### ISSUE TITLE
discuss using a panic internally in the commands lib

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1182]
All over the place in the commands lib, we use:
```go
if err != nil {
    res.SetError(err, cmds.ErrNormal)
    return
}
```

This is kindof ugly to write, mostly because we need to remember the return statement.

I propose that we throw a panic inside of SetError, and recover it in the function that calls run. (oh no! exceptions!). 

I think this will make the code a little bit cleaner for users to write their own commands, and also lower the chance of accidentaly forgetting to return and continuing on in an error case (this has happened...).

I'm not saying we *have to* do this, just something I would like to discuss.

@jbenet @tv42 @wking

**Comment by whyrusleeping** [comment]
or really, we could just make the Run function return an error...

**Comment by whyrusleeping** [comment]
after some more 3am thinking on this, the only reason we dont just return err right now is because we set a type on it. I think a better way to do this would be to have a wrapper for the `ErrClient` like:
```
if err != nil {
    return cmds.ErrClient(err)
}
```

And then outside of that we can type switch around to get the type information we need.
In the normal case (cmds.ErrNormal) we can just return the error, no need to wrap it.

**Comment by cryptix** [comment]
+1 on custom error types. This setter getter business is not idiomatic.

**Comment by wking** [comment]
On Sat, May 02, 2015 at 01:55:55AM -0700, Jeromy Johnson wrote:
> I propose that we throw a panic inside of SetError, and recover it
> in the function that calls run. (oh no! exceptions!).

I like exceptions, but then I mostly write Python ;).  I'm happy to
defer to native Go speakers on this one.

**Comment by tv42** [comment]
Yes, return an error. You don't have the obscure control flow that e.g. `encoding/json` uses as its excuse to use panics internally.

**Comment by jbenet** [comment]
FWIW, i'd like to get rid of this problem too. it's annoying, and error prone. 

To give you a sense of the history here, though: The commands lib _used to_ return an error. the reason it looks like this now is because we switched to emulating the http library (req/res pair). We've switched back and forth _many_ times now because we keep running into problems with the model. 

The commands library is really complex, and ultimately it's dealing with a lot of complexity in possible transports and so on. It's really not an easy thing to wrestle. I'd like to make it much simpler and easy to reason about, and I think moving fully in http's direction is the right thing to do.

I don't think a panic is the right thing to do, and we've already tried the "return an error" way. In general, the http stdlib pkg and the number of http server libraries out there (like gorilla) should give us good examples to follow. Our commands lib operates over http as a transport and has many of the same modes of operation (_streaming_, user errors, server errors, cancellation, etc).

--- 

perhaps an easy thing to do here, if we _want_ most commands to use an error return is to use a wrapper that sets the error for the user:

```
func (req Request, res Response) {
  ret, err := run(req, res)
  if err != nil {
    res.SetError(err, cmds.Normal)
  } else {
    res.SetReturn(ret) // or whatever. (not exact syntax)
  }
}
```
do note that this -- error return -- is actually mixing metaphors: it has the (req, res) pair AND return values. that may be _more_ error prone and confusing.  (the req/res pair is unavoidable, because options + args  may need be read, and headers may need to be set.)

**Comment by jbenet** [comment]
Anyway, i think maybe a way fwd is to reason carefully about target interfaces to expose first, and then change the cmds lib to give us that. Maybe we can write some simple examples here.

**Comment by whyrusleeping** [comment]
```
func Run(req cmds.Request) (interface{}, error}
```

Is what i'm thinking about now.

**Comment by whyrusleeping** [comment]
The 'lets pretend to be http' model is bad IMO, at least at this layer, if we want to keep it working this way, we can just have the caller of `Run` set the values in the response object, no need for the 'user' to have to muck around with it.

**Comment by cryptix** [comment]
> func Run(req cmds.Request) (interface{}, error}

@whyrusleeping I started hacking with that, too. Do you feel a strong urge to have a go at this? otherwise I can tackle it next sprint maybe.

Although it's not very pressing issue, I think we need somebody to that is maintaining that.
I know it has complex requirements but I really think it can be implemented cleaner.

**Comment by whyrusleeping** [comment]
@cryptix its all yours! I'm supposed to be focusing on perf, lol

**Comment by jbenet** [comment]
Guys seriously, that's the interface we had and _had to_ change. Please look into both the history and the exact existing uses before attempting-- else will just waste time.



—

**Comment by whyrusleeping** [comment]
@jbenet I dont get the 'had to' part. I see no reason why we 'had to' change it to this, it makes no sense at all

**Comment by whyrusleeping** [comment]
I would be fine doing the wrapper you mentioned here: https://github.com/ipfs/go-ipfs/issues/1182#issuecomment-98391379

But i think exposing that weird, un-idiomatic quasi-http stuff to the writer of a command it not the right thing to do.

**Comment by whyrusleeping** [comment]
i still think changing this interface would make things more pleasant, closing for now to avoid further bikeshedding
