### ISSUE TITLE
ipfs refs --recursive --unique is not recursive

### ISSUE THREAD

**Issue by MichaelMure** [ipfs/go-ipfs#1211]
$ ipfs refs --recursive Qmb8Hct2kCaPskyDuY9e6V9pUUUBAPMinZXAyVj9CrELk2
    QmcM14fEAVpJpJ8ymvG4HtEz8N29iEyJBYm7vRWhjtaBJk
    QmToBjWSFNGFngp641WZGJBMiY3JUMiG6KvTp26hMrrLVU
    Qmc3RTuTfmtDXtDto8v7iScQfeCtsPUQ1ednfwStMoQh1r
    QmSwiFcSfTMiBwG6P6JwQ9HtU6tyAYiCJQujf88HQxeJhF
    QmVP3RnEXpsm5onMwGivopoFx1iFWKX5e4z7s1hDTb6c8r
    QmaPqrCjCfNdyCEkc3RTA5AYWfEaD6jTrExoNrRutnsRW3

    ....

    QmS1gt76QqZsN222f5ZciAHADLZLcStoXofrU9HqNs5938
    QmYSdPJVuSzChf1Ku3iiAEExBus4qfK1W9e7oHjm4mu8Ef
    QmZiqP1CjAVetDEteox9WJUJDSiGwVMQnecUidA5dqQYcx
    QmNYXefsUHmjyhK4cr3Y562nhc9zNPtxpvuNxz2iEHRVNJ
    QmX1UQiMYPTpkvvV9So93jb5pYdKiuKhaGZEwckGe9GSji
    QmVSdELUEUUg5aPo1G7DwZtEVW2Mwdfc8pEdCEtPqArmeG

    $ ipfs refs --recursive --unique Qmb8Hct2kCaPskyDuY9e6V9pUUUBAPMinZXAyVj9CrELk2
    QmcM14fEAVpJpJ8ymvG4HtEz8N29iEyJBYm7vRWhjtaBJk
    QmdqDBerv9hnC445NDuA7q9tfE6JL24rmPDC3MV3X63V5T

When using --recursive and --unique, only the direct childs in the dag are listed. I would expect all the childs (recursive), but deduplicated

**Comment by jbenet** [comment]
@MichaelMure was this fixed with #1212 ?

**Comment by MichaelMure** [comment]
Just updated my master, it's still here.

**Comment by gatesvp** [comment]
I could not download the original hash listed in the ticket, but I did manage to repro this locally with some experimentation.

I think the fix is relatively simple, we just need to kill this `if` statement: https://github.com/ipfs/go-ipfs/blob/master/core/commands/refs.go#L235

That stated, this probably deserves some extra `sharness` tests because there's nothing really covering this type of bug. I will cook this up shortly.

**Comment by jbenet** [comment]
> I think the fix is relatively simple, we just need to kill this if statement: https://github.com/ipfs/go-ipfs/blob/master/core/commands/refs.go#L235

sounds right to me

**Comment by MichaelMure** [comment]
Just tested, this is fixed. I guess the good thing is to close the bug. Thanks !

**Comment by jbenet** [comment]
:+1:
