### ISSUE TITLE
Release branches?

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1309]
Perhaps we should use a `release` branch for the gobuilder releases and only merge things to that when we cut a release. 

that way we dont have random builds in the wild that we don't intend to, and we can feel more comfortable merging migration-needing things into master.

**Comment by jbenet** [comment]
cc @whyrusleeping @krl @cryptix @lgierth @chriscool @tv42

**Comment by wking** [comment]
On Sun, May 31, 2015 at 02:49:58PM -0700, Juan Batiz-Benet wrote:
> Perhaps we should use a `release` branch for the gobuilder releases
> and only merge things to that when we cut a release.

I expect we want to default folks using ‘go get …’ to the released
branch too, so maybe we want releases in ‘master’ with unreleased
development in ‘develop’ (or ‘next’ or whatever)?

**Comment by jbenet** [comment]
> I expect we want to default folks using ‘go get …’ to the released

I think we're going to _have to_ give up 'go get ...' anyway. other things (like bindings to clibs, using our own tool for package management, etc) are all stacking up against this impediment. `go get` feels nice, but it's not hackable and too constraining.

**Comment by whyrusleeping** [comment]
> I think we're going to have to give up 'go get ...' anyway. 

yeap, as much as i've fought it, i have to concede to this defeat.

**Comment by cryptix** [comment]
Hey, I'm all for release branches as well.

And I think we can remain `go-getable` to a certain degree so that the switch over isn't to painfull. For instance, [syncthing](https://github.com/syncthing/syncthing) has a pretty solid release story. They advertise other ways to download binaries and have a custom build tools but if you have everything in place, you can still `go get` it.

We need to phase out documenting approach this sooner or later anyway. It's already broken for Windows (a missing dependency which is only imported when compiling for that platform - godeps can't deal with that) and I fear there are other odd edge cases we haven't seen yet.

That beeing said, I'd like to prepare a [gb](https://getgb.io) branch during the next sprint if there are no objections. After seeing Dave's [talk](https://www.youtube.com/watch?v=c3dW80eO88I) and comparing other tools to his, I think he is the strongest contender with the most conclusive rationale of how vendoring needs to be delt with and it comes with a couple of other nice features because of how it does things.. Don't want to derail this further though, we can discuss this tonight and on another issue.

**Comment by tv42** [comment]
Here's a -1 vote for `gb`. It's a moving target with unclear goals. State your requirements, look for something based on those, instead of flocking to something shiny.

If you just want vendoring while getting rid of the `github.com/ipfs/go-ipfs/Godeps/_workspace/src` prefix in all imports, all you need is a thing that manipulates `GOPATH`. That can be either a bundled `build.go` or something like https://github.com/skelterjohn/wgo -- none of that requires the rube goldberg machine of `gb`.

Also, this is unrelated to a whether there's a release branch / whether `master` only gets known-good commits every week or so -- maybe talk about it in a different issue?

**Comment by jbenet** [comment]
> And I think we can remain go-getable to a certain degree

No, we really cannot. We will be using cgo. We will also be using our own vendoring tool based on ipfs, which precludes go get entirely.

> gb

No. We will not use gb. it's a step forward, but not large enough, and it's model is also wrong. it does not even accept that libraries must to vendor their deps.

**We will use our own tool that uses ipfs to vendor. we will self host and dogfood. **

**Comment by jbenet** [comment]
![](http://gifsec.com/wp-content/uploads/GIF/2014/10/Anyway-David-Tennant-Doctor-Who-So-Anyway-GIF.gif)

---

I'm wary of moving the default branch to anything other than master, as people tend to just PR against master, and do so from other tools like `hub`. I think shifting the default branch will add a lot of noise. 

how about:
- tag every release (as we do)
- create `stable` branch, point it to latest _tagged_ release
- change links from ipfs.io/docs/install and https://www.npmjs.com/package/go-ipfs to use `stable` instead of `master` (so we dont have to change links manually)
- `master` must still pass all the tests all the time, but it's not _shipped_ to users until it's released.

**Comment by lgierth** [comment]
:+1:

Bonus points: signing the tags

**Comment by jbenet** [comment]
> Bonus points: signing the tags

ah yep! fixed above.

**Comment by Kubuxu** [comment]
I greatly agree with using release branches. It allows to fully implement gitflow (where already development is performed in almost gitflow way).

**Comment by whyrusleeping** [comment]
we have a release branch and signed tags for releases. i think we can close this

**Comment by jbenet** [comment]
We won't use gitflow. gitflow is unnecessarily complicated and wastes a lot
of time (I've used it many times in different teams and of different sizes
-- and every time it ends in arguments and painful removal after months of
wastig time). It would add 2-3 branches to our setup depending on how. We
saw how bad that hurt us already (having long running branches being merged
to separate from hotfixes)

I need to review this before I would say I agree with it still (I've
learned more) but: https://gist.github.com/jbenet/ee6c9ac48068889b0912
