### ISSUE TITLE
missing dependency is godeps directory

### ISSUE THREAD

**Issue by jcftang** [ipfs/go-ipfs#1410]
```
jtang@awesome-o-w:[(none)@master]go-ipfs$ go get -d -u ./...
package github.com/jbenet/go-ipfs
	imports github.com/jbenet/go-ipfs/assets
	imports github.com/jbenet/go-ipfs/blocks
	imports github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-base58
	imports github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-datastore
	imports github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-datastore/query
	imports github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess
	imports github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/satori/go.uuid
	imports github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-multihash
	imports github.com/ipfs/go-ipfs/Godeps/_workspace/src/golang.org/x/crypto/sha3
	imports github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/mitchellh/go-homedir
	imports github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/whyrusleeping/go-logging
	imports github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/whyrusleeping/go-logging
	imports github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/whyrusleeping/go-logging: cannot find package "github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/whyrusleeping/go-logging" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/whyrusleeping/go-logging (from $GOROOT)
	/Users/jtang/develop/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/whyrusleeping/go-logging (from $GOPATH)
```

I looks like there is a missing library which isn't vendored for a clean build.

**Comment by whyrusleeping** [comment]
@rht you wanna field this one?

**Comment by cryptix** [comment]
This is a nasty side effect of using `go get -d`

```
The -d flag instructs get to stop after downloading the packages; that is,
it instructs get not to install the packages.
```
It than can happen that unchanged installed packages try to link against code thats no longer there. (like with the logging consolidation now)

@jcftang can you try updating with 'git pull'? Since go-ipfs vendors all its dependencies there is no need to use the go tool to update other ones.

**Comment by rht** [comment]
i c, so either 1. vendored deps have to stay semi-indefinitely for compatibility with older versions, or 2. `go get` simply doesn't have to update `github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/whyrusleeping/go-logging` (it could additionally check that this Godeps package still exists for earlier revisions).

**Comment by jbenet** [comment]
@rht could you explain more? i didnt understand

**Comment by jcftang** [comment]
@cryptix I've pulled to 3a1c8d7a535ecfeb976d8b49ab90197807491896 , I've just manually installed go-logging and the build error went away for me.

**Comment by jbenet** [comment]
@jcftang 

> I've just manually installed go-logging and the build error went away for me.

you shouldn't have had to-- what package imports it?

**Comment by jbenet** [comment]
@jcftang also try: 

```sh
go install -a cmd/ipfs
```
should clear up any stale built things

**Comment by jcftang** [comment]
@jbenet I've done as you suggested and I've cleared out the some of the .a libs that go stores in the pkg directory and rebuild it all. I'm not seeing the problem anymore. I'd be inclined to close this ticket since it's working for me now. Thanks

**Comment by rht** [comment]
> @jcftang can you try updating with 'git pull'? Since go-ipfs vendors all its dependencies there is no need to use the go tool to update other ones.
Doesn't `go get -d -u` already do `git pull`?

> It than can happen that unchanged installed packages try to link against code thats no longer there. (like with the logging consolidation now)

Assuming that `go get` already runs the `git pull`, does that mean the issue is solved with `go install -a cmd/ipfs` / `go get -u` (without `-d`)?

@jbenet I'm just wondering of how the previous versions can still build the package and update Godeps without having to check the latest non-existing `github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/whyrusleeping/go-logging`. But since the version/hash of Godeps is essentially tied to the hash of the repo, a Godeps update means a necessary update of the repo as well. So there is no need to do either of my suggestion. Just my lack of understanding.

**Comment by whyrusleeping** [comment]
this has been resolved.
