### ISSUE TITLE
crypto uses rand.Reader directly.

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#143]
We use `rand.Reader` directly in the crypto package, which makes it depend on the global seed. We should be using a specific, configurable `rand.Source`, like `crypto/tls`: 
http://golang.org/src/pkg/crypto/tls/key_agreement.go#L214 

```Go
// crypto/tls
ka.privateKey, x, y, err = elliptic.GenerateKey(ka.curve, config.rand())
```

**Comment by rht** [comment]
I don't think the purpose of having a ```Rand``` field in ```crypto/tls``` is so that people can use different source for different instances in their code.
I could be wrong, but the point is it allows one to use a different random source (that is not available through ```crypto/rand```) for the entire program.

The default ```rand.Reader``` already suffices as a CSPRNG[1].
Any userspace (```math/rand```) approach with seeds from ```crypto/rand``` is still less secure than using ```crypto/rand``` directly with its single global seed[2].
The only reason why this ```config.rand()``` needs to be implemented is if accessing the global source is a major performance bottleneck[2].

[1] http://www.2uo.de/myths-about-urandom/
[2] https://news.ycombinator.com/item?id=7610273.

**Comment by jbenet** [comment]
thanks @rht -- that makes sense. probably still good to do. another reason is to mock it out to run tests faster

**Comment by rht** [comment]
```/dev/urandom``` (```rand.Reader```'s default for linux, os x, freebsd) can be used right away, at the expense of lower entropy and still be more random than ```math/rand```.

**Comment by whyrusleeping** [comment]
@rht but for tests, we dont care about randomness, we just want it to be 'random enough' and fast so our tests can not take forever

**Comment by rht** [comment]
```rand.Reader``` is non-blocking unless the test reaches its concurrent limit.

From https://travis-ci.org/ipfs/go-ipfs/jobs/65047346, ```make $TEST_SUITE``` took 298.93s, 283.137s of which is from github.com/ipfs/go-ipfs/exchange/bitswap.
Can't further tell if ```rand.Reader``` is a major bottleneck here, but I will try swapping with ```math/rand``` and check the perf increase later.

For the sharness test, I replaced https://github.com/ipfs/go-ipfs/blob/master/test/sharness/lib/test-lib.sh#L58
with ```sleep 0.1```.
I discovered a ~1 min speedup from
```make  24.52s user 6.43s system 15% cpu 3:25.66 total``` to ```make  24.71s user 6.20s system 22% cpu 2:19.29 total```.

**Comment by jbenet** [comment]
hardware differs. for my macbook air, `math/rand` is much faster for me than `crypto/rand.Reader`

**Comment by jbenet** [comment]
> For the sharness test, I replaced https://github.com/ipfs/go-ipfs/blob/master/test/sharness/lib/test-lib.sh#L250 with sleep 0.1. I discovered a ~1 min speedup from

ohh wow, yeah. submit a PR?

**Comment by rht** [comment]
The changes are within standard deviation https://github.com/ipfs/go-ipfs/pull/1326, so it's not much apparently. The PR only makes the checks more granular.

**Comment by whyrusleeping** [comment]
closing, if further discussion is warranted open a new issue.
