### ISSUE TITLE
Back door random compression trick? #BigData

### ISSUE THREAD

**Issue by aunk** [ipfs/go-ipfs#1768]
By using my aunk/comb repo, and a little TLC, we can wager that the compression of random data is possible. In fact, it may be very compressible. I just need a contributor who would do compile tests for me, and tell meofthe compiler output if it doesn't compile, and if it does, the output of the program. Just compress and decompress. Use a 10k random file from random,org file. This would be good at handling video for ipfs. It's very small. It's a spaghetti plate though, but the spacing clears it up. If it keeps all the data, since this is a prepper for the compression itshould compress when you use it, i just needto nw that the input comes out after output, correctly. Thanks

**Comment by jbenet** [comment]
@aunk, to be frank and direct, i can't tell if you're trolling, or really don't know what you're doing. But, I'll give you the benefit of the doubt.

> compression of random data is possible

By definition, this is impossible. (random data is defined as incompressible, if you find a way to compress the data, it is no longer random. cryptographically secure randomness is indistinguishable from a uniform distribution).

Your code -- https://github.com/aunk/comb/blob/master/Comb.cpp -- is on the path to obfuscation. I can't read more than 8 lines without giving up. Learn to clearly decompose and comment.

If you keep at it, and you manage to make a correct program (that compiles and succeeds in compressing data), then produce **reproducible benchmarks** over a **variety of workloads**, that show the drastic improvement over other compressors. This means a running program, input data, graphs with the results, and so on. So that anybody else can run the benchmarks again in <1min. I'm sorry, but nobody is going to waste time on statements that are nonsensical, dubious, or obviously wrong, or on code that is painful to read and doesn't even compile. :disappointed: 

I don't mean to be rude, but please stop opening this kind of issues here. Thanks.

**Comment by aunk** [comment]
Sorry, im not trolling, no. I need to get it right I know. I was just hoping someone would help me. Then it'd be working and be ready for benchmarks. Youre not being rude, either. Apparently this is how everyone feels about new coders. I haven't been able to meet anyone that would help.

Spaghetti sucks,too. The output of my program isnt comoressed though. It's prepped to be comoressed more than a normal amount, by segregating bits from others. These are kept to themselves. And by doing so, you limit the number of unique byte sequences. That's all.

Sorry. Just wanted it to go world wide quick,
