### ISSUE TITLE
bitswap net notifee misunderstanding (bug)

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1809]
after way too much debugging, i discovered the issue for the halting we saw in the utp test.

It comes down to a misunderstanding between how the `Connected` and `Disconnected` notifications work, I expected `Disconnected` to only be called when we actually disconnect from a peer. But what i have observed happening is that we somehow (havent figured this part out yet) get two connections open to a given peer which calls `Connected` at least once (read: twice). This tells bitswap to open up a worker for that peer in the wantmanager, shortly thereafter, one of those two connections is broken, and the `Disconnect` notification is sent to bitswap. This makes bitswap close down the worker, and results in us never being able to send that peer our wantlist updates, even though we still have an open connection to them.

This is either:

A) A bug in bitswap, I should check to make sure we have zero open connections to a peer before actually stopping their worker, or

B) A bug in the network somewhere, why are we allowing two connections to the same peer? Thats weird, and: Should we send a Disconnect notification for a peer if we're still connected to them?

(or 'C' both)

**Comment by whyrusleeping** [comment]
After further testing, I've found that I actually will sometimes receive more disconnect notifications than connect notifications... So that messes up the refcounting solution that I had written...

I'm also fairly convinced this bug is the cause of all the random 'bitswap hung' problems we have seen.

**Comment by jbenet** [comment]
>  I expected Disconnected to only be called when we actually disconnect from a peer. 

you're right. this should be the right way to do it. well, maybe actually. depends on the function. i would expect something like:

```go
// called only after fully disconnected
func (n *notifiee) Disconnected(peer.ID) {}

// called for every connection breaking:
func (n *notifiee) Disconnected(peer.ID, conn.Conn) {}
```
we could alter as you see fit here.

---

> A) A bug in bitswap, I should check to make sure we have zero open connections to a peer before actually stopping their worker, or
> B) A bug in the network somewhere, why are we allowing two connections to the same peer? Thats weird, and: Should we send a Disconnect notification for a peer if we're still connected to them?
> C) both.

I think it's C. because:

- the network should do one of the above function calls.
- but bitswap SHOULD STILL check again. notifications may arrive out of order. e.g., if a peer connects, disconnects, and connects again rapidly, bitswap **could** receive notif calls:  `Connect -> Connect -> Disconnect`. dont see an easy way around this without lots of change.

> But what i have observed happening is that we somehow (havent figured this part out yet) get two connections open to a given peer which calls

Simultaneous open will cause two connections often. this is fine. i used to deal with it with the `Multiconn` but it wasn't needed. in the future we may resurface it, and do smart connection selection based on measurements. (and possibly even something like [multipath](https://en.wikipedia.org/wiki/Multipath_TCP), if the bw is additive -- i.e. different networks).


cc @diasdavid definition update:
- simulcast -- broadcasting _the same stream_ across multiple paths. See https://en.wikipedia.org/wiki/Simulcast
- multipath -- making use of multiple paths between two hosts, in which the bandwidth adds up. implies multihoming. (e.g. WIFI + Cellular). see https://en.wikipedia.org/wiki/Multipath_TCP (multi!) [0]
- multihoming -- an IP host with interfaces in multiple networks.

[0] funny story time: turns out that as a wee "intro to computer networks" student, i was surprised to find out that kernels were not yet doing something like what MPTCP eventually did, so i thought about implementing something. I briefly looked into it, found a mountain of gross hackery awaiting, and then got distracted by homework. This was ~2008, and i think proper MPTCP was already in development, though not yet out. i wasn't obsessed with the multis yet, so who knows if i would've named it that, but it's a really funny coincidence and i'm glad it turned out this way.

**Comment by whyrusleeping** [comment]
@jbenet last night I implemented a ref-counting sort of deal to prevent bitswap from closing workers early, and then my test still failed. So i printed out the incref and decref for the peer in question:
```
➜  trash directory.t0130-multinode.sh git:(feat/utp) ✗ cat .iptb/4/daemon.stderr | grep c4j
time="17:52:14:000" level=error msg="peer connected! <peer.ID c4jGXp>" module=bitswap 
time="17:52:14:000" level=error msg="peer connected! <peer.ID c4jGXp>" module=bitswap 
time="17:52:14:000" level=error msg="peer disconnected: <peer.ID c4jGXp>" module=bitswap 
time="17:52:14:000" level=error msg="peer disconnected: <peer.ID c4jGXp>" module=bitswap 
time="17:52:14:000" level=error msg="peer disconnected: <peer.ID c4jGXp>" module=bitswap 
time="17:52:14:000" level=error msg="CLOSING PEER HANDLER: <peer.ID c4jGXp>" module=bitswap 
time="17:52:14:000" level=error msg="peer disconnected: <peer.ID c4jGXp>" module=bitswap 
time="17:52:14:000" level=error msg="peer connected! <peer.ID c4jGXp>" module=bitswap 
time="17:52:14:000" level=error msg="peer disconnected: <peer.ID c4jGXp>" module=bitswap 
time="17:52:14:000" level=error msg="CLOSING PEER HANDLER: <peer.ID c4jGXp>" module=bitswap 
```

I have no idea why this is happening, but as you can see, more disconnects than connects are being sent...

**Comment by whyrusleeping** [comment]
this appears to be the issue: https://github.com/jbenet/go-peerstream/pull/20

**Comment by whyrusleeping** [comment]
fixed!
