### ISSUE TITLE
ipfs log level [system] [level] is broken

### ISSUE THREAD

**Issue by MichaelMure** [ipfs/go-ipfs#1874]
Step to reproduce:

> ipfs log level all info

--> I can see some logs, bitswap included

> ipfs log level all panic
> ipfs log level bitswap info

--> no log shown

**Comment by whyrusleeping** [comment]
thanks for reporting. This is indeed broken...

**Comment by whyrusleeping** [comment]
@rht do you think I could get a hand on this one?

**Comment by rht** [comment]
This is because there is no way to set log level threshold for each `logrus.Entry`.
Creating a new logger (instead of entry) for each module won't do, since logger doesn't store fields.

Though here is one way to do it (fork `logrus.Entry` to contain threshold field) https://github.com/rht/go-ipfs/commit/9e26753bc41c32ea3513f6e5902e12d6e07d279b.

**Comment by whyrusleeping** [comment]
i think this has been fixed, we don't use logrus anymore
