### ISSUE TITLE
webui broken?

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1883]
can't use the webui in 0.3.8 -- looks like some permission errors-- others seeing this?

**Comment by VictorBjelkholm** [comment]
Seeing this on go-ipfs/0.3.9-dev too

<img width="388" alt="screen shot 2015-10-22 at 13 21 56" src="https://cloud.githubusercontent.com/assets/459764/10663983/e89e63dc-78bf-11e5-8849-b128a838ca7e.png">

**Comment by whyrusleeping** [comment]
Hrm, its working fine on my machine... (not that that means much).

@VictorBjelkholm your issues look like CORS problems, which is definitely strange.

 @jbenet what problems were you seeing? what do you mean by 'cant use the webui' does it not load? do things not come up?

**Comment by VictorBjelkholm** [comment]
@whyrusleeping it's definitely not a CORS problem. First, the requests happen from one domain, to the same domain but different path. Also, get the same response using cURL.

**Comment by whyrusleeping** [comment]
> To add some debug information, I'm accessing the webui on a different machine, not on my local machine, if that could be the issue.

Are you running it with the CORS headers set correctly for that machine? by default the api requests the webui uses can only be made from the localhost, in your setup (accessing from a different machine) those calls would be made from your browser (on a different machine/host).

**Comment by VictorBjelkholm** [comment]
@whyrusleeping I'm not supposed to have to set the `Origin` header of CORS if the requests are made to/from the same domain. It's only supposed to reject the request if CORS headers are missing **and** the request is to/from different domains/subdomains/ports.

Seems like the API that the webui is using is unnecessary restrictive. Looks like the request is invalid if I set the `Refer` header, even if the `Refer` is the same as the actual host the daemon is running on. Without any headers at all, I can perfectly fine access the API. With `Refer` header set to anything, the request results in 403.

**Comment by jbenet** [comment]
@VictorBjelkholm i think you're right.

**Comment by jbshirk** [comment]
I stopped using the webui before updating to 0.3.8 because i couldn't use it to add assets, list peers, and after a while it stopped listing new assets, etc, but it least it showed me my correct id and the assets I had initially added a month or more ago.

I have done only one 'init' but today I noticed that the web ui does not show my correct id anymore.

    ipfs id
    {
        "ID": "Qme67efGcE9iX6r8Wk6CrHUsmWckLbnMHQ19g5YK15doUY",
        "PublicKey": "CAASpgIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCxK48Krv/otuLLipnMoyhAksS2q+X5BDBROw/wRrDwjKDJD8HUu+YKOJ+boo3lrmmG5Iq+mMVNVWSdzgFnv43JVx/DJ1KzzmpaMIfBDjtwgKXvnnuoCcE8sBF0IaClEWGQaSPR1waI4fPeCbSAP9TUg8eOq0Jlwv78xsFgO9Eown6s1arGlP0cm+UP1FlGNYo0YAnCT6WL9NqxhQJJiTHrWCBPtUD+5/SHbBXQ1LUdc5MzaRnkkh3ja6hWpKWdmD0HtWISbeW7yO/fnacS4rwSbz5LLHMKtW9MxJJo8pnLuGSpOh+0Rj4zLYpiBkj26NTjngOfqB5n9wh4DKqnzzjxAgMBAAE=",
        "Addresses": [
            "/ip4/127.0.0.1/tcp/4001/ipfs/Qme67efGcE9iX6r8Wk6CrHUsmWckLbnMHQ19g5YK15doUY",
            "/ip4/192.168.1.3/tcp/4001/ipfs/Qme67efGcE9iX6r8Wk6CrHUsmWckLbnMHQ19g5YK15doUY",
            "/ip4/71.101.244.185/tcp/4001/ipfs/Qme67efGcE9iX6r8Wk6CrHUsmWckLbnMHQ19g5YK15doUY"
        ],
        "AgentVersion": "go-ipfs/0.3.8",
        "ProtocolVersion": "ipfs/0.1.0"

when I go to `http://localhost:5001/webui` it lands here:
    http://localhost:5001/ipfs/QmS2HL9v5YeKgQkkWMvs1EMnFtUowTEdFfSSeMT4pos1e6/#/files

![localhost5001ipfsqms2](https://cloud.githubusercontent.com/assets/3949396/10938967/37bdc5a0-82cc-11e5-97df-32bafae14fe7.png)

When I go to my original (bookmarked) webui address, 
    http://localhost:5001/ipfs/Qme67efGcE9iX6r8Wk6CrHUsmWckLbnMHQ19g5YK15doUY/#/files

I now get:
![localhost5001ipfsqme6](https://cloud.githubusercontent.com/assets/3949396/10938995/65f53c6e-82cc-11e5-9316-d09e8da30dbc.png)

I emphasize that from the shell, I can add assets, list assets, list swarm peers. I don't really want to do another init and lose my id and the assets in it.

Maybe/maybe not relevant:
I discovered this after noticing that new adds take a long long time to get out to the ipfs net, timing out with this message:
     Path Resolve error: context deadline exceeded

But again, they do eventually make it.

**Comment by jbshirk** [comment]
![localhost5001ipfsqmbm-home](https://cloud.githubusercontent.com/assets/3949396/10940530/d7e57c32-82d4-11e5-888c-0f4a5bc1de29.png)

**Comment by jbshirk** [comment]
Ah excuse me, I just realized that `QmS2HL9v5YeKgQkkWMvs1EMnFtUowTEdFfSSeMT4pos1e6` is the webui hash, not anything to do with my ID. This is subtracted from the mystery AFAIAC.

**Comment by MichaelMure** [comment]
I had the same problem, and after adding `http://127.0.0.1` and `http://127.0.0.1:5001` in `API.HTTPHeaders Access-Control-Allow-Origin`, the webui finally load fully and works correctly.

**Comment by diasdavid** [comment]
@MichaelMure I believe that is because only 'localhost:5001' is whitelisted to bypass CORS

**Comment by MichaelMure** [comment]
I think someone can close this one as https://github.com/ipfs/go-ipfs/pull/2021 got merged.
