### ISSUE TITLE
s/cancelled/canceled/g for contexts.

### ISSUE THREAD

**Issue by rht** [ipfs/go-ipfs#1994]
`golang.org/x/net/context` uses 'canceled' in its err messages, comments, and naming. For consistency's sake, err messages, comments, and naming of the code that are derived from the package should use 'canceled' as well.

For the rest?

(beside, natural lang tends to evolve over time towards using more regular grammar)

Edit: clarification of the rationale

**Comment by jbenet** [comment]
sounds good

**Comment by yuvallanger** [comment]
Is this issue resolved, @rht?

**Comment by rht** [comment]
Not yet, feel free to ...resolve it.

**Comment by RichardLitt** [comment]
I would use `cancelled`, because the one `l` variant is only American, and not fully established. [Source](http://grammarist.com/spelling/cancel/). AmEnglish is only one type of English; when there are variants that also work in BrEnglish, I would suggest using those.

**Comment by rht** [comment]
@RichardLitt are you suggesting to pick which one is the canon by looking at the ngram usage of the combined corpus of `en-*`? (though one could have restricted the sampling to `en-*` in the web/code, excluding the ancient texts)
If so, this kind of fix should be proposed to `golang.org/x/net/context`. The err I'm addressing here is specifically about usage consistency with that lib. While it is possible to localize representation of err messages (en-us, en-uk, ...), this is not yet the case with source code (the naming and comments). The compiler doesn't know that 'cancelled' and 'canceled' both refer to the passive form of 'cancel'.

A historical example would be the http referer case.

**Comment by jbenet** [comment]
this isn't about english, it's about matching usage in `net.Context`. we should either
- do what they do
- not care and let the compiler correct us

**Comment by RichardLitt** [comment]
I'm suggesting standardizing dialectical variation of `cancelled` and `canceled`, although I wouldn't necessarily use just frequency in a corpus to test that. [Google ngrams](https://books.google.com/ngrams/graph?content=canceled%2C+cancelled&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Ccanceled%3B%2Cc0%3B.t1%3B%2Ccancelled%3B%2Cc0) shows they are used about the same, with one-l more common since computers. 

But @jbenet is right. My bad, then. I'd say do what they do. I can look into proposing a fix to golang, maybe.

**Comment by jbenet** [comment]
> I can look into proposing a fix to golang, maybe.

don't bother, it would break interfaces and thus would not do it.

**Comment by RichardLitt** [comment]
cool. Won't. :)

**Comment by rht** [comment]
(to err and be corrected by the compiler is human)
