### ISSUE TITLE
"Slow filesystem" caching layer

### ISSUE THREAD

**Issue by kyledrake** [ipfs/go-ipfs#2018]
Related to #2016 and #2017.

IPFS will require a "Slow Filesystem" caching layer for efficient cloud object storage usage.

You can see a flavor of this in [nginx slowfs cache](https://github.com/FRiCKLE/ngx_slowfs_cache/), an nginx caching module that is designed for caching network mounted filesystems locally. S3 is the slow disk, the local disk is the fast one. This will be important for both cost and performance reasons.

Some examples of what this could do:
- Caching of requested/busy slowfs data on the local disk
- Only store pinned data remotely, using the local disk for ephemeral data caching
- A cache of the hashes stored remotely, to prevent cost and performance issues from P2P network
  requests for data. Hitting S3 for each incoming request would be very costly

**Comment by jbenet** [comment]
look into https://github.com/jbenet/go-datastore/ -- this is trivial with a TieredDatastore -- https://github.com/jbenet/go-datastore/blob/master/tiered/tiered.go -- and this is not specific to bucket clouds, datastore is generic and meant to be composed as desired. we just havent made it easy to do so because we broke the abstraction along the way, but we're getting it back.

**Comment by whyrusleeping** [comment]
I think that the tiered datastore solves this issue, we should make the datastore code more configurable from the ipfs config.
