### ISSUE TITLE
"peerstream listener failed" error on p2p/net/swarm go-tests

### ISSUE THREAD

**Issue by thelinuxkid** [ipfs/go-ipfs#2094]
The [travis-ci go tests](https://travis-ci.org/thelinuxkid/go-ipfs/jobs/97425303) throw this error. I cannot reproduce these locally. I have only seem this error after e37208095e1f36a82e3b2c4554b74345ebba8931, but, it could be unrelated.

As mentioned in #2095, I created [travis-rerun](https://github.com/thelinuxkid/travis-rerun) to mirror the travis-ci environment offline and was able to reproduce the error.

I am still looking into the cause.

**Comment by thelinuxkid** [comment]
Travis' Trusty build doesn't have ipv6 support yet. TEST_NO_IPV6 flag was added in dcc9f212ad12e47fd2097e1b79fe77ed7e5f1900

**Comment by whyrusleeping** [comment]
Yeah, a few of the swarm tests randomly fail due to kernel stuff on whatever machine they are running on. Apparently provisioning hundreds (thousands?) of sockets over and over again is hard? Unless youre working on stuff related to the network stack, its generally alright to ignore those (but do keep an eye out for ones that look different)

**Comment by thelinuxkid** [comment]
You might be able to get the kernel runtime parameters and use them to limit the ipfs tests. But, I don't know if it's worth it.
