### ISSUE TITLE
TestFilePersistence and TestMultipleDirs fuse tests fail

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#2214]
Moving https://github.com/ipfs/ipfs/issues/153.

@thelinuxkid said:

> https://travis-ci.org/thelinuxkid/go-ipfs/jobs/102976905#L252
> https://travis-ci.org/thelinuxkid/go-ipfs/jobs/102976905#L255

**Comment by thelinuxkid** [comment]
For TestFilePersistence, reading the file right after writing alleviates the problem most of the time. But, that could be completely unrelated or just chance. Maybe someone with more fuse experience like @whyrusleeping or @tv42 can enlighten. 
```
    data := writeFile(t, 127, mnt.Dir+fname)

    b, e := ioutil.ReadFile(mnt.Dir + fname)
    if e != nil {
        t.Fatal(e)
    }
    for _, _ = range b {
    }

    mnt.Close()
```

**Comment by tv42** [comment]
Sounds like the Lookup doesn't find that file, regardless of whatever earlier success was reported for the file write. FUSE debug log might be useful to confirm that. Sounds like a bug in IPFS directory data structure management.

**Comment by thelinuxkid** [comment]
The nodes aren't being closed correctly, therefore, the data is not always written to the datastore when unmounting. The solution involves using https://godoc.org/bazil.org/fuse/fs#HandleFlusher and https://godoc.org/bazil.org/fuse/fs#HandleReleaser instead of Forget, https://github.com/ipfs/go-ipfs/blob/master/fuse/ipns/ipns_unix.go#L216, and Close, , https://github.com/ipfs/go-ipfs/blob/master/fuse/ipns/ipns_unix.go#L204. Thanks @tv42 for the insight. I am out of town until next Friday and probably won't be able to put too much work into this until then.

**Comment by chriscool** [comment]
@thelinuxkid has something be done about this?

**Comment by thelinuxkid** [comment]
This issue is no longer showing up.

**Comment by chriscool** [comment]
Closing following @thelinuxkid's comment above.

**Comment by chriscool** [comment]
Really closing now :-)
