### ISSUE TITLE
panic in go tests (mfs_test.go)

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2361]
https://travis-ci.org/ipfs/go-ipfs/jobs/109692258

**Comment by whyrusleeping** [comment]
again: https://travis-ci.org/ipfs/go-ipfs/jobs/110250431

**Comment by chriscool** [comment]
@whyrusleeping the commit that is tested in the build that failed again is https://github.com/ipfs/go-ipfs/commit/edfac549e84a3fd0cb71efc73abcdda6d49ee199 which merges https://github.com/ipfs/go-ipfs/commit/ac42bb793207597b87bea499aa21762617679ea7 into https://github.com/ipfs/go-ipfs/commit/f8eefba0a3bbd2df4908910543ff141e38e50df4

@noffle's commit that fixes the problem is https://github.com/noffle/go-ipfs/commit/2c4de53c319624dbb08aac108c206940eee505ae and it is not reached by any of the above commits.

Looking at the graph:

```
* |   65cda02 Merge pull request #2367 from ipfs/docs/capitalize-dht
|\ \  
| * | ac42bb7 Capitalized DHT
| |/  
* |   9cdb69c Merge pull request #2365 from noffle/length_zero
|\ \  
| * | 2c4de53 Fixes range error by using > 0 length buffer.
| |/  
* |   944f749 Merge pull request #2369 from ipfs/docs/get-command
|\ \  
| |/  
|/|   
| * 50a44f9 Added ticks, `the`, and defaults to `get`
|/  
*   f8eefba Merge pull request #2354 from ipfs/fix/stdin-arg-parse
```

we can see the related commits have been merged without being rebased first.

So I believe @noffle's fix is correct.

**Comment by whyrusleeping** [comment]
ah, okay. sounds good to me

**Comment by chriscool** [comment]
Thanks!
