### ISSUE TITLE
unknown commands not erroring right

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#2501]
```
> ipfs version
ipfs version 0.4.0-dev

> ipfs local
Error: Unknown Command "local"


Use 'ipfs  --help' for information about this command
> ipfs local refs
Error: invalid ipfs ref path
```
wat.

looks like it's feeding `local` into `ipfs refs` somehow?

**Comment by whyrusleeping** [comment]
huh... strange. looks like i'll have to go diving into that cli parsing code again... yay :(

**Comment by rht** [comment]
If `ipfs local` were an existing command, what would it refer to?

**Comment by thomas-gardner** [comment]
Juan Benet <reply@reply.github.com> / 2016-03-25 00:51:12-0700
> ```sh
> > ipfs local
> Error: Unknown Command "local"
> 
> 
> Use 'ipfs  --help' for information about this command
> > ipfs local refs
> Error: invalid ipfs ref path
> ```
> wat.
> 
> looks like it's feeding `local` into `ipfs refs` somehow?

The above commit fixes this hole (RFC).

Presently the root options flags can be specified _anywhere_ in the input line,
which is not standard practice (e.g.:

	`git -C <path> status` vs. `git status -C <path>`

) and makes error reporting somewhat unpredictable, (e.g.: Should

	ipfs --bool foo

identify that `--bool` isn't an option or recognise that `foo` isn't a
subcommand, and which error should be reported?)

I reckon it'd be beneficial to agree on the general case of a valid cli
input string (please direct me to one if it exists!)---perhaps it should
be something like: 

	ipfs [options] [subcommand [options] [args]]

---and the priority of parsing errors. One obvious downside with this is
that the `--help` flag will be forced into an awkward position, but this
can be fixed by changing `--help` to a subcommand, akin to git's
behaviour.

**Comment by thomas-gardner** [comment]
(Re-posted since email reply is butchered by Github parsing.)

=0= The above commit fixes this hole (RFC).

=1= Presently the root options flags can be specified _anywhere_ in the input line,
which is not standard practice (e.g.:

	`git -C <path> status` vs. `git status -C <path>`

) and makes error reporting somewhat unpredictable (e.g.: Should

    ipfs --bool foo

identify that `--bool` isn't an option or recognise that `foo` isn't a
subcommand, and which error should be reported?)

I reckon it'd be beneficial to agree on the general case of a valid cli
input string (please direct me to the spec if it exists!)---perhaps it should
be something like:

    ipfs [options] [subcommand [options] [args]]

---and the priority of parsing errors. One obvious downside with this is
that the `--help` flag will be forced into an awkward position, but this
can be fixed by changing `--help` to a subcommand, akin to git's
behaviour.
