### ISSUE TITLE
build system changes

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2570]
I'm going to add a rule to the makefile for downloading gx and gx-go from the dist.ipfs.io page (via https) into bin/{gx/gx-go} and then using those two for the `gx install` part of the build process.

**Comment by jbenet** [comment]
@whyrusleeping what's needed is a description of:
- the constraints
- accounting the edge cases (the compiler crap)
- the possible solutions

look at https://github.com/ipfs/go-ipfs/issues/1841 for inspiration

**Comment by whyrusleeping** [comment]
## Constraints:
  - must work cross platform
  - must fail gracefully, and with error messages that allow the user to understand what the problem is.
  - repeated installs must be reproducible. (ideally a checksum over the directory after repeated installs of the same commit should yield the same output)

## Edge Cases:
  - the correct version of go might not be installed.
  - the version of go that gx is compiled with should match the version being used.
  - the user might be on windows without cygwin (or similar)
  - the user might be running an unsupported operating system
  - the user might not have an internet connection.

## Process:

starting with `make install`:

1. check that `go` is installed
  - if it is not installed, halt and alert user that go is required to build
    - Note: in the future, we could download the correct version of go for the user
2. check that `go` is the correct version.
  - if it is not, halt and alert the user of what version is required.
    - Note: in the future, we could download the correct version of go for the user
3. check that the user is running make from `$GOPATH/src/github.com/ipfs/go-ipfs`
  - if they are not, halt and alert the user about golang workspace conventions
4. check if bin/gx-VERSION and bin/gx-go-VERSION have been downloaded from a previous install
  - if they are not found, download each from dist.ipfs.io (see Download From Dist for details)
5. use the downloaded version of gx to install package dependencies.
  - Note: should verify that gx does not fail and leave half installed deps in a bad state.
6. change directory into cmd/ipfs and build the ipfs binary using ldflags to insert the commit sha information

### Download From Dist
programs required by the install process should be available on the distributions page.
To download a binary from dist.ipfs.io, use the following process:

1. construct the distributions url from the distname, version, GOOS and GOARCH inputs
  - GOOS can be accessed (if not set in the environment) via `go env GOOS` 
  - GOARCH can be acquired similarly
2. check if user has a tool to download content over http installed, one of wget, curl or fetch works
  - If they have no such tool installed, halt and alert the user.
  - Note: in the future, we could ship a small bit of go code and build our own http fetching tool to avoid having to rely on the user having one.
3. Download the correct archive to a temporary directory within the working directory
  - finding a cross platform 'tmpdir' isnt easy, using a local directory is.
4. depending on the archive type (zip or tar.gz) check if the user has a tool to extract it.
  - if they do not, halt and alert the user than they need such a tool installed.
  - Note: this functionality could be part of the aforementioned download program.
5. From the extracted archive, move the desired binary into the specified location

**Comment by jbenet** [comment]
thanks @whyrusleeping this helps [alot](http://3.bp.blogspot.com/_D_Z-D2tzi14/S8TTPQCPA6I/AAAAAAAACwA/ZHZH-Bi8OmI/s400/ALOT2.png).

> 5. use the downloaded version of gxto install package dependencies

- should make sure that "bad states" are rolled back in case of problems. thankfully immutable objects are fine to leave lying around, it's how we use them (rewrites?) that gets tricky.
  - consider having a "clean" command that removes any possible bad state stuff. (`make clean-deps` maybe?) 

---

- maybe also include a section on install? `make install` (after compiling, where it gets installed? (in $GOPATH/bin", as is go standard, etc).

---

> programs required by the install process should be available on the distributions page.
-  make that a "MUST be available". 
- as your note said about shipping + installing the go toolchain for the user (this would be really nice to do and would save so much time for many users. but it does get tricky to do right) we can later ship go + compiled bins from golang.org/dl too, to make it possible to _completely self-host_ the entire development toolkit on IPFS, and _**not require the internet at all to develop go-ipfs**_ 😮 🎉 🎆 

---

> check if user has a tool to download content over http installed, one of wget, curl or fetch works
> in the future, we could ship a small bit of go code and build our own http fetching tool to avoid having to rely on the user having one.

- we may want this to be `ipget`, to "just work" (having a default or optional fall back to http from the API at ipfs.io). (we can put ipget in pkg mgrs too).
- we may consider having a shell script do the {ipget, wget, curl, error} dance, so that it's super portable.

---

> 3. Download the correct archive to a temporary directory within the working directory

- sounds good to me. we can have a `.tmp` or `.trash` or even a `build/` where we put all the intermediates. and `make clean` or `make clean-deps` it out.

---

all this reminds me that we want a nice way to install stuff from our dists page. this could be combined into our goals with `gx-bin`. but even then, it will be relevant + useful to have a shell script able to do it (checks your arch, downloads, extracts, installs to location). (`dist-install-sh`? `gx-bin-sh`? (gx-bin, the shell version?)). 

i think our distributions page + ipfs + gx + tooling + pgp (or other sig checking) will be a killer "protocol" for doing project releases, in an offline-first or bad-network-friendly way. yay.

**Comment by whyrusleeping** [comment]
@jbenet thoughts on having a shell script to do the fetching from dist vs having a small go program? In go it will be much easier to handle all the different cross platform issues, and we require go to build ipfs anyways.

**Comment by jbenet** [comment]
@whyrusleeping we'll need a script like that in sh to handle cross platform issues to install other things in the project. (like install go-ipfs or gx bins in various settings, that do not involve go compilation) a go tool would land us in the same spot: having to select the right arch bin to download. i think there's no way around sh (or `make`? but `make` is less portable) as the entry point.

**Comment by whyrusleeping** [comment]
@jbenet for the go tool i was thinking of just putting the source for it in the repo. Since we already require they have go installed before this step, we can use that to build the http downloading and extracting tool

**Comment by martinvahi** [comment]
My current comment may sound extra stupid, but currently the attractive IPFS is absolutely USELESS for me, because I just could not get it to compile on Raspberry Pi 1 due to the fact that its core dependency, the Go programming language, [failed to compile](https://github.com/golang/go/issues/15965). That's my first impression of the whole project, because I wanted to compile it to try it out without using binary blobs.

You may say that my current text is out of topic, but I have [had interest](http://martin.softf1.com/g/yellow_soap_opera_blog/few-observations-about-the-freenet-project) in various distributed publishing networks for years and the main scheme of failure for all of those alternate networks seems to be that the project founders are very enthusiastic, focus on awesome features-features-features-features and the political requirements and use case side of things and the implementation is just cobbled together by hastily picking the shiniest, latest and greatest, libraries that are available, without giving much though on the project life cycle in the long run. The academia is no better, because there the project is left to ruins the moment the scientific paper gets published or grant money runs out. 

Another, very typical, reoccurring, mistake that I see is that when someone gets some funding from somewhere, including in-house projects at private sector, business world, then people do not think, what it will cost to host the software, leading to a situation, where the project depends on technologies that require expensive hosting services, sometimes even hosting services that cease to exist regardless of the availability of money. People talk about scaling up, but in a world, where machines and services should be reliable enough to be just placed somewhere and left to run till every body in the organization forgets that those systems are actually running and doing something useful, it is also important that systems can SCALE DOWN, specially from cost point of view.  Essentially, a perfect technology choice for lower level infrastructure is a technology that can run some Sci-Fi Egyptian Pyramid "Home automation", thousands of years, without anybody paying anything for maintenance. The current TCP-IP stack seems to be exactly that kind of software. If people are building something to replace it or to become as fundamental in the future as the TCP-IP is today, then the dependencies of the technology, including its running costs, must be taken to account. The "Egyptian Pyramid Home automation" issues might not even always be based on the lack of money, but lack of electrical power and lack of legacy hardware. Running some 70-ties graph database in 2016 is probably going to be "so much fun" that most people will  probably even skip trying.

My point: focusing on features has been tried before and FAILED with previous P2P publishing networks, because in practice the modularity of the implementation, bootstrapping/building of the project is very important. P2P network infrastructure is not yet-another-business-software-project, because it must last long, withstand different environments. That is to say, network infrastructure projects have far stringer constraints than network applications.

Thank You for reading my comments. I'm just wishing that the IPFS will not be yet another Freenet or I2P or other networks like that.

**Comment by tidux** [comment]
Why does this even exist?  The upstream versions of gx and gx-go work just fine with `go get` even on exotic platforms like DragonFly BSD now.  Unless you're willing to make kernel-specific tarballs for every platform, just use `go get` like everybody else.  This whole issue is dumb and wrong and should be reverted back to using `go get` now that the upstream issues have been resolved.

**Comment by jbenet** [comment]
@martinvahi thank you for your comments and perspective.

Rest assured that we take project life cycle and deployment very seriously and a very large fraction of our time is making this nice, including having a standardized release cycle, lots of review and testing, hosting compiled binaries in https://dist.ipfs.io , building tools like https://github.com/ipfs/ipfs-update/ and others to ease deployment, etc. Unfortunately, all of this is hard work and takes time. We are doing it for free. Instead of saying "the attractive IPFS is absolutely USELESS for me" consider that instead you may be able to help us make sure we have pre-compiled builds for your architecture, to help yourself and others. This is how open source works: we all work together to improve the products.

**Do note that compiling from Go **IS NOT** the easiest nor recommended way to install at all; we have precompiled binaries here: https://dist.ipfs.io **. If it does not have your architecture yet, please contribute to https://gtihub.com/ipfs/distributions to add it. FWIW, i have been bitten by Go compiler bugs before, and it's very frustrating, yes. We've considered adding a target to the Makefile that downloads a version of Go known to work with go-ipfs for those people unfamiliar with Go but that need to compile go-ipfs for some reason (eg pre-compiled binaries unavailable for them)

**Comment by jbenet** [comment]
@tidux 

- It is in general very useful to have binaries available for quick download and deployment without compilation. 
- You may not have seen https://dist.ipfs.io, which is in wide use by LOTS of people and projects. 
- There are also many contexts where compilation is simply unavailable. 
- You can use `go get` to your heart's content, nothing prevents you from forking go-ipfs and doing whatever you want.

---

A general note of communication feedback: saying things like:

> This whole issue is dumb and wrong and should be reverted back 

Is extremely frustrating to our development team. You clearly have not read everything there is to read, and fail to have full context. Qualify your statements and be friendlier, or don't speak. Your comment is behind on community discussion (given all the constraints that have already been discussed here and elsewhere). 

Being behind is totally fine, nobody can be expected to have ready everything. People will kindly point you to relevant discussion if you're generally pleasant, friendly, and qualify your statements with "I think that" or "it seems to me that". Instead, your post here denigrates our conversations, our decisions, and our people -- worst, it does so from a place of foolish ignorance. Be more careful with your statements, be more friendly, or don't post.

**Comment by jbenet** [comment]
I'm closing this issue because:

- This issue is old, and others discuss more recent state of the distributions process.
- Own issues and even different repos are more relevant places for discussion of some of the remaining points.
- It has veered off topic dramatically.
- Comments annoyed many people in unproductive ways.

**Comment by martinvahi** [comment]
@jbenet Thank You and others for the answers. 

What regards to the statement that I should help in stead of just complaining, then generally speaking, I agree, except that there's the issue of the course of action. If the Go language is so difficult to set up, then my conclusion is that I should write my code in something else. Currently I have my own projects to fix, so I can't really take on exhaustive work of fixing or rewriting other people's projects, but what regards to the choice of programming languages, then it's a topic that every software developer, who is any good at all, has probably spent a lot of time on and my own 2016_08_05 summary of my starting point, as copy-pasted from [one of my blog posts](http://martin.softf1.com/g/yellow_soap_opera_blog/my-technology-stack-in-2016_07-and-how-i-prefer-to-choose-it), is (and hopefully will not be in the future):

- Does the set of design patterns that a programming language has built-in support for cover the problem domain of a software project?

- Do the programming language implementations have the tooling for detecting the programming language specific (abstraction layer specific) flaws and what the social process and price of the tooling is, including the dependencies of the tooling?

- What performance optimizations does the programming language implementation have, including the various overheads of the possible runtimes like the C# CLR, JavaVM, Ruby/Python interpreter, etc?

As a short clarification I mention that by _"programming language built in design pattern support"_ I mean the features that make it more succinct to implement design patterns. For example, before the Object Oriented programming languages Object Orientation was used as a design pattern and sometimes is still used in plain C. By _"abstraction layer specific flaws"_ I mean flaws that can be illustrated by the [myriad](http://sva.cs.illinois.edu/menagerie/) of C language specific memory leaks, memory corruptions. Add to the mix [_internal domain specific languages_](http://bitrary.softf1.com/index.php?title=Software_Development_:_Domain-Specific_Languages) and the topicks like _model checking_ and alike become relevant. By _performance optimizations_ I mean all the classical topics like algorithmic complexity, parallelization, compiler optimizations, data flow analysis, etc.

Thank You for reading my comment.

P.S. In Estonian culture there's a difference between being friendly and being considerate. **One does not need to be friendly to be considerate.** That is to say, it is NOT RUDE, id est IT IS OK, to point out technical flaws and mistakes of other people as long as the person making the remark presents his/her findings by not claiming that he/she is the source of absolute truth. After all, I might be making a mistake myself at detecting the flaws/mistakes at other peoples' work. It seems to me that Germans and Finns tend to find the Estonian style that I just described to be a bit on the rude side, but I do not know a functional alternative to it, because  there has to be conversation about technical observations and it is not possible to beautify one's observations. It is possible to be precise and not use derogatory languages and not throw un-explained statements around, but if a rocket blows up, software fails, something mechanical fails, then there's no way to hide the technical flaws.
