### ISSUE TITLE
Config option for disabling NAT discovery

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-ipfs#2964]
In some locations (e.g. datacenters) you don't need NAT discovery. Sometimes it'll take its full couple of seconds though! If we can disable that, restarts of the daemon will be faster.

**Comment by whyrusleeping** [comment]
This should be pretty easy to do, should probably go under the `Swarm` config group and be called `NatPortMap`, default value true (if not present in the config, set it to true).

It needs to pass an option to the host construction method so that it can pass or not pass an option to the basichost.New here: https://github.com/ipfs/go-ipfs/blob/master/core/core.go#L731

Instead of passing a bool for 'NatPortMap' to this method with already way too many parameters, lets add an options struct as a parameter that we can extend later with more of these tweaks.

**Comment by kevina** [comment]
@whyrusleeping 

> if not present in the config, set it to true

where would be a good place to do this?  at the moment is is non obvious.

**Comment by whyrusleeping** [comment]
in repo/fsrepo/serialize/serialize.go, at the bottom in the  `Load` function, we just create an empty config before passing it to `ReadConfigFile`. If you set values in that, they will remain set to that value if the field is missing from the json.

Youre right, this is non-obvious, we should document it a bit while we're at it

**Comment by kevina** [comment]
Okay will do, It looks like this will be the first time we used a default value other than the go default of False, 0, or the empty string.

**Comment by whyrusleeping** [comment]
Yeah, i don't think we knew how to do this before, otherwise the `NoSync` option would have been just `Sync`

**Comment by kevina** [comment]
> Yeah, i don't think we knew how to do this before, otherwise the NoSync option would have been just Sync

So it turned out is was not sufficient to set the defaults in _just_ the `Load` function, they also needed to be set in `initConfig` in `fsrepo.go` so I created a `SetDefaults()` method on the config structure.  P.R. coming soon with some test to make sure the NoSync option really defaults to true.

**Comment by whyrusleeping** [comment]
We have this now, #3798 was merged

The config option is `Swarm.DisableNatPortMap`

**Comment by lgierth** [comment]
Awesome, thanks so much :D
