### ISSUE TITLE
sometime command didn't work

### ISSUE THREAD

**Issue by morningyyy** [ipfs/go-ipfs#3015]
Sometime I try "ipfs swarm peers", or "ipfs dht findprovs", and some other commands, the program didn't return, seems stuck somewhere

**Comment by RichardLitt** [comment]
@morningyyy Thanks for reporting. Can you explain why you didn't use the issue template? Was it a bit confusing? 

This is a very difficult bug report to fix, because we don't know what you were doing at the time. Without the additional information about what sort of system you're on and what you were doing, it is almost impossible to diagnose this and fix it.

**Comment by whyrusleeping** [comment]
issue is stale, closing. Please reopen as necessary
