### ISSUE TITLE
Update gogo protobuf dependency

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3214]
We havent updated our gogo-protobuf dep in a while. The primary reason for this is that its not as simple to do as a lot of our other deps. The repo itself is huge, and our current gogo-protobuf package is roughly 40MB. This make the `gx install` ux slow and really annoying.

We should look at repackaging a newer version with exactly what we need, or finding a better way to shrink this package to just what we need to make the process of keeping things updated easier.

cc @Kubuxu @parkan @vyzo

**Comment by vyzo** [comment]
This has escalated into a serious problem for us, because the vendored gogo-protobuf apparently generates code that can't marshall/unmarshall oneofs.

Is there any workaround with gx to make it not ewrite the gogo-protobuf dependency in our tree? We don't explicitly depend on the gx vendored package, but it gets rewritten because of the transitive dependency through libp2p.

**Comment by Kubuxu** [comment]
The huge part of gogo-protobuf are tests (there is tests that has 400k lines). We could add them to `.gxingnore`.

**Comment by Kubuxu** [comment]
Also it looks like we are using only `/proto` and `/io`.

**Comment by Kubuxu** [comment]
Removing `/test` form the gx export will leave us with about 1MiB code package.

**Comment by Kubuxu** [comment]
@vyzo you can try importing `QmVsHZSaohNEZrzNuBPi9z63iiJxWc2rvN4PZKqJXQ9oU5` which is current master of gogo/protobuf but I have no idea how it will work (there might be backward incompatible changes).

**Comment by vyzo** [comment]
@Kubuxu thanks, the explicit import of this new version works with protos compiled with unvendored gogo-protobuf!

**Comment by vyzo** [comment]
And needless to say, it solves our marshaling woes :)

**Comment by Kubuxu** [comment]
The process became just a bit more complicated, as gogo protobuf fixed bug with order of values.

Version of protobuf used by us includes the bug, current protobuf 3 version is fixed.

Meaning that if we update the protobuf library hashes of new files will change.

**Comment by Kubuxu** [comment]
https://github.com/gogo/protobuf/issues/42

**Comment by ribasushi** [comment]
Was browsing around and ran across this issue.

Since you are about start producing new hashes **anyway** ( due to the different order of protobuf "frames" ) may I suggest re-declaring [repeated varint fields](https://github.com/ipfs/go-ipfs/blob/master/unixfs/pb/unixfs.proto#L15) as packed? [According to the spec](https://developers.google.com/protocol-buffers/docs/encoding#packed) packed fields are forward and backward compatible...

This will save 1~2 bytes per unixfs link (and likely for other higher protocols too)

**Comment by Kubuxu** [comment]
We won't be changing output hashes just to update protobuf Also as far as I know, we won't be touching protobuf-unixfs format. We plan deprecating it, and maybe creating ipld-unixfs in version 0.5 but it isn't still decided, AFAIK.

@whyrusleeping might know more about this.

**Comment by ribasushi** [comment]
@Kubuxu I meant the above suggestion given that hashes **will** change as per your own writeup here: https://github.com/ipfs/go-ipfs/issues/3214#issuecomment-256940525

**Comment by Kubuxu** [comment]
As we don't want to change the hashes, we can't update for this new version of gogo-protobuf.

But we should update gogo-protobuf to a version with test vectors removed. It is 19MiB of 29MiB package, we probably could remove some other packages from it too.

**Comment by Stebalien** [comment]
I'm currently working on this.

Plan:

* [x] Publish a new version of gogo-prootbuf.
    * QmdxUuburamoF6zF9qjeQC4WYcWGbWuRmdLacMEsW8ioD8
* [x] Update gogo for go-merkledag and go-unixfs, making sure we don't change the hashes. In go-merkeldag, this involves making sure we don't re-generate the marshaler code (and making sure we actually *use* it).
* [x] File PRs against:
    * [x] go-bitswap
        * https://github.com/ipfs/go-bitswap/pull/2
    * [x] go-ipfs-routing
        * https://github.com/ipfs/go-ipfs-routing/pull/8
    * [x] go-ipns
        * https://github.com/ipfs/go-ipns/pull/16
    * [x] go-libp2p-circuit
        * https://github.com/libp2p/go-libp2p-circuit/pull/43
    * [x] go-libp2p-crypto
        * https://github.com/libp2p/go-libp2p-crypto/pull/37
    * [x] go-libp2p-floodsub
        * https://github.com/libp2p/go-floodsub/pull/94
    * [x] go-libp2p-kad-dht
        * https://github.com/libp2p/go-libp2p-kad-dht/pull/183
    * [x] go-libp2p
        * https://github.com/libp2p/go-libp2p/pull/390
    * [x] go-libp2p-record
        * https://github.com/libp2p/go-libp2p-record/pull/18
    * [x] go-libp2p-secio
        * https://github.com/libp2p/go-libp2p-secio/pull/29
    * [x] go-log
        * https://github.com/ipfs/go-log/pull/39
    * [ ] go-multicodec
* [ ] Merge PRs
* [ ] Gx-publish new versions
* [ ] Run a gx-workspace update: `gx-workspace update start go-bitswap go-ipfs-routing go-ipns go-libp2p-circuit go-libp2p-crypto go-libp2p-floodsub go-libp2p-kad-dht go-libp2p go-libp2p-record go-libp2p-secio go-log go-merkledag go-multicodec go-unixfs`.
* [ ] File a PR against go-ipfs.

**Comment by mib-kd743naq** [comment]
> this involves making sure we don't re-generate the marshaler code

@Stebalien this seems like a suboptimal plan. What you want is to update gogo, [apply the patch reverting the sorting change](https://github.com/ipfs/go-ipfs/pull/5012#issuecomment-389845771), and publish **that** in `gx-go`. Then you **do** regenerate the marshallers, taking advantage of improvements in the generated code. Perpahs even switching to the `faster` flavor ( no carriage of unrecognized field values )

The only reason I did not reopen/finish https://github.com/ipfs/go-ipfs/pull/5012 is because I ran out of time trying to figure out how `gx-go` works, and then never came back to it :(

**Comment by Stebalien** [comment]
>  Then you do regenerate the marshallers, taking advantage of improvements in the generated code. Perpahs even switching to the faster flavor ( no carriage of unrecognized field values )

We should do that as well however, we want all of this to work without gx. That's why I'm taking this approach (use upstream as much as possible).

**Comment by Stebalien** [comment]
The sharness tests pass. Running the interop tests now.

**Comment by Stebalien** [comment]
The interop tests pass (those that usually do, at least).
