### ISSUE TITLE
Hash not corresponding ?

### ISSUE THREAD

**Issue by vmadrien** [ipfs/go-ipfs#3247]
#### Description:

Hi there,

I think i miss something...

While uploading just a byte array contening "multihash" I was expecting to get this path from go IPFS 
QmYtUc4iTCbbfVSDNKvtQqrfyezPPnFvE33wFmutw9PBBk as discribed in the doc at the end ( from multihash repo).
but instead i'm getting QmZLXzjiZU39eN8QirMZ2CGXjMLiuEkQriRu7a7FeSB4fg either from java-ipfs client or directly from the console.

So did i miss something in the doc or is it a bug ?

===================Doc =================
sha2-256 0x12 - sha2-256("multihash")

12209cbc07c3f991725836a3aa2a581ca2029198aa420b9d99bc0e131d9f3e2cbe47 # sha2-256 in hex
CIQJZPAHYP4ZC4SYG2R2UKSYDSRAFEMYVJBAXHMZXQHBGHM7HYWL4RY= # sha256 in base32
QmYtUc4iTCbbfVSDNKvtQqrfyezPPnFvE33wFmutw9PBBk # sha256 in base58
EiCcvAfD+ZFyWDajqipYHKICkZiqQgudmbwOEx2fPiy+Rw== # sha256 in base64

**Comment by loadletter** [comment]
I believe IPFS does something like hash(protobuf(metadata, data)) where metadata contains the mime type and probably something else

**Comment by KrzysiekJ** [comment]
`ipfs add` packs files into [a Protobuf container which contains raw bytes and a list of links](https://github.com/ipfs/go-ipfs/blob/2b6da0c024f28abeb16947fb452787196a6b56a2/merkledag/pb/merkledag.proto#L31-L39). If you want to put raw file into IPFS, you can execute `echo -n multihash | ipfs block put`, but currently it won’t fit well into IPFS semantics. ([IPLD](http://ipld.io/) is going to use a different canonical format than Protobuf).

**Comment by whyrusleeping** [comment]
Just to note: on the very latest master there is an experimental feature that lets you use raw blocks as files and file leaves. `ipfs add --raw-leaves file` will result in the multihash matching the actual hash of the file for files under a single blocksize.

Block created this way are not backwards compatible with the rest of the network, which is why we're calling it experimental. The official release of this functionality will be the ipfs 0.5.0 release

**Comment by Kubuxu** [comment]
Also it has size limit.
