### ISSUE TITLE
Migrate from stdlib syscall to golang.org/x/sys

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#3267]
The stdlib won't be updated anymore and in case of Go 2 (if it ever is created) will be removed.

The docs recommend moving to golang.org/x/sys library.
It is something we should do in future but there is no hurry for that.

Moving to golang.org/x/sys includes moving go-ipfs and all of dependencies controlled by us.

**Comment by whyrusleeping** [comment]
lol, we have a technical debt label now. Great.

**Comment by djdv** [comment]
I'm not sure if there are any other cases like this but the standard itself suggests using /x/sys for at least this structure and it's methods on Windows, due to security concerns.
https://golang.org/src/syscall/dll_windows.go#L182
https://golang.org/src/syscall/dll_windows.go#L39

The calls in IPFS should probably be checked against the latest documentation to see if there are any notes of problems that are resolved in /x/ but not in std.

**Comment by Kubuxu** [comment]
@Stebalien I recall you working on this, have you removed all usages?

**Comment by Stebalien** [comment]
Not yet. Sorry, some of those PRs dropped off of my radar. I've submitted a PR to do take care of this in IPFS but we still need to merge/bubble those PRs (Travis is failing on go-reuseport so I'm not entirely sure what's wrong there...).

Also, FYI, we won't be able to *completely* switch. Not everything we use is exported by `golang.org/x/sys/x/unix` (although most of it is).

**Comment by Stebalien** [comment]
We've now switched over as much as we can.
