### ISSUE TITLE
Can view / request ipfs seeders/leechers ?

### ISSUE THREAD

**Issue by aronayne** [ipfs/go-ipfs#3330]
Description: Can the number of seeders / leachers within the ipfs network be monitored ? Is there a command and/or display area within webui that displays this information ?

**Comment by whyrusleeping** [comment]
@aronayne currently thats not easily possible. You can monitor your bandwidth usage with the `ipfs stats bw` command and its related options, but that doesnt get you exactly what youre looking for. 

This is a feature that we've been thinking about for a little while, but its not as easy to do in ipfs as it is for bittorrent due to the differences in the systems.

**Comment by aronayne** [comment]
thanks @whyrusleeping , I'm not sure what all of those differences are but this issue provides some clarity : https://github.com/ipfs/faq/issues/17 "IPFS is a filesystem while Bittorent is a download system. Fundamentally, this means that an IPFS aware application can issue a ipfs:\ call, just like a file:\ call, and receive a file.". https://github.com/ipfs/faq/issues/17 is linked from https://github.com/ipfs/faq/issues/21

**Comment by Stebalien** [comment]
You can view a per-peer ledger with `ipfs bitswap ledger`. Filed a feature request at https://github.com/ipfs-shipyard/ipfs-webui/issues/1037.
