### ISSUE TITLE
Swarm peers no response

### ISSUE THREAD

**Issue by ewooonk** [ipfs/go-ipfs#3718]
#### Version information:  
go-ipfs version: 0.4.5-
Repo version: 5
System version: amd64/linux
Golang version: go1.7.4

#### Description:

ipfs swarm peers is not responding. The situation occurs when my PC connected to via an router and when my PC is directly connected to the LAN network. IPFS runs fine on Windows 10 using the same network (by wifi). I also cannot access the example files via localhost in my webbrowser. 

`lsof -i -n -P | grep ipfs` shows 8 established connections. 

I'm aware of #2518 and #2540, but have not been able to solve the issue.

**Comment by whyrusleeping** [comment]
@ewooonk can you set the environment variable `IPFS_LOGGING` to `debug` before starting the daemon?

**Comment by ewooonk** [comment]
@whyrusleeping  Thank you for reaching out. It seems to be a NAT issue.
Full log: https://gist.github.com/ewooonk/8f760e51e97cd1974e6cd340de03b4fb

**Comment by Kubuxu** [comment]
It seems like a NAT issue, for some reason it repeats the NAT query over and over. I can add more logs but there isn't much we can do.

Maybe if you could use Wireshark to capture the UPNP traffic, but I won't be giving tutorial here.

**Comment by whyrusleeping** [comment]
@Kubuxu but why would that cause a peer to have no connections?

**Comment by Kubuxu** [comment]
I just checked the NAT code, it isn't the case, the logs out there are right, it should recheck the mapping every 20s.

I have no idea, I have similar problem at my house, ipfs is not able to even dial out cleanly.

**Comment by whyrusleeping** [comment]
@Kubuxu not able to dial OUT cleanly? what are the symptoms? Can you make outbound connections with netcat?

**Comment by Kubuxu** [comment]
I can use nc and any other systems but ipfs doesn't seem to function great.

I am not there right now but what happens is I get a peer or two, and then it can't dial to other peers cleanly (for example my server).

I can try diagnosing it when I get there.

**Comment by saan099** [comment]
I'm still having this problem. I have 0.4.13 version installed. How can I resolve this?

**Comment by Stebalien** [comment]
@saan099 just to make sure, are you seeing the following?

1. `ipfs swarm peers` is empty.
2. `lsof -i -n -P | grep ipfs` shows established connections to remote peers.

**Comment by talyguryn** [comment]
Have the same issue.

@Stebalien 
![](https://capella.pics/df652729-6163-4289-96c4-a0ec2423f589)

**Comment by Stebalien** [comment]
@talyguryn that's not quite the same issue. You don't *have* any connections. The issue here is that `ipfs swarm peers` shows no connections but `lsof -i -n -P | grep ipfs` shows established connections (ones in the ESTABLISHED state).

You're probably behind a firewall that blocks outbound connections on port tcp/4001. If you can install netcat, do so and try running `nc 104.131.131.82 4001`. You should see something that includes `/multistream/1.0.0`.

**Comment by Kubuxu** [comment]
You can also try running `IFPS_REUSEPORT=false ipfs daemon` it seems to help in case of my ISP. Normally I would get one or zero connections.

**Comment by Stebalien** [comment]
> You can also try running IFPS_REUSEPORT=false ipfs daemon it seems to help in case of my ISP. Normally I would get one or zero connections.

Hm. I wonder if it would be possible to detect this. https://github.com/libp2p/go-tcp-transport/issues/18

**Comment by gregory-vc** [comment]
Hi, I get this problem too.

ipfs version 0.4.13

I think this happen because ifs daemon start listening and announcing on IP in my private network (I join to it for WI-FI for access to internet from router)

Swarm listening on /ip4/192.168.80.1/tcp/4001
Swarm announcing /ip4/192.168.80.1/tcp/4001

ipfs log tail

{"dial":"failure","duration":821722,"encrypted":true,"error":"dial tcp6 [HIDE:4a:5001]:4001: connect: no route to host","event":"connDial","inPrivNet":true,"localPeer":"HIDE","remoteAddr":"/ip6/HIDE:10::4a:5001/tcp/4001","remotePeer":"HIDE","subsystem":"conn","system":"conn","time":"2017-12-18T23:11:47.164708Z"}

Nobody connect to me across 192.168.80.1, but how I have to start else ifps daemon? manual route port in router? its so boring..
