### ISSUE TITLE
ipfs mount fails when installed via snap

### ISSUE THREAD

**Issue by mattseh** [ipfs/go-ipfs#3788]
#### Version information:

root@snap:~# ipfs version --all
go-ipfs version: 0.4.6-
Repo version: 5
System version: amd64/linux
Golang version: go1.7.5

#### Description:

On a fresh Ubuntu 16.04 VM, I installed go-ipfs:

    root@snap:~# snap install ipfs
    ipfs v0.4.6 from 'elopio' installed

With the daemon running, and /ipfs and /ipns created, I get this error:

    root@snap:~# ipfs mount
    Error: fusermount: exec: "fusermount": executable file not found in $PATH

[This](https://github.com/ncw/rclone/issues/1188) issue seems to suggest that it is because the snap doesn't depend on FUSE? 

Thanks

**Comment by Kubuxu** [comment]
Yes, you need to have fuse installed for it to work.

**Comment by mattseh** [comment]
Right, fuse is installed via apt-get, but the snap doesn't seem to recognise that, so shouldn't the snap config make sure fuse is installed within the snap?

**Comment by Kubuxu** [comment]
No idea, @elopio mind helping out?

**Comment by elopio** [comment]
Yes, thanks for the report!

I haven't added support for mount on the snap yet, so it was an expected failure. In snaps you bundle all your dependencies, so installing fuse is simple, just add `stage-packages: [fuse]`. What might not be so simple is to give permission to the snap to mount. I need to give it a try, and if it's blocked by the strict confinement of the snap, talk to the security team to design a safe plug for this. I will have time for this during the weekend. Maybe it doesn't require any work at all, but I need to check.

@Kubuxu I'm not sure if you want to keep this bug here, or we should move it to https://github.com/elopio/ipfs-snap

**Comment by Kubuxu** [comment]
If you can, move it there. It will be borrowed among other issues.

**Comment by elopio** [comment]
Well, there's no way to move bugs in github, but I copied it here: https://github.com/elopio/ipfs-snap/issues/6

You can close this one @Kubuxu.
