### ISSUE TITLE
PeerID in IPNS key workflow

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-ipfs#3807]
#### Description:

- `ipfs name publish --key` should accept a PeerID in addition to the key name.
- `ipfs key list` should list the PeerID alongside the key name (`-l` arg should be default true).

**Comment by keremgocen** [comment]
Hey @lgierth, could you please give a bit more detail for the expected behavior of these 2 items?

- It seems straightforward to change the default value of `ipfs key list` like [this](https://github.com/keremgocen/go-ipfs/commit/aa12416db52cb90b3a9c3e81195d8705650bf9fa#diff-97187cb5f6f28de4954c862a0f2d1308L158) but do you want to preserve the previous behavior by providing another option?

- `ipfs name publish --key` for this one, as I understand currently it's publishing to/as `self` using the node's own `PeerID`, this would enable the node to publish to other nodes instead of self bypassing the [private key lookup here](https://github.com/ipfs/go-ipfs/blob/9dc5883ac8a633e2aca50d0c479677a2d9631202/core/commands/publish.go#L169)? This part is a bit ambiguous to me, i'd appreciate any details

**Comment by Kubuxu** [comment]
@lgierth @keremgocen I think the current behaviour of `ipfs key list` should stay. It is already established API so we shouldn't change it. We might want to create list of API changes we want to do when we are able to provider two versions of API or we decide to make a non-compatible change to the API.

@keremgocen about the `ipfs name publish --key` currently you are able to use it with key name. Like:
```bash
ipfs key gen --type=rsa --size=2048 mykey
ipfs name publish --key=mykey QmSomeHash
```

@lgierth calls for being able to use `peerID` instead of keyname (`mykey` in this case)`. PeerID can be obtained using `ipfs key list -l` but I am not sure if keystore (code responsible for storing keys) provides good method to lookup PeerID -> keyname or PeerID -> private key.

**Comment by keremgocen** [comment]
Then I shall skip the "-l arg should be default true" part.

@Kubuxu what would be a good way to lookup peerIDs? I see some potential ways of doing so (like this one)[https://github.com/ipfs/go-ipfs/blob/master/core/commands/id.go#L100] but not sure which one would be the best option with my current exposure level to the codebase.

**Comment by Kubuxu** [comment]
It should use keystore, as the `--key` parameters currently uses keyname (from keystore) as parameter. You can't use routing as you need private key. For now the simplest way would be to list all keys (in keystore), load them, check for matching peerID. If found use that key.

**Comment by Kubuxu** [comment]
So the actions here would be:
* Enable `ipfs name --key=Qm...AAA Qm...BBB` to work
* Write sharness tests for it

**Comment by lgierth** [comment]
> So the actions here would be:
> * Enable `ipfs name --key=Qm...AAA Qm...BBB` to work
> * Write sharness tests for it

SGTM :+1:

**Comment by keremgocen** [comment]
fca98aea9d5a5d23240f9fc2e9895cfead74ab21 should conclude #3882, might need to rebase though

**Comment by tomatopeel** [comment]
@lgierth Can you close this if it's all completed :D (I'm just going through "help wanted" issues trying to find things to work on)

**Comment by lgierth** [comment]
Certainly :)

Thanks @keremgocen!
