### ISSUE TITLE
Changes for Ed25519 public key IPFS identities

### ISSUE THREAD

**Issue by JustinDrake** [ipfs/go-ipfs#3896]
Below are the changes to support Ed25519 public key identity types. It was taken from https://github.com/ipfs/notes/issues/241 incorporating comments from @whyrusleeping and @Kubuxu.

- multiformats/multicodec (@JustinDrake)
  - [X] ~~table.csv: add Ed25519 codec (PR https://github.com/multiformats/multicodec/pull/46)~~
  - [X] table.csv: add identity multihash (PR https://github.com/multiformats/multicodec/pull/50)
- ~~multiformats/go-multicodec-packed (@JustinDrake)~~
  - [X] ~~multicodec.go: add Ed25519 codec (PR https://github.com/multiformats/go-multicodec-packed/pull/10)~~
- ~~multiformats/go-multihash (@JustinDrake)~~
  - [X] ~~multihash.go: add support for the identity hash (PR https://github.com/multiformats/go-multihash/pull/51)~~
- ~~libp2p/go-libp2p-crypto (@JustinDrake)~~
  - [X] ~~ed25519.go: add `UnmarshalEd25519PublicKey` helper function (PR https://github.com/libp2p/go-libp2p-crypto/pull/24)~~
- libp2p/go-libp2p-peer
  - [X] ~~peer.go: Add `ExtractEd25519PublicKey` and `ExtractPublicKey` helper functions (@JustinDrake) (PR https://github.com/libp2p/go-libp2p-peer/pull/15)~~
  - [ ] peer.go: Generalise `IDFromPublicKey` and `IDFromPrivateKey` functions beyond SHA2_256. (As pointed by @whyrusleeping this may be tricky. Most of the time context should be sufficient to determine public key type. If not we may have to resort to heuristics and defaults?) (@whyrusleeping)
- ipfs/go-ipfs-util (@whyrusleeping)
  - [ ] util.go: Remove dependence of `Hash` function which only supports SHA2_256
- libp2p/go-libp2p-kad-dht (@JustinDrake)
  - [X] ~~records.go: Have `GetPublicKey ` extract public key instead of querying caches or the DHT for new identity type (PR https://github.com/libp2p/go-libp2p-kad-dht/pull/57)~~
- ipfs/go-ipfs (@JustinDrake)
  - [X] ~~namesys/publisher.go: Have `PutRecordToRouting` refrain from publishing public key to the DHT for new identity type (PR https://github.com/ipfs/go-ipfs/pull/4020)~~
- other
  - [ ] Add argument specifying hash type to all calls to `IDFromPublicKey` and `IDFromPublicKey` (@whyrusleeping)
  - [X] Add command line option to use the new identity type when generating new identities (@JustinDrake) (PR https://github.com/ipfs/go-ipfs/pull/4076)
  - [ ] Write documentation and tests for the new identity type  (@JustinDrake)
  - [ ] Do the same thing for js-ipfs (@JustinDrake, @diasdavid)

**Comment by jbenet** [comment]
- multiformats/multicodec (@JustinDrake, @jackkleeman)
  - [ ] table.csv: add Ed25519 codec
- multiformats/go-multicodec-packed (@JustinDrake, @jackkleeman)
  - [ ] multicodec.go: add Ed25519 codec
- multiformats/go-multihash (@JustinDrake, @jackkleeman)
  - [ ] multihash.go: add support for the identity hash
- ipfs/go-ipfs-util (@whyrusleeping)
  - [ ] util.go: Remove dependence of `Hash` function which only supports SHA2_256
- libp2p/go-libp2p-peer (@whyrusleeping)
  - [ ] peer.go: Generalise `IDFromPublicKey` and `IDFromPrivateKey` functions beyond SHA2_256. (As pointed by @whyrusleeping this may be tricky. Most of the time context should be sufficient to determine public key type. If not we may have to resort to heuristics?)
- libp2p/go-libp2p-kad-dht (@JustinDrake, @jackkleeman)
  - [ ] records.go: Have `GetPublicKey ` extract public key instead of querying caches or the DHT for new identity type
- ipfs/go-ipfs (@JustinDrake, @jackkleeman)
  - [ ] namesys/publisher.go: Have `PutRecordToRouting` refrain from publishing public key to the DHT for new identity type
- other
  - [ ] Add argument specifying hash type to all calls to `IDFromPublicKey` and `IDFromPublicKey` (@whyrusleeping)
  - [ ] Add command line option to use the new identity type when generating new identities (@JustinDrake, @jackkleeman)
  - [ ] Write documentation and tests for the new identity type  (@JustinDrake, @jackkleeman)
  - [ ] Do the same thing for js-ipfs (@JustinDrake, @jackkleeman, @diasdavid)

**Comment by jbenet** [comment]
I made the allocations above ^ lmk if that makes sense or not, or edit as makes sense.

**Comment by JustinDrake** [comment]
The allocations make sense to me 👍  I've gone ahead and submitted three pull requests for the multiformats. Once this is merged in it will make sense to implement the rest.

**Comment by JustinDrake** [comment]
I've added two more PRs for review https://github.com/libp2p/go-libp2p-crypto/pull/24, https://github.com/libp2p/go-libp2p-peer/pull/13 👍

**Comment by JustinDrake** [comment]
@whyrusleeping: In regards to the task to generalise `IDFromPublicKey` assigned to you, I have written a function `IDFromEd25519PublicKey` in https://github.com/libp2p/go-libp2p-peer/pull/14 (used for tests) 👍

**Comment by lidel** [comment]
In 2022,  ed25519 keys are the default in both go-ipfs and js-ipfs :sparkles:
