### ISSUE TITLE
ipns pin add doesn't resolve sharded paths

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#3974]
#### Version information:

go-ipfs version: 0.4.9-8ec0814a8
Repo version: 5
System version: amd64/linux
Golang version: go1.8.3

#### Type:

Bug

#### Severity:

High/Medium

#### Description:

`ipns pin add` doesn't work with sharded paths. To reproduce, cat the wikipedia index and then try pinning it:

```sh
ipfs cat /ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/index.html
ipfs pin add /ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/index.html
```

The second command fails with:

```
Error: pin: no link named "wiki" under QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco
```

/cc @whyrusleeping

**Comment by whyrusleeping** [comment]
This is because `ipfs pin add` calls `corerepo.Pin`, and that method uses the non-unixfs context resolver: https://github.com/ipfs/go-ipfs/blob/master/core/corerepo/pinning.go#L35

That should probably be amended to use a unixfs resolver as in: https://github.com/ipfs/go-ipfs/blob/master/core/coreunix/cat.go#L12
