### ISSUE TITLE
install ipfs and build the code

### ISSUE THREAD

**Issue by TimothyWang123** [ipfs/go-ipfs#4119]
![image](https://user-images.githubusercontent.com/13633039/28956504-eec5bfa0-791f-11e7-8ebb-186161e0ae23.png)

thanks for ur help. but I ran all the cmds as shown above, I just got three folders
![image](https://user-images.githubusercontent.com/13633039/28956521-07c7540a-7920-11e7-82ac-5e55a5de7071.png)

 I dont know how to get the complete one like 
![image](https://user-images.githubusercontent.com/13633039/28956512-fcbd152c-791f-11e7-99e0-191984e91b6c.png)

thanks

**Comment by djdv** [comment]
Take a look at this
https://github.com/ipfs/go-ipfs/blob/master/docs/windows.md
When you're done ipfs.exe should be in %GOPATH%/bin/

I personally use msys2 to build on Windows and use a batch file to update my builds. I keep the repo isolated on my system for testing, it's not required.
```
SET ORIGGOPATH=%GOPATH%
SET ORIGPATH=%PATH%
SET GOPATH=C:\tmp

IF NOT EXIST %GOPATH%\bin\gx.exe (
	go get -u "github.com/whyrusleeping/gx"
)

IF NOT EXIST %GOPATH%\bin\gx-go.exe (
	go get -u "github.com/whyrusleeping/gx-go"
)

pushd %GOPATH%\src\github.com\ipfs\go-ipfs
::git checkout master
git pull
make install

ipfs shutdown
ping -n 3 localhost
popd

move /Y %GOPATH%\bin\ipfs.exe %ORIGGOPATH%\bin\ipfs.exe

SET GOPATH=%ORIGGOPATH%
SET PATH=%ORIGPATH%
ipfs daemon 2>&1 | tee ipfs.log
```

**Comment by Kubuxu** [comment]
@TimothyWang123 the code that builds the distribution package lives in separate repo.

I am slowly working on bringing it to `go-ipfs` itself including building full, portable source package.

**Comment by TimothyWang123** [comment]
@djdv thanks , bu it seems some cmds are not available on my computer,like ipfs shutdown.
![image](https://user-images.githubusercontent.com/13633039/29645558-e38b029e-88b0-11e7-9739-c15ec9700c82.png)

**Comment by Kubuxu** [comment]
What is your `ipfs --version`?

**Comment by djdv** [comment]
@TimothyWang123  `shutdown` was added somewhat recently https://github.com/ipfs/go-ipfs/pull/3884 you likely won't have it on the first build but subsequent builds should be fine, it's not required either way, it's just to make sure "ipfs.exe" is not in use so that it may be overwritten with the `move` command, the `ping` following `shutdown` is just to make sure the file handle is closed in time (I had issues with this early on, maybe it's fine now).
If you make sure your exe is not in use before building, you could remove both of those lines.

You also don't have to pipe the output to `tee`, I just do that for catching crashes and to fix cli colours (https://github.com/ipfs/go-ipfs/issues/2124).

**Comment by TimothyWang123** [comment]
@Kubuxu 0.4.9 centos7

**Comment by TimothyWang123** [comment]
@djdv thanks,I see

**Comment by whyrusleeping** [comment]
I think this is resolved, feel free to reopen or open a new issue as needed.
