### ISSUE TITLE
Can't get small data (<1KB) stored on DHT

### ISSUE THREAD

**Issue by HexRabbit** [ipfs/go-ipfs#4158]
#### Version information:
go-ipfs version: 0.4.10-
Repo version: 5
System version: amd64/linux
Golang version: go1.8.3

#### Description:
>The size of objects and use patterns of IPFS are similar
to Coral [5] and Mainline [16], so the IPFS DHT makes a
distinction for values stored based on their size. Small values
(equal to or less than 1KB) are stored directly on the DHT.

According to IPFS whitepaper, after add some small data (<1KB) on ipfs,
one should still able to get the data even if the provider shutdown deamon,
because it has been stored on DHT.
I've tried a few time but can't get anything, also tried "ipfs dht provide <hash>" and still the same...

Did I misunderstand the way it works?

**Comment by Stebalien** [comment]
I believe this is a case where the implementation disagrees with the whitepaper. This is probably due to a combination of factors:

1. Simplicity. We can add features like this later.
2. Minds changed when go-ipfs was implemented. There are a lot of small differences between the white-paper and reality.
3.  In general, storing data on the DHT is rather expensive and inefficient so we'd rather discourage it as much as possible.

Note: There are still crafty ways to store arbitrary data on the DHT, they're just not technically supported.

Preemptive "but where's the spec!" answer: we need to get better at writing this stuff down. This is a known (high priority) issue (that comes up again and again) but knowing that we need write updated specs and having the time to do so are two very different things. Now, if you have some free time and feel like diving into some fun distributed systems code and writing a bit of documentation from the perspective of someone unfamiliar with IPFS, I'd be more than happy to answer any questions that might come up :grin: :heart:. For some reason, people tend not to take me up on that offer but it's always worth a try...

**Comment by Stebalien** [comment]
I'm going to close this issue to keep the number of issues on this repo manageable(ish). If you have any further questions, please reach out to us on IRC (#ipfs on freenode.net) or in the http://discuss.ipfs.io/.
