### ISSUE TITLE
Unixfs is defaulting to use Raw Leaves

### ISSUE THREAD

**Issue by diasdavid** [ipfs/go-ipfs#4188]
Is this on purpose? This means that files being added with latest go-ipfs will show a different hash than if they were added with a previous go-ipfs version without required the user to pass any option.

This was detected by @alanshaw

**Comment by alanshaw** [comment]
...to add context:

`ipfs add file.txt --cid-version=1` will automatically set `--raw-leaves` as per:

https://github.com/ipfs/go-ipfs/blob/e8477b50c907c1544f8a7e15334d6fb595baac19/core/commands/add.go#L95

I was looking into adding this missing option to `js-ipfs` and found that I'd first need to add `raw-leaves` (also missing) first because of this.

**Comment by Kubuxu** [comment]
`--cid-version=1` changes the default value of raw leaves. You still can override it with `--raw-leaves=false`.

**Comment by alanshaw** [comment]
I think the concern is that this didn't used to happen in a previous go version?

**Comment by Kubuxu** [comment]
It did since introduction of `--cid-version` to go-ipfs.

**Comment by Kubuxu** [comment]
See: https://github.com/ipfs/go-ipfs/commit/518adec022db6ec1273dcf9c3d2cf082eabf2206#diff-bd0ca9f1e2d5c7ba128af01ec4c1131cR183

**Comment by alanshaw** [comment]
Not a problem then :) safe to close @diasdavid ?
