### ISSUE TITLE
repo fsck doesn't remove badger lockfile

### ISSUE THREAD

**Issue by djdv** [ipfs/go-ipfs#4301]
#### Version information:
go-ipfs version: 0.4.12-dev-e7acb96c6
Repo version: 6
System version: amd64/windows
Golang version: go1.9.1

#### Type:
Bug

#### Severity:
Medium
#### Description:
Running `ipfs repo fsck` reports that lockfiles were successfully removed but they're not.

![ipfs repo fsck not clearing](https://user-images.githubusercontent.com/13862850/31526635-178b6500-af96-11e7-9666-f48348c21d29.png)

**Comment by kevina** [comment]
From ipfs-dev channel on irc:
> \<kevina\> stebalien: if your around, why was I assigned to https://github.com/ipfs/go-ipfs/issues/4301?
> \<stebalien\> kevina: I probably fat fingered something. I intended to assign that to Magik6k.

**Comment by Kubuxu** [comment]
@schomatis the `LOCK` file in a `datastore` is to prevent multiple instances running over the same repo. The `ipfs repo fsck` removes the `LOCK` file from it because we had the same issue badger has currently. We didn't have proper locking on Windows and were using just a file to do it. Currently we lock properly on Windows so `ipfs repo fsck` isn't really needed anymore.
