### ISSUE TITLE
Add Opentracing support to ipfs event logging

### ISSUE THREAD

**Issue by frrist** [ipfs/go-ipfs#4487]
#### Description:
Quick summary of terminology (over simplifying a bit here)
[Opentracing](http://opentracing.io/documentation/pages/spec) is an API for distributed event tracing.
[Tracer](https://github.com/opentracing/opentracing-go/blob/master/tracer.go#L7) is an interface to create `Span`s and associate them with a context.
[Spans](https://github.com/opentracing/opentracing-go/blob/master/span.go#L27)  can be thought of as events with durations (and some metadata).  

Basically, a trace is a set of spans, in some hierarchical order. [Here](https://ipfs.io/ipfs/QmUMJCmHRQ2svFjWjXfiC5y5XCHG2qj4TvA4Jbz7XKFvaE/Selection_008.png) is an example of a trace for the `ipfs add -r` command, created using [Jaeger](http://jaeger.readthedocs.io/en/latest/) 

We are exploring ways of [integrating opentracing with go-log events](https://github.com/ipfs/go-log/pull/8), and lack a way of enabling/disabling as well as configuring where traces are sent. 

Adding a subcommand `tracer` to `ipfs log` seems like a good way to solve this.

To enable tracing, if `adder` is omitted use tracers default. (In the case of [Jaeger](http://jaeger.readthedocs.io/en/latest/getting_started/#all-in-one-docker-image) `localhost:6831`)
```
ipfs log tracer enable [adder]
```
To view the status (if there is an active tracer)
```
ipfs log tracer status
```
To disable tracing
```
ipfs log tracer disable
```

EDIT: Thinking about this more, it might make more sense to do a majority of the tracer configuration via the existing ipfs config file, but still leave the option to enable and disable it from the command line.
What do ya'll think? @Stebalien @lgierth @whyrusleeping @hsanjuan @Kubuxu

**Comment by b5** [comment]
So much support for this @ForrestWeston, any progress in the way of support for Opentracing would be incredible! On my wishlist is anything in the way of Opentracing support for the libp2p stack

**Comment by dignifiedquire** [comment]
Adding tracing would be a great addition. I don't have any insight into if opentracing is the way to go or if there are other options we should consider using for implementing this. Did you research/compare alternatives?

**Comment by ForrestWeston** [comment]
From what I can tell, The Opentracing API is the only open-standard for instrumenting applications with distributed tracing. However, there are a few different distributed tracing systems to choose from, all of which are based on [The Dapper Paper](https://research.google.com/pubs/pub36356.html).

An important distinction to make is that OpenTracing is **vendor neutral**, meaning it doesn't matter which of the below systems we use for collecting traces from our Applications. If we decide we want to use a different system later on, it will be easy to replace so long as it supports the OpenTracing API.

### Open Source:
#### [Jaeger](https://uber.github.io/jaeger/)
* [Go Client](https://github.com/jaegertracing/jaeger-client-go)
#### [Zipkin](https://zipkin.io/)
* [Go Client](https://github.com/openzipkin/zipkin-go-opentracing)
#### [AppDash](https://github.com/sourcegraph/appdash)
* Only supports Go

### Honorable Mentions:
#### [Lightstep](http://lightstep.com/)
* [Go Client](https://github.com/lightstep/lightstep-tracer-go)
#### [New Relic](https://newrelic.com/)
* [Go Client](https://github.com/newrelic/go-agent)
#### [StackDriver Trace](https://cloud.google.com/trace/) 
* For Google Cloud Apps
#### [DataDog](https://docs.datadoghq.com/tracing/go/)
* [Go Client](https://github.com/DataDog/dd-trace-go)
#### xTrace
* Turned into **PivotTrace**, which has been deprecated 

Lightstep and Uber (Jaeger) are the primary contributors to Opentracing, because of that I think it makes sense to go with a system from them, since Lightstep isn't free that leaves us with Jaeger.

**Comment by Stebalien** [comment]
We're going to go with opencensus.
