### ISSUE TITLE
commands: expected type <-chan interface{}, got <nil>

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#4495]
When sending a SIGINT to `ipfs repo verify`, I occasionally get:

```
128 blocks processed.d.
Error: expected type <-chan interface {}, got <nil>
```

This was originally reported at https://github.com/ipfs/go-ipfs/issues/4360#issuecomment-348350673 (and believed fixed). However, the issue itself was a separate problem so I'm opening a new issue.

**Comment by Stebalien** [comment]
@kevina

**Comment by keks** [comment]
I'm having trouble reproducing this. What happens here is that sometimes it doesn't print an error. The `-D` flag isn't helpful either.

**Comment by Stebalien** [comment]
I can reproduce it about 50% of the time. You need to let the command run for a second before hitting ^C. Try adding a bunch of large files so `ipfs repo verify` takes longer.

**Comment by schomatis** [comment]
@Stebalien Is someone currently working on this? (I'm checking because I saw this issue in the [release blockers list](https://hackmd.io/HJv3HOBoTeKfzFmoo1WWWQ#Help-Wanted).)

There seems to be a [race condition][RACE_PAIR] between the goroutine of the `ipfs repo verify` and the goroutine that emits/marshals the output. The marshaler is receiving a [`nil` output][NIL_OUTPUT] because the [context was canceled][CONTEXT_CANCEL] (SIGINT/CTRL+C) while the emitter is still [reading values from the output channel][OUTPUT_CHAN_READ] to marshal.

[CMD_CANCEL]: https://github.com/ipfs/go-ipfs/blob/bea666f3cd2a6ea460b3329ff2516797d5885e27/core/commands/repo.go#L313-L314

[DEFERRED_CLOSE]: https://github.com/ipfs/go-ipfs/blob/bea666f3cd2a6ea460b3329ff2516797d5885e27/core/commands/repo.go#L285

[OUTPUT_CHAN_READ]: https://github.com/ipfs/go-ipfs-cmds/blob/13acd1ab00ea043c3b202e1eb0fca2dec1a34a34/cli/responseemitter.go#L158-L164

[CONTEXT_CANCEL]: https://github.com/ipfs/go-ipfs-cmds/blob/13acd1ab00ea043c3b202e1eb0fca2dec1a34a34/chan.go#L104-L107

[NIL_OUTPUT]: https://github.com/ipfs/go-ipfs/blob/bea666f3cd2a6ea460b3329ff2516797d5885e27/commands/legacy/response.go#L35-L37

[RACE_PAIR]: https://github.com/ipfs/go-ipfs/blob/bea666f3cd2a6ea460b3329ff2516797d5885e27/commands/legacy/command.go#L37-L38

**Comment by Stebalien** [comment]
@schomatis thanks for diagnosing this! Nobody's currently working on it, feel free.

I took one look, gave up, and migrated this command to the new commands lib (https://github.com/ipfs/go-ipfs/pull/4764). However, having a proper fix would be *really* nice.

**Comment by schomatis** [comment]
@Stebalien This seems more a problem of the legacy commands library than the `ipfs repo verify` command (e.g., `ipfs filestore dups` and `ipfs filestore verify` have the same error). The `Output` function of `responseWrapper` discards the error received from [`Next`](https://github.com/ipfs/go-ipfs/blob/bea666f3cd2a6ea460b3329ff2516797d5885e27/commands/legacy/response.go#L35-L37) so when the output returned is `nil` there is no indication if this is expected (command canceled, stop printing output) or if there was an error. The code implementing the command can explicitly check if it has been canceled (see PoC #4773), but I'm not sure if this should be the responsibility of the command.

In case the fix should happen inside the commands library (and I'm inclined to think so) I'm going to need more guidance as to where it should be placed.

**Comment by Stebalien** [comment]
I see what the problem is now.

So, when we switched to the new cmds library, we appear to have partially migrated marshalers. We *used* to call the marshaler *once* for the entire stream. We now call it for each item. However, the *interface* still acts like we're calling it once. This makes it really error prone, hacky, and shitty. I'm going to try some sed magic to fix this.

**Comment by Stebalien** [comment]
So, this really just sucks all around. I think the best way to fix this is to:

1. Manually migrate commands with multiple outputs to the new system.
2. Sed-migrate everything else to an intermediate.

I really have no idea how I missed this in review.

**Comment by Stebalien** [comment]
All done.
