### ISSUE TITLE
potential memory leak in ipfs add

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#4505]
Several users have reported ipfs using way too much memory when adding large datasets.

This could be that the mfs structure is not ever flushing directories from memory, we probably need to periodically call `Flush` on parts of the structure during longer adds.

**Comment by Stebalien** [comment]
> Several users have reported ipfs using way too much memory when adding large datasets.

That may be providing. We queue up a bunch of go routines to provide blocks and have no backpressure mechanism. Ask them to try again with `--local` and see if that makes a difference.

**Comment by Stebalien** [comment]
Actually, it looks like you're right.

![add-profile](https://user-images.githubusercontent.com/310393/34173041-06221c10-e4ec-11e7-8975-619fc3a04356.png)

**Comment by Stebalien** [comment]
Several issues:

1. When adding, we need to stream CIDs back to the user instead of queuing them all up.
2. When providing, we need to *not* queue CIDs in memory.
3. Our CIDs are *large*. The 48 bytes for the CID structure and 48 bytes for the `Cid` structure, 48 bytes for the CID multihash (according to the profiler). We should really jump on https://github.com/ipfs/go-cid/issues/3.
4. We allocate 256KiB buffers when importing but don't make any attempts to shrink them down if we happen to read a smaller file. This means we end up batching `ParallelBatchCommits(2*NumCPU) * MatchBatchBlocks(128)` 256KiB blocks in our DAG batch writer. That's *not* good.

**Comment by whyrusleeping** [comment]
@dignifiedquire hrm... thats troublesome, but the users reporting issues here said that their machines had at least 8GB of ram. That wouldnt account for that would it?

**Comment by Stebalien** [comment]
We should try adding an LRU (or ARC) cache for CIDs.

**Comment by Stebalien** [comment]
@whyrusleeping 

1. How many CPUs do they have.
2. You have to take GC into account. GC will lag a bit even if we're allocating a ton of buffers.

**Comment by Stebalien** [comment]
(old)
