### ISSUE TITLE
issue installing go-ipfs

### ISSUE THREAD

**Issue by RedaBenh** [ipfs/go-ipfs#4534]
Cannot install it on mac OS X. try with both `go-ipfs_v0.4.13_darwin-386.tar.gz` and    go-`ipfs_v0.4.13_darwin-amd64.tar.gz `

```
$ sudo ./go-ipfs/install.sh
We cannot install ipfs in one of the directories /usr/local/bin /usr/bin
```

**Comment by leerspace** [comment]
What version of macOS are you on?

The installer works just fine for me on macOS High Sierra 10.13.1. There shouldn't be anything stopping you from writing to `/usr/local/bin`, but `/usr/bin` is going to be locked down by default on later versions of macOS (even for sudo).

**Comment by qezz** [comment]
@RedaBenh 

You can also check for missing `ipfs` in `./go-ipfs/` directory

e.g. with this one-liner: `if [[ -f ./go-ipfs/ipfs ]]; then; echo "ipfs binary is present"; else; echo "ipfs binary not found"; fi`

**Comment by VictorBjelkholm** [comment]
You need to run `install.sh` from within the `go-ipfs` directory.

So, download the tar, extract it and then `cd go-ipfs && ./install.sh` and it should work fine.

In the next version, it'll be possible to run `install.sh` from any directory, since https://github.com/ipfs/go-ipfs/pull/4547 was merged
