### ISSUE TITLE
Block put with sha2-512

### ISSUE THREAD

**Issue by richardschneider** [ipfs/go-ipfs#4577]
#### Description:
A block put with sha2-512 returns an invalid CID.  The returned CID starts with`8`.  This is not a valid multicodec code!

```
POST http://localhost:5001/api/v0/block/put?mhtype=sha2-512
RSP {"Key":"8Vva8UXUZQVLNqYHCTqwxQg5m6ZrYXGaV731xAoefMjh6GmYbRVuFNadUKuZ8YFCDtx8qirW3BodmzcwG4z1Vg3Wmf","Size":5}
```

**Comment by Stebalien** [comment]
It looks like ipfs is trying to return a CIDv0 with a SHA2-512 hash (invalid). In this case, IPFS can't actually guess the correct IPLD block format (it can with CIDv0 because there's only one) so this command *should* return an error. (well, really, this shouldn't care about CIDs at all but... https://github.com/ipfs/go-ipfs/issues/4189)

The correct command would have a `format=$CODEC` parameter.

**Comment by richardschneider** [comment]
So what are the valid `$CODEC` values.  I tried `dag-pb` and `dag-cbor` with no luck.

**Comment by Stebalien** [comment]
`pb`, `cbor`, `raw`.

**Comment by magik6k** [comment]
Fixed by https://github.com/ipfs/go-ipfs/pull/4563
