### ISSUE TITLE
ipfs object diff returns a change when diffing empty directory with itself

### ISSUE THREAD

**Issue by rememberberry** [ipfs/go-ipfs#4591]
#### Version information:
go-ipfs version: 0.4.13-
Repo version: 6
System version: amd64/darwin
Golang version: go1.9.2

#### Type: 
Bug

#### Severity:
Low

#### Description:
To recreate:
`ipfs files mkdir /testdir`
`HASH=$(ipfs files stat --hash /testdir)`
`ipfs object diff $HASH $HASH`
output is:

> ~ QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn ""

I would expect it to be empty

**Comment by Stebalien** [comment]
I can confirm. This is definitely a bug...

**Comment by schomatis** [comment]
@Stebalien I'd like to work on this if no one is.

The [`Diff`](https://github.com/ipfs/go-ipfs/blob/master/merkledag/utils/diff.go#L97) algorithm  seems to be designed to work with directories as inputs, comparing its links, not with single files (or an empty directory, that for this case behaves the same). The [base case](https://github.com/ipfs/go-ipfs/blob/master/merkledag/utils/diff.go#L98) of this recursive function is assuming (my interpretation) that if it reached that node in the tree it's because they (version A and B) had different hashes in the parent node (directory) that led it to them, and hence they are different (so it returns it as a [modification](https://github.com/ipfs/go-ipfs/blob/master/merkledag/utils/diff.go#L101) in the tree). It is not contemplating the case where the algorithm starts at the leaf (single file, empty directory). I think that base case should be modified to take that into account.

**Comment by schomatis** [comment]
@rememberberry Could you check again with #4767 please?
