### ISSUE TITLE
Recursive pinning can lose existing direct pin

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-ipfs#4650]
#### Description:

This bit looks like it'll lose the existing direct pin if the attempt to add the recursive pin fails. The direct pin will have been removed, and the expected recursive pin won't have succeeded: https://github.com/ipfs/go-ipfs/blob/864c960aa641bff2820b59b5eeb9d93be5d0998d/pin/pin.go#L213-L228

`directPin.Remove()` should probably happen after `recursePin.Add()`

**Comment by lgierth** [comment]
And we probably want to guard against blocks being removed between `FetchGraph()` and `recursePin.Add()`, however unlikely it is to occur.

**Comment by schomatis** [comment]
@lgierth Is someone working on this? I'd like to make a try, it will help me to learn more about the pinning system.

**Comment by lgierth** [comment]
@schomatis thanks, please go for it :)

**Comment by Kubuxu** [comment]
@lgierth pinner is locked during this time and any access to pins does require locking (or at least it should, not true about: https://github.com/ipfs/go-ipfs/blob/864c960aa641bff2820b59b5eeb9d93be5d0998d/pin/pin.go#L491-L498). So there is no inconsistency.

The fact that those two functions do not require locking will just lead to concurrent map modification panic

**Comment by schomatis** [comment]
1. 

> directPin.Remove() should probably happen after recursePin.Add()

I agree. Maybe a function could be added to add recursive pins (e.g., `addRecursePin`) that would abstract the requirement that a pin can only be of only one type (e.g., direct or recursive) performing the atomic check `p.directPin.Has(c)` inside the function.

2. 

> And we probably want to guard against blocks being removed between FetchGraph() and recursePin.Add(), however unlikely it is to occur.

As @Kubuxu commented the `Pin` function is protected by a [lock](https://github.com/ipfs/go-ipfs/blob/v0.4.13/pin/pin.go#L173) and, for example, a direct attempt to remove the block being pinned with `ipfs block rm` will [check for pins](https://github.com/ipfs/go-ipfs/blob/v0.4.13/blocks/blockstore/util/remove.go#L47) and block when it tries to call [`CheckIfPinned`](https://github.com/ipfs/go-ipfs/blob/v0.4.13/pin/pin.go#L300). However, if the garbage collection is run while adding the pin (`ipfs repo gc`), as [`RecursiveKeys`](https://github.com/ipfs/go-ipfs/blob/v0.4.13/pin/pin.go#L453) is not protected, there is a chance that the block is removed before it is pinned (i.e., added to `recursePin`).

So both `DirectKeys` and `RecursiveKeys` (and probably any other exported function that manipulates the pin sets) should be locked to prevent similar issues (although they may be quite rare). Locking those getter pin functions may have some performance impact over other parts of the code that will stall while the `pinner` is working (from what I'm seeing adding a recursive pin is an expensive operation).

------------------------------------------------------

As a side note I could verify this race condition adding a sleep before `recursePin.Add()` and manipulating some time conditions through a debugger: adding a pin (`ipfs pin add`) and triggering a garbage collection (`ipfs repo gc`) in the middle would cause the block to be removed before the `Pin` call is completed. Although the garbage collection [does block](https://github.com/ipfs/go-ipfs/blob/v0.4.13/pin/gc/gc.go#L165) while trying to access [`InternalPins`](https://github.com/ipfs/go-ipfs/blob/v0.4.13/pin/pin.go#L527) (that is protected) this happens after it already accessed [`RecursiveKeys`](https://github.com/ipfs/go-ipfs/blob/v0.4.13/pin/gc/gc.go#L141) (this order of calls it's just a coincidence I believe) so the newly added pin won't be taken into consideration during the sweep stage of GC.

I couldn't always trigger this scenario as in some cases the pin got listed as an internal pin (inside the `internalPin` set) for reasons I don't understand (I'm new to the code), so the pin would still the same get added to [`gcs`](https://github.com/ipfs/go-ipfs/blob/v0.4.13/pin/gc/gc.go#L53) and the block [wouldn't get removed](https://github.com/ipfs/go-ipfs/blob/v0.4.13/pin/gc/gc.go#L80), but I can confirm that this deletion wasn't avoided because the pin was added to `recursePin`.

**Comment by schomatis** [comment]
Looking more carefully into the issue I have to correct myself, `ipfs pin add` [locks the GC](https://github.com/ipfs/go-ipfs/blob/v0.4.13/core/commands/pin.go#L66) so the above mentioned race condition should not happen, I still think `DirectKeys` and `RecursiveKeys` should be locked, as there may be other code paths that could lead to a similar situation.
