### ISSUE TITLE
install from source 

### ISSUE THREAD

**Issue by fjqdxq** [ipfs/go-ipfs#4851]
when I compile the source code, I have the following problem:
ERROR: Error: strconv.Atoi: parsing "it:": invalid syntax
ERROR: req-check hook failed: exit status 1 
mk/gx.mk:4: recipe for target 'gx-deps' failed

how I can fix it, thanks!

**Comment by fjqdxq** [comment]
@Stebalien 
 go1.9.4 and it's environment as : 
GOROOT=/usr/local/go
 GOPATH=$HOME/go

**Comment by Stebalien** [comment]
Did you compile gx-go with go-git? Are you building the latest master of go-ipfs?

**Comment by fjqdxq** [comment]
@Stebalien  
no , I follow these steps:
$ go get -u -d github.com/ipfs/go-ipfs

$ cd $GOPATH/src/github.com/ipfs/go-ipfs
$ make install

**Comment by fjqdxq** [comment]
@Stebalien 
and I sure build the latest go-ipfs

**Comment by fjqdxq** [comment]
@Stebalien 
all things good, but I can not fetch the file

 [get ] [fetch]   go-log                        QmRb5jh8z2E8hMGN2tkvs1yHynUanqnZ3UeKwgN1i9P1F8
[0 / 194] 134sERROR: from shell.Get(): Post https://ipfs.io/api/v0/get?arg=QmRb5jh8z2E8hMGN2tkvs1yHynUanqnZ3UeKwgN1i9P1F8&encoding=json&stream-channels=true: dial tcp 174.37.175.229:443: getsockopt: connection timed out
......
what I should do? thanks!

**Comment by djdv** [comment]
@fjqdxq 
Do you happen to be located in China?
I am asking because I have noticed a rise in Chinese locals having difficulties connecting to ipfs.io

In the meantime you can try running a [prebuilt version of go-ipfs](https://dist.ipfs.io/#go-ipfs), starting the daemon, and running `make build`. `gx` will automatically detect that IPFS is running and use it to fetch dependencies directly from other peers.
After it is built you can shutdown the daemon and replace it with the one you just built. The binary should be in the `cmd/ipfs` directory.

**Comment by crazyyi** [comment]
@djdv Confirmed I can't connect to ipfs.io in China. I will try your workaround and see how it goes.

**Comment by kelvinji2009** [comment]
@djdv Tried the steps you mentioned above, but still not working. It indeed try get dependencies from other peer. But it seems that all of other peers still timeout.

**Comment by kelvinji2009** [comment]
@Stebalien Thanks. I just tried again. Everything works fine after keep `ipfs daemon` running. It failed last try because of my networking issue.

**Comment by peer2peer** [comment]
https://github.com/ipfs/go-ipfs/releases/download/v0.4.17/go-ipfs-source.tar.gz
