### ISSUE TITLE
webui doesn't work in Private Networks

### ISSUE THREAD

**Issue by pecastro** [ipfs/go-ipfs#4907]
#### Version information:
go-ipfs version: 0.4.15-dev-ecb4095
Repo version: 6
System version: amd64/linux
Golang version: go1.9.4

#### Description:
After setting up ipfs to use private networks as described in https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#private-networks loading the webui hangs and eventually returns a message 

`
ipfs resolve -r /ipfs/QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa/: failed to get block for QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa: context deadline exceeded
`

**Comment by Mr0grog** [comment]
Howdy, @pecastro. This is actually the same as #4174 — your problem is that the WebUI is actually not part of `go-ipfs`! Instead, it’s actually content downloaded over the IPFS network. If you aren’t connected to a network that has the WebUI living on one of the nodes, you won’t be able to load it.

You may want to try starting your node connected to the public network, load the WebUI, then shut your node down and make it private. You should be to use the WebUI on your private network from then on (and other nodes on your network will be able to get the WebUI from you).

**Comment by mandarvaze** [comment]
@Mr0grog How can I "start a node connected to public network" ? 
Do you mean I get webui to work first, and then `ipfs bootstrap rm --all` ?

**Comment by Kubuxu** [comment]
Yes, open webui before transitioning to a private network.

**Comment by LetItGlow** [comment]
Sorry, for pushing this OLD issue back up
I usually solve this problem by
```
rem version 4.18
ipfs get /ipfs/QmSDgpiHco5yXdyVTfhKxr3aiJ82ynz8V14QcGKicM3rVh -o L:\IPFS_Storage\webui-%version%
attrib /S L:\IPFS_Storage\webui-%version% +r 
ipfs add -r L:\IPFS_Storage\webui-%version%
```
on a live node and re-add the directory on my private nodes, taking care they are read-only.
I run 4 nodes on my local comp, a private node, which does not have the webui locally, will get the webui from the node, which has the files - which is my main bootstrap node.
When clustered, just DL+pin it across all nodes.

For version 4.19 so far, use
`ipfs get QmXc9raDM1M5G5fpBnVyQ71vR4gbnskwnB9iMEzBuLgvoZ -o webui-0.4.19`
instead, note: this is subject to change, as development progresses.

However, you can use the 4.18 webui on newer versions of IPFS, just use
`http://127.0.0.1:5001/ipfs/QmSDgpiHco5yXdyVTfhKxr3aiJ82ynz8V14QcGKicM3rVh`
(you MUST issue the ipfs-path) to get started, so better bookmark it afterwards.
