### ISSUE TITLE
go-ipfs depends on distinct 3 forks of golang.org/x/sys maintained by different authors

### ISSUE THREAD

**Issue by hvenev** [ipfs/go-ipfs#4916]
- gx/ipfs/QmPXvegq26x982cQjSfbTvSzZXn7GiaMwhhVPHkeTEhrPT/sys
- gx/ipfs/QmTq8ag5pgTCqtGDtmpm1F5TPE2i1H8bcU6295WFKTc5ie/sys
- gx/ipfs/QmTsTrxKNXu8sZLv7FP6p884CHoDbT9upKA1j4FkCy5V7T/sys

Also, on project named `gx/ipfs/QmT6n4mspWYEya864BhCUJEgyxiRfmiSY9ruQwTUNpRKaM/protobuf`, which is a fork of `github.com/golang/protobuf`, and on `gx/ipfs/QmXSs8cccbT4zDR95c1iRpYKDqVMzqeF1J6iZcavgE6eNw/protobuf`, which is a fork of `github.com/gxed/protobuf`, which is a fork of `github.com/golang/protobuf`.

Also, on `github.com/ipfs/go-log`, its fork `gx/ipfs/QmRb5jh8z2E8hMGN2tkvs1yHynUanqnZ3UeKwgN1i9P1F8/go-log` and its fork `gx/ipfs/QmSpJByNKFX1sCsHBEp3R73FL4NF6FnQTEGyNAXHm2GS52/go-log`.

Also, two forks of `github.com/ipfs/go-detect-race`.

Also, the following dependencies are duplicated by `gx` forks:
- github.com/agl/ed25519
- github.com/blang/semver
- github.com/btcsuite/btcd/btcec
- github.com/codegangsta/cli
- github.com/gogo/protobuf
- github.com/ipfs/go-ipfs-cmdkit
- github.com/libp2p/go-libp2p-crypto
- github.com/libp2p/go-libp2p-peer
- github.com/mattn/go-colorable
- github.com/minio/blake2b-simd
- github.com/minio/sha256-simd
- github.com/mr-tron/base58
- github.com/multiformats/go-multiaddr
- github.com/multiformats/go-multiaddr-net
- github.com/multiformats/go-multihash
- github.com/opentracing/opentracing-go
- github.com/spaolacci/murmur3
- github.com/whyrusleeping/go-logging
- github.com/whyrusleeping/stump
- github.com/whyrusleeping/tar-utils
- golang.org/x/crypto
- golang.org/x/net

**Comment by Stebalien** [comment]
The sys, go-detect-race, protobuf, and go-log duplicates are bugs that we're slowly fixing.

However, this is otherwise intentional. Instead of vendoring our dependencies, we import them into our IPFS-based package manager called `gx`. This:

1. Means we don't have to check them all into every one of our (many) repositories. This would bloat many of our repositories quite a bit.
2. Allows us to accurately version dependencies (because they're named by IPFS path).
2. Given a stack trace with something like gx/ipfs/QmTsTrxKNXu8sZLv7FP6p884CHoDbT9upKA1j4FkCy5V7T/sys/... in it, you can immediately get the *exact* source for that dependency via ipfs (at `/ipfs/QmTsTrxKNXu8sZLv7FP6p884CHoDbT9upKA1j4FkCy5V7T/sys/`).

See:
* https://github.com/whyrusleeping/gx
* https://github.com/whyrusleeping/gx-go

**Comment by Kubuxu** [comment]
We are using go modules now.
