### ISSUE TITLE
Content added via mfs and ipfs add have different hashes

### ISSUE THREAD

**Issue by achingbrain** [ipfs/go-ipfs#5024]
add:

```sh
$ echo 'Hello, World!' > hello.txt
$ ipfs add hello.txt
added QmYAXgX8ARiriupMQsbGXtKdDyGzWry1YV3sycKw1qqmgH hello.txt
$ ipfs object data QmYAXgX8ARiriupMQsbGXtKdDyGzWry1YV3sycKw1qqmgH | xxd
00000000: 0802 120e 4865 6c6c 6f2c 2057 6f72 6c64  ....Hello, World
00000010: 210a 180e                                !...
```

mfs:

```sh
$ echo 'Hello, World!' | ipfs files write --create /hello.txt
$ ipfs files ls -l
hello.txt	QmPbFXUdgtyrCjExNAjugJTro6Lx4GG4MuvXTiHcZQkiif	14
$ ipfs object data QmPbFXUdgtyrCjExNAjugJTro6Lx4GG4MuvXTiHcZQkiif | xxd
00000000: 0802 180e 200e                           .... .
// huh, weird, only dag-pb bytes in the data field
$ ipfs dag get QmPbFXUdgtyrCjExNAjugJTro6Lx4GG4MuvXTiHcZQkiif
{"data":"CAIYDiAO","links":[{"Name":"","Size":22,"Cid":{"/":"Qmd8q2S2ByCjpRxQvYNrHhC3C6oZ9N9CEbtCxnwakgw6ea"}}]}
// ok, let's look at the linked node
$ ipfs object data Qmd8q2S2ByCjpRxQvYNrHhC3C6oZ9N9CEbtCxnwakgw6ea | xxd
00000000: 0800 120e 4865 6c6c 6f2c 2057 6f72 6c64  ....Hello, World
00000010: 210a 180e                                !...
```

So `ipfs add` gets you one DAGNode with type `file` that contains the data:

```sh
ipfs object data QmYAXgX8ARiriupMQsbGXtKdDyGzWry1YV3sycKw1qqmgH | unixfs
{"type":"file","data":{"type":"Buffer","data":[...]},"blockSizes":[]}
```

But `ipfs files write` leaves you with an empty DAGNode of type `file` that contains a link to a `raw` DAGNode that contains the data:

```sh
$ ipfs object data QmPbFXUdgtyrCjExNAjugJTro6Lx4GG4MuvXTiHcZQkiif | unixfs
{"type":"file","blockSizes":[14]}
$ ipfs object data Qmd8q2S2ByCjpRxQvYNrHhC3C6oZ9N9CEbtCxnwakgw6ea | unixfs
{"type":"raw","data":{"type":"Buffer","data":[...]},"blockSizes":[]}
```

Does anyone know what the thinking behind the difference in structure was?

**Comment by schomatis** [comment]
Nice question, I'm also interested in learning more about the files API and MFS.

@achingbrain there is a nice introductory video [here](https://www.youtube.com/watch?v=FX_AXNDsZ9k) about the files API (although it isn't very recent), the specification is not done yet, I may be missing some other worthwhile resources to read (besides the code of course).

@Stebalien could we bother you with some pointers here?

**Comment by Kubuxu** [comment]
MFS uses different DAG builder than `ipfs add`. It uses trickle DAG, a hybrid between a linked list and a tree (it is better for insertions and edits).

Different hash and structure from `ipfs add` are expected, but I am not sure about that thin linking node. It might be a bug in the DAG builder.

**Comment by schomatis** [comment]
Thanks for the clarification.

@achingbrain Yes, the difference is in the way the tree is built (imported). Adding the file through the trickle importer gives the same hash as adding it with MFS.

```
echo 'Hello, World!' | ipfs add --trickle -Q
# QmPbFXUdgtyrCjExNAjugJTro6Lx4GG4MuvXTiHcZQkiif

echo 'Hello, World!' | ipfs files write --create /hello.txt
ipfs files ls -l
# hello.txt QmPbFXUdgtyrCjExNAjugJTro6Lx4GG4MuvXTiHcZQkiif	14
```

The [trickle builder](https://github.com/ipfs/go-ipfs/blob/139d62409214f2b430edc2bc1af87845f565f6a2/importer/trickle/trickledag.go#L39) (roughly speaking) creates a root node and adds many child nodes (at the same depth) with the file contents. The "empty DAGNode" is the root of the tree with the metadata of the file type and block (child) sizes as you have seen with this `unixfs` command (which I didn't know about, where did that came from?). Because of the way the trickle importer is coded (and this can be improved I think) it always creates the root node without file data and adds a child to it (with the file data), even in the case one node would have sufficed to store it all.

Compare that with the [balanced builder](https://github.com/ipfs/go-ipfs/blob/139d62409214f2b430edc2bc1af87845f565f6a2/importer/balanced/builder.go#L29) which if it can will store the entire file in one node (as you have shown), but if the node data limit (256K in this case) is exceeded it will also create a root (parent) node with the children that will actually store the file data.

```
hash=$(python -c "print('A' * 256 * 1024)" | ipfs add -Q)
ipfs dag get $hash | jq

{
  "data": "CAIYgYAQIICAECAB",
  "links": [
    {
      "Name": "",
      "Size": 262158,
      "Cid": {
        "/": "QmV57mWMAMg7UJ6TpmTqbYgf3A6e4r3arhwBx2N8mvvM8Q"
      }
    },
    {
      "Name": "",
      "Size": 9,
      "Cid": {
        "/": "Qmc5m94Gu7z62RC8waSKkZUrCCBJPyHbkpmGzEePxy2oXJ"
      }
    }
  ]
}
```

**Comment by achingbrain** [comment]
Thanks for the explanation, I hadn't realised the go `mfs` implementation uses trickle DAGs exclusively.  I guess it's fine unless the user wants to seek to a random point in a file, streaming video, for example.  Perhaps they should be able to specify the DAG structure during import in the same way as `ipfs add`?

`unixfs` is a little cli tool I knocked up to make inspecting DAGNode data a little easier while trying to implement `mfs` on `ipfs-js`.  You can get it by doing `npm install -g ipfs-unixfs-cli`.

**Comment by schomatis** [comment]
@achingbrain Great, I'll give it a try.
