### ISSUE TITLE
Bitswap wantlist API

### ISSUE THREAD

**Issue by richardschneider** [ipfs/go-ipfs#5077]
According to the [docs](https://ipfs.io/docs/api/#apiv0bitswapwantlist) `/api/v0/bitswap/wantlist` returns `Keys` which is an array of string.  I assume that the string is either a CID or a block's multihash.

However, `Keys` is actually an array of objects, with I think is an IPLD link
>{"Keys":[{"/":"QmPfMX1epKLZNxG3cAoXYehjiP3inGpzFxFFKW1EregzgC"}]}

It should return something like
>{"Keys":["QmPfMX1epKLZNxG3cAoXYehjiP3inGpzFxFFKW1EregzgC"]}

**Comment by magik6k** [comment]
This is probably a bug in docs generator as the output type is defined as

https://github.com/ipfs/go-ipfs/blob/f7a980926bc4a60f0b51fb665a39316d2dee4890/core/commands/refs.go#L20-L23

and in go `cid.Cid` overrides 'standard' json serialization:

https://github.com/ipfs/go-cid/blob/078355866b1dda1658b5fdc5496ed7e25fdcf883/cid.go#L407-L415

**Comment by richardschneider** [comment]
Thanks @magik6k  for the code pointers.

My question is why does it override 'standard' json serialization?  IPLD is a much higher 'protocol' than bitswap.  Bitswap deals with blocks and CIDs.

**Comment by richardschneider** [comment]
@Mr0grog I really think that the documentation is correct and the API should just return the CIDs.  Why make Bitwswap API consumers know about IPLD (which seems to be WIP)?

**Comment by Mr0grog** [comment]
> IPLD is a much higher 'protocol' than bitswap

Sure, it’s certainly “higher” than a set of routines concerned with trading bits, but the *API* isn’t bitswap. It’s data *about* bitswap, and IPLD is concerned with how you represent and parse data.

On the other hand, I totally agree that it doesn’t seem especially useful that every instance of a CID in the API is formatted as a *link* (besides, a CID [doesn’t even *have* to be formatted like `{"/": "<cid>"}` to be a link](https://github.com/ipld/ipld/issues/39)). It does feel like it adds a lot of noise to the API.

(It also looks to me like this is really the result of trying to make it easier for CBOR to represent a link with *just* a CID, rather than differentiating the two concepts. I was surprised to realize that’s how it works last week.)

**From a more practical perspective, though,** this has been the way the API has worked for [over a year](https://github.com/ipfs/go-cid/commit/7bcaf9264a6423c8fbb4fac1916d0b5a7dd6949b#diff-beb384810133d725af6b502e9b6e3de8R237) and it affects *9* API endpoints:

- `/api/v0/bitswap/stat`
- `/api/v0/bitswap/wantlist`
- `/api/v0/dag/put`
- `/api/v0/dag/resolve`
- `/api/v0/filestore/ls`
- `/api/v0/filestore/verify`
- `/api/v0/object/diff`
- `/api/v0/repo/gc`
- `/api/v0/stats/bitswap`

Seems like a very non-trivial change.

I also think it’s worth considering that, as I learned during the docs research and heard repeatedly since then, the HTTP API docs are [not widely considered a reliable or especially useful reference](https://github.com/ipfs/docs/issues/69).

**Comment by Mr0grog** [comment]
I didn’t mean to derail this discussion entirely! If this is still worth discussing, @richardschneider, we certainly should. I just wanted to make sure we understand the scope when making decisions on this.
