### ISSUE TITLE
always failed when use gx to install dependents,but i can curl and wget using http proxies, can you remove the gx tool or is there any other way to download deps?

### ISSUE THREAD

**Issue by W-B-S** [ipfs/go-ipfs#5151]
C:\Users\NBS\go\src\github.com\ipfs\go-ipfs>make install
bin/check_go_version 1.10
bin/check_go_path /c/Users/NBS/go/src/github.com/ipfs/go-ipfs /c/Users/NBS/go/src/github.com/ipfs/go-ipfs
gx install --global
[[33mget [0m] [fetch]   go-log                        Qmbi1CTJsbnBZjCEgc2otwu8cUFPsGpzWXG7edVCLZ7Gvk
[[33mget [0m] [fetch]   go-libp2p-peer                QmVf8hTAsLLFtn4WPCRNdnaF2Eag2qTBS6uR8AiHPZARXy
[0 / 184] 48sERROR: from shell.Get(): Post https://ipfs.io/api/v0/get?arg=Qmbi1CTJsbnBZjCEgc2otwu8cUFPsGpzWXG7edVCLZ7Gvk&encoding=json&stream-channels=true: EOF
ERROR: from shell.Get(): Post https://ipfs.io/api/v0/get?arg=QmVf8hTAsLLFtn4WPCRNdnaF2Eag2qTBS6uR8AiHPZARXy&encoding=json&stream-channels=true: EOF
[0 / 184] 870sretrying fetch QmVf8hTAsLLFtn4WPCRNdnaF2Eag2qTBS6uR8AiHPZARXy after a second...
retrying fetch Qmbi1CTJsbnBZjCEgc2otwu8cUFPsGpzWXG7edVCLZ7Gvk after a second...
[0 / 184] 998sERROR: from shell.Get(): Post https://ipfs.io/api/v0/get?arg=Qmbi1CTJsbnBZjCEgc2otwu8cUFPsGpzWXG7edVCLZ7Gvk&encoding=json&stream-channels=true: EOF
retrying fetch Qmbi1CTJsbnBZjCEgc2otwu8cUFPsGpzWXG7edVCLZ7Gvk after a second...
ERROR: from shell.Get(): Post https://ipfs.io/api/v0/get?arg=QmVf8hTAsLLFtn4WPCRNdnaF2Eag2qTBS6uR8AiHPZARXy&encoding=json&stream-channels=true: EOF
retrying fetch QmVf8hTAsLLFtn4WPCRNdnaF2Eag2qTBS6uR8AiHPZARXy after a second...
[0 / 184] 1022smake: *** [mk/gx.mk:4: gx-deps] Interrupt

C:\Users\NBS\go\src\github.com\ipfs\go-ipfs>wget https://ipfs.io/api/v0/get
--2018-06-25 16:08:23--  https://ipfs.io/api/v0/get
Resolving ipfs.io (ipfs.io)... 31.13.68.22, 31.13.68.22, 2602:fea2:1:78::, ...
Connecting to ipfs.io (ipfs.io)|31.13.68.22|:443... connected.
ERROR: no certificate subject alternative name matches
        requested host name 'ipfs.io'.
To connect to ipfs.io insecurely, use `--no-check-certificate'.

C:\Users\NBS\go\src\github.com\ipfs\go-ipfs>

**Comment by Stebalien** [comment]
So, the next version of `gx` will support proxies. The current doesn't. You can get support *now* by downloading and recompiling `gx` against a recent version of `go-ipfs-api`. However, you'll have to overwrite `bin/gx` (in the go-ipfs source directory) with your new copy of `gx` to get `make` to use it.

You can download a *complete* (including all deps) source archive here: https://dist.ipfs.io/go-ipfs/v0.4.15/go-ipfs-source.tar.gz. That way, you won't need `gx` at all (it comes with all the requisite deps).

Alternatively, you can install IPFS first (from a binary), set the IPFS_API environment variable to `127.0.0.1:5001`, and then have `gx` use IPFS instead of fetching over HTTPS.

---

Closing as this issue has been fixed in `gx` and isn't actionable. Feel free to ask further questions.
