### ISSUE TITLE
`nipfs ls xxx ` is not useful for `ipfs object new`

### ISSUE THREAD

**Issue by luzhongqiu** [ipfs/go-ipfs#5165]
input:  ipfs object new
output:  xxxxx(hash)

input: ipfs ls -v xxxxx
output: Error: proto: required field "{Unknown}" not set

How can I deal with this?

**Comment by schomatis** [comment]
Hey @luzhongqiu, the `ipfs object new` command (despite its name) creates an empty DAG node without any data inside of it, the `ipfs ls` command belongs to the upper UnixFS layer (which deals with files) and it's looking inside that empty DAG node to look for the file format (that would have the file name, size, etc.) but it's not finding anything, hence the error, which definitely needs to be more descriptive (thanks for this feedback!).

Compare this with creating a new DAG node with an empty directory format:

```
ipfs object new unixfs-dir
# QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn
ipfs ls -v QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn
# Hash Size Name
``` 

It doesn't list anything (as the directory is empty) but it stops complaining because it found a valid directory format inside the DAG node. Does this answer your question? What did you need to accomplish with the `ipfs object new` command? (It's a low-level command that is normally not used by the user, to add files you should call `ipfs add`, or were you just experimenting?

**Comment by luzhongqiu** [comment]
Thanks, but I want to know, how can I distinguish between dictionary or file by a hash

**Comment by schomatis** [comment]
Sorry, I should have clarified that the "You can't" reply meant that the file/directory information isn't encoded inside the hash, that the hash alone won't tell you that, but you definitely can obtain that information with different commands that will do the "fetch and look inside" work for you, like `ipfs files stat`:

```
FILE_HASH=$(echo "File content." | ipfs add -Q)
ipfs files stat /ipfs/$FILE_HASH
# QmTAziJfLUFD67iQRa9YxBzTRLqw5DNie4Roo1GGwtEnDe
# Size: 14
# CumulativeSize: 22
# ChildBlocks: 0
# Type: file          <---

DIR_HASH=$(ipfs object new unixfs-dir)
ipfs files stat /ipfs/$DIR_HASH
# QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn
# Size: 0
# CumulativeSize: 4
# ChildBlocks: 0
# Type: directory      <---
```
