### ISSUE TITLE
Concurrent add and pin doesn't work

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#5376]
... unless `ipfs add --pin=false` is specified. It looks like we're taking the pin lock too early somewhere.

**Comment by Stebalien** [comment]
This is not new. It has been an issue since before 0.4.13.

It looks like `ipfs pin add` takes a *write* lock on the pinset *before* starting the pin.

**Comment by Stebalien** [comment]
Wow, the pinner doesn't even have access to the pin lock.

**Comment by postables** [comment]
Let me know if there's anything I can do to help with this

**Comment by postables** [comment]
@Stebalien Currently in my system I have a queue that process IPFS pin requests, and a queue that processes IPFS file add requests, which is how I initially saw this issue occur.

Since the issue occurs will attempting to add a file with a pin, while also pinning; would a reasonable solution be to add files with no pin, then have a seperate process pin the content to my IPFS node?

**Comment by Stebalien** [comment]
Test case:

```
ipfs dag put <<<'{"link": {"/": "QmdZmoS1b1jp9vL5vgTyebEYUVH6zjd6erhp3fpqV1Zktx"}}'
ipfs pin add zdpuAsWv1LNwtxvFB3iTQjtwDLxPxRaa3WeE4i6BoDuKDy4gf &
echo "thing" | ipfs add
```

The last two commands should block indefinitely.

**Comment by Stebalien** [comment]
So, it turns out that we simply have a hidden requirement here: We need to take the GCLock before taking the pin lock.

Actually, after thinking about this, we can't even take this lock from within `pinner.Pin` as the caller may be holding it.
