### ISSUE TITLE
No result from http://localhost:5001/api/v0/file/ls?arg=<id>

### ISSUE THREAD

**Issue by LaggAt** [ipfs/go-ipfs#5400]
#### Version information:
Hi, I'm using go-ipfs v0.4.17 on windows.

#### Type:
Bug

#### Description:
I try to get a directory listing using the api, therefore I use:
http://localhost:5001/api/v0/file/ls?arg=QmVktW6uo1mcqSiufH7fmExsmyC7dFx2GCYiEDmJLSatnD
This is just someone's folder I found for testing.
Bug is: the request takes forever, and I get no result at all. I monitored the request for some minutes with fiddler, not getting a single byte back.
--- edit: to be exact: I finally got the result, after 3h40 disabling timeout on client side.

Curious is, that the web-api could get a directory listing in no time, using:
http://localhost:8080/ipfs/QmVktW6uo1mcqSiufH7fmExsmyC7dFx2GCYiEDmJLSatnD

I attach two example requests, for fiddler I used and configured the local ip instead of localhost. 
[fiddler.txt](https://github.com/ipfs/go-ipfs/files/2316702/fiddler.txt)

**Comment by Stebalien** [comment]
So, the issue is probably that the `ls` command using the API tries to get the file *type* (to determine if the file is a *file* or a *directory*). Unfortunately, we currently have to fetch the root block of the file to do that and you may not have been able to find a node *with* the relevant blocks (the root blocks of all the files in the directory).

You can disable this by passing `--resolve-type=false`. That is, http://localhost:5001/api/v0/file/ls?arg=QmVktW6uo1mcqSiufH7fmExsmyC7dFx2GCYiEDmJLSatnD&resolve-type=false. That should be significantly faster.

(note: we're *planning* on improving this by embedding the file type in directory entries in an ipfs file-format overhaul but that effort has stalled for now)
