### ISSUE TITLE
Run time error

### ISSUE THREAD

**Issue by akshitababel** [ipfs/go-ipfs#5478]
When I am running a program which is for a web response I am getting a run time error as follows : 

http: panic serving 127.0.0.1:43802: runtime error: invalid memory address or nil pointer dereference
goroutine 6 [running]:
net/http.(*conn).serve.func1(0xc4200a4a00)
/usr/lib/go-1.10/src/net/http/server.go:1726 +0x11b
panic(0x9b5360, 0xd99230)
/usr/lib/go-1.10/src/runtime/panic.go:502 +0x24a
github.com/ipfs/go-ipfs-api.(*RequestBuilder).Send(0xc4201740a0, 0xb95c60, 0xc420022100, 0x0, 0x0, 0x0)
The code of main file is as follows :

func main() {

router := httprouter.New()
router.RedirectTrailingSlash = true
c := cors.New(cors.Options{
	AllowedOrigins:   []string{"*"},
	AllowedMethods:   []string{"GET", "POST", "OPTIONS", "Authorization"},
	AllowedHeaders:   []string{"*"},
	AllowCredentials: true,
})
router.GET("/create", StoreAndGetHash)
router.GET("/read/:hashvalue", GetFile)
router.GET("/appdata/:appID", ReadPeer)
router.GET("/update", UpdateAndGetHash)
router.GET("/createdir", GetDir)
router.GET("/newkey", GetNewKey)

log.Fatal(http.ListenAndServe(":3000", c.Handler(router)))

}

I am working on ubuntu 18.04.1
go version go1.10.1 linux/amd64

**Comment by keks** [comment]
Hi @akshitababel , it seems like you are experiencing issues with go-ipfs-api. Please open an issue in that repo.
Also, the parts you pasted don't contain much valuable information for us. For example, the stack trace mentions go-ipfs-api, but no file name or line number. The main function does not does not even use go-ipfs-api. Based on this information, we can't really help you. Finally, please format your code and terminal output blocks properly. To do this, just select the code lines and click the "<>" in the composer's toolbar. That really helps us understanding the issue at hand.

I'm closing this issue here, feel free to open a new one [here](https://github.com/ipfs/go-ipfs-api)
