### ISSUE TITLE
better content-type for wasm

### ISSUE THREAD

**Issue by eminence** [ipfs/go-ipfs#5520]
#### Description:
I'd like to use ipfs to host small applications written in web assembly.  Currently the public ipfs gateways are serving webassembly files (.wasm extension) with the `application/octet-stream` content-type.  However browsers require that web assembly files be served with the `application/wasm` content-type.

This enhancement request is for the IPFS gateways to use the correct content type for .wasm files.

CC https://github.com/ipfs/infrastructure/issues/433

**Comment by Stebalien** [comment]
Possibly related to https://github.com/ipfs/go-ipfs/issues/4025

**Comment by lidel** [comment]
Related:

- In [this blog post](https://medium.com/temporal-cloud/temporal-ipfs-updates-kubernetes-ens-domains-amazon-s3-playground-organization-management-16353e89b255) Temporal announced  support for custom `?ctype=` parameter
  (I was unable to test because their gateway was down at the time of writing this)
- alternative proposal: manifest file for the IPFS gateway https://github.com/ipfs/go-ipfs/issues/6214

**Comment by eminence** [comment]
Turns out this was fixed a while ago in 2e87ac88a35f15d06702594c2ddad27c2606ee90 🎉 

This is pretty cool because now entirely self-contained webassembly apps can be deployed to / run from IPFS

**Comment by mar1n3r0** [comment]
Hey @eminence I am trying this with [go-app](https://github.com/maxence-charriere/go-app).

Would you mind sharing how did you manage to produce a self-contained wasm application and to load it in the browser?
