### ISSUE TITLE
Requirement (or not) to Accept Incoming Network Connections After Running IPFS Daemon

### ISSUE THREAD

**Issue by hatgit** [ipfs/go-ipfs#5558]
After running the IPFS Daemon successfully at the command line with all swarms listening, and ```"Daemon is ready" ```showing in at the command line, there is a pop-up on my MacOS asking ```"Do you want the application “ipfs” to accept incoming network connections?"``` and I wasn't sure if denying is optional or if IPFS requires this feature. I've already checked the forum for a similar question posed but it wasn't answered so posting this as an issue (although it is partially support related.) perhaps it should be added to the readme? Any answer/help with this is appreciated. Thanks.

**Comment by eingenito** [comment]
Hey @hatgit. The answer is 'it depends'. Under some use cases (like fetching data from the IPFS network) the daemon doesn't strictly require inbound network connectivity (that is other IPFS daemons being able to initiate a connection to the one running on your system). 

If you want to _provide_ content, that is share content currently on your IPFS instance with other IPFS daemons it helps a lot to allow inbound network connection _and_ to have a publicly reachable IP address. 

Those are just general guidelines - it's actually pretty complicated because of the multiple ways that IPFS can connect to other nodes and exchange content.

**Comment by eingenito** [comment]
@hatgit I'm going to close this issue in the hopes that you got an adequate answer. Feel free to reopen it if you have follow-up questions.
