### ISSUE TITLE
Adding files returns Size as String

### ISSUE THREAD

**Issue by felixSchl** [ipfs/go-ipfs#5576]
#### Version information:

```
go-ipfs version: 0.4.15-
Repo version: 6
System version: amd64/linux
Golang version: go1.10.2
```

#### Type:

Potential Bug

#### Description:

The `Object` and `AddedObject` types in `coreunix.add` keeps their size member as a string, but I can find no documentation anywhere as to why, since everywhere sizes are treated as uint64. I started typing this up on SO, but it felt too specific a question and could perhaps be considered a bug in that it's not documented anywhere. The only reason I can think of is that a size might not fit a uint64, but that would not explain why it's only this one module that does this? Wouldn't, for example, an object's cumulative size (object/stat) be able to grow beyond the size limits of a single object and eventually not fit? Actually, the size can hardly be the issue because: https://github.com/ipfs/go-ipfs/blob/cf963724a736029b497d35fa5691a1f1ada1c8c2/core/coreunix/add.go#L559.

**Comment by schomatis** [comment]
Hey @felixSchl, thanks for your concern and for taking the time to report this. So, actually what you're seeing is one of our infinitely-many-pseudo-non-binding object (whatever that means) representations that I kind of stopped caring about. It is basically meaningless since it even reports the size of proto-nodes when actually talking about files/dirs that operate on another layer. If anything this is another testament to the need to have some clear documentation of how are files stored in IPFS that I really need to write (I'm getting to it, I promise :).

I'm closing this issue since I already have many opened about the missing documentation. If you're curious, here is where the size of a normal node is calculated (as an `uint64` as you very well suspected),

https://github.com/ipfs/go-merkledag/blob/master/node.go#L237

and here you can find more details about how a file is chunked into several nodes and the file size is encoded across all of them,

https://github.com/ipfs/go-unixfs/blob/master/importer/balanced/builder.go

**Comment by felixSchl** [comment]
Hey, thank you for the reply, however I would argue that since the json rep of that struct is what gets sent back over HTTP for `api/v0/add` it is leaking and non-internal.

**Comment by schomatis** [comment]
Yes, good point! Re-opening.

I'm not sure we can change this now though, without breaking some kind of compatibility I mean, @keks WDTY? (tl;dr the size reported in the `ipfs add` command is encoded as a string instead of an integer).

**Comment by keks** [comment]
I agree `int` would be better. Unfortunately, I don't see a reasonable upgrade path, because changing this would break our API stability contract.

The types `Object` and `AddedObject` were defined three years ago in [this commit](https://github.com/ipfs/go-ipfs/commit/86901aff3c309065285250b2007160f6685a5963) and if nothing else, it reminds us that decisions early in the project will stick around if you don't implement provisions for an upgrade path from the beginning.

We are currently redesigning the control API protocol and *in theory* it might be possible to fix this in there. However, I'm not 100% clear how that would work, because we try to use the same commands and types over all transports, so we'll have to see how that will work out. I will discuss this issue in that effort's [issue](https://github.com/ipfs/go-ipfs-cmds/issues/37).

**Comment by keks** [comment]
@felixSchl It's not entirely clear why we went for encoding numbers in strings, but a likely reason was future-proofness and [JS's limited precision when parsing integers](https://stackoverflow.com/questions/18755125/node-js-is-there-any-proper-way-to-parse-json-with-large-numbers-long-bigint). In future API protocols we will probably not use JSON so we will be able to use integer types there. I'm closing this issue because encoding numers as strings is intended in this case.
