### ISSUE TITLE
CoreApi.Offline

### ISSUE THREAD

**Issue by magik6k** [ipfs/go-ipfs#5654]
Mentioned in https://github.com/ipfs/go-ipfs/pull/5649#discussion_r228379383, it would be nice to have a way to tell CoreAPI that we want to be in offline mode.

There are a few ways to do this:
- Context hints - https://github.com/ipfs/go-ipfs/issues/4009
  - Should be quite contained
  - Easy to implement global `--offline` flag
- `api.Offline()`
  - Should also be quite contained
  - Easy to implement global `--offline` flag too
  - More visible?
- Functional options on the constructor
  - Also not a bad option, should be decently small change
  - Also easy to implement `--offline`

We could also use this to expose sessions (and maybe other global options later?), so I'd say we should go with the more flexible option, which would be context hints

Opinions?

cc @Stebalien

**Comment by dokterbob** [comment]
Trying to add large (150GB+) resources with a running daemon breaks for us (ipfs-search.com). Probably because the daemon crashes during the process.

I might share these resources using `ipfs-pack`. But due to the large resources required by an IPFS daemon, I would strongly prefer to only run one, and there's already one running on our server (eating about 10GB RAM with about 8k connections).

Hence, it would be ideal to be able to add these resources independently of the running (and regularly crashing, due to it hitting hard memory limits) and then adding them as a one-off operation. Hence, being able to do `ipfs add` *as if* there were no daemon running.

**Comment by Stebalien** [comment]
@dokterbob I believe you're looking for the poorly documented `ipfs --local add` flag. *This* issue is about an offline option such that `ipfs get ...` doesn't use bitswap (although it will likely *also* imply `--local`).

**Comment by Stebalien** [comment]
`ipfs --help` will list the global options (including `--local`).
