### ISSUE TITLE
Block generated by the directory of large number of files

### ISSUE THREAD

**Issue by thomas92911** [ipfs/go-ipfs#5731]
version: 0.4.17

1. mkdir a directory
2. create 50,000 files, each file name exceeds 100 bytes
3. ipfs add -r 5w/

block stat info:

NumLinks: 50000
BlockSize: 7438898
LinksSize: 7438896
DataSize: 2
CumulativeSize: 8888898

This block cannot be transmitted over the IPFS network.

**Comment by Stebalien** [comment]
So, the solution here is to enable [experimental directory sharding](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#directory-sharding--hamt). Unfortunately, it's still experimental because we'd *like* a more generalized solution and have run into some annoying performance issues with the current one. The current plan is to replace the existing experimental feature with either https://github.com/ipfs/go-hamt-ipld or something like it.
