### ISSUE TITLE
Document IPFS_PATH

### ISSUE THREAD

**Issue by anacrolix** [ipfs/go-ipfs#5828]
I think `IPFS_PATH` should be documented. That it's an environment variable, and what it implies. It's referenced in various locations in the docs, but only explicitly offhandedly mentioned that it's an an environment variable in the README. If there are other environment variables that affect the ipfs cmd, it might be grouping the descriptions of these together in a new document.

**Comment by Stebalien** [comment]
So, it's actually pretty well documented in `ipfs --help`.

However, I agree we should have a document listing *all* environment variables. Mind making one? Maybe under `docs/environment-variables.md`?

**Comment by chenminjian** [comment]
If it hasn't been done yet, I want to help with this.

**Comment by schomatis** [comment]
@chenminjian Go for it!

**Comment by anacrolix** [comment]
What's required so that I can assign this to @schomatis ?

**Comment by schomatis** [comment]
I think he meant @chenminjian.

**Comment by schomatis** [comment]
(which I don't seem to be able to assign)

**Comment by anacrolix** [comment]
I meant @chenminjian , I'm still not able to assign however.

**Comment by melwong** [comment]
Yeah, agree. I'm having lots of issues with running IPFS daemon now since I'm a new in sysadmin.

I have the following line in ipfs.service file from a tutorial,
`Environment=IPFS_PATH="$HOME"`
And it's giving me error like `mkdir Permission denied`

What does IPFS_PATH supposed to be? I installed my IPFS under /home/ubuntu. So is it /home/ubuntu/.ipfs or /home/ubuntu?
