### ISSUE TITLE
Improving impromptu communication

### ISSUE THREAD

**Issue by eingenito** [ipfs/go-ipfs#5837]
## Goal

Based on voting in #5819. We want to support easier impromptu communicate as a team. There are a collection of reasons why we think this would be helpful: a faster way to get unblocked, easy way to ask questions etc.  

A number of interesting solutions have already been mentioned like Teamspeak, Mumble or Discord. In this issue we're going to discuss (and decide on) something to try first.

## Summary

*stebalien* - I wish there were some way to flag ourselves as busy/available. Going to IRC and just shouting into the ether hoping someone's listening can be a bit isolating. [also concerned about the distracting nature of lots of notifications]

*eingenito* - I wish there were a more chatty place where just go-ipfs development was discussed. [interested in more conversation]

*djdv* - I do think how we communicate on a regular basis, is an important thing to focus on, and would like to discuss this at some point somewhere. To me subtle changes in our communication patterns and tools could have a big impact. [mentions risk of tribal knowledge and how it might be mitigated by discipline]

*magik2k* - IMO this is definitely worth trying at some point. [mentions experiences with Teamspeak, and also is concerned about tribal knowledge]

*DonaldTsang* - [Discord is an option]

*kevina* - [mentions risk of tribal knowledge in emphasizing voice/video communications]

**Comment by magik6k** [comment]
To iterate on options we have:

* All options:
  * Support all major platforms (Linux/Windows/Mac/Android/iOS)
* Teamspeak3:
  * ++ Reliable from my experience
  * -- Closed source
  * -- Requires special license for commercial use
  * -- Setup should be quick (few h), getting the license may be a bit of pain
  * Has an option to encrypt communication, but it's hard to say if it's done right
* Mumble
  * I haven't used it much
  * ++ Open source
  * ++ No licensing problems
  * ++ Setup should be quick (2-3h)
  * ++ TLS + OCB-AES128
  * -- Default ui is a bit ugly, but at least it's clean.
  * -- afaik has less powerful permission system than teamspeak, but we don't really need that.
* Discord
  * -- [`By uploading, distributing, transmitting or otherwise using Your Content with the Service, you grant to us a perpetual, nonexclusive, transferable, royalty-free, sublicensable, and worldwide license to use, host, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform, and display Your Content in connection with operating and providing the Service.`](https://discordapp.com/terms)
  * -- No commercial license - [`solely for your personal, non-commercial use, unless we agree to your commercial use in writing`](https://discordapp.com/terms)
  * -- In browser or Electron app
  * ++ Has a shiny UI (I don't think anyone really cares about this point)
  * ++ Has some shiny features like video chats and screen sharing (can just use zoom/slack for that)
  * +- Text chat is not paired with voice channels, and users can be in more than one text channel at once. I'd say that this isn't an advantage for us because:
    * With teamspeak/mumble these text channels are really only useful for sending links related to what we talk about, anything else should likely be discussed on IRC/GitHub anyways, the 'discord' way may encourage bad practices.
* Something else?
  * Voice over pubsub?
    * <sub><sup><sub>no</sub></sup></sub>

**Comment by djdv** [comment]
I lean towards mumble just for the self hosted, open nature of it.
The reference client is a bit rough in terms of UX, and lacking (imo) compared to TeamSpeak, but it's portable, free, and it works to simulate a collection of rooms that people can create, enter, and exit (with auth methods).
In my experience on the server and client side, it's pretty much set and forget for most options we have.
I've been hosting and using ventrillo, teamspeak, mumble, and others, on my own machines over the years.

In the future I'd love to see us using something less centralized, like maybe something built around IPFS (voice over p2p sockets: YES), matrix, or even xmpp, but we may not be there yet.
https://tox.chat/ is a P2P protocol with some clients that has been on my "to check" list for a while but I haven't gotten around to it.
We might be able to setup a chatroom with voice and video capabilities in P2P IM clients like this if we find a good one.

I really like the Discord UX but not a fan of anything else around it. If there was a self hosted solution on the server side and more choice on the client side, it could be nice, but I personally avoid it if I can.
There's also a common complaint that I'm familiar with, where your audio stops broadcasting and you really wouldn't know it.
Not sure if this has improved since last time I used it (~2 years) but it happened often enough then to annoy a lot of people.

The "IM" tools like matrix, tox, slack, et al. seem better for scheduled conference calls where the "voip" tools like mumble, teamspeak, et al. seem better for simulating a passive lounge/workspace.

Slack is honestly pretty close to ideal for me on the UX side. Love threads, emoji replies, voice+video capabilities, persistent logs, etc. but also suffers from being closed, centralized, and not self hosted.
Some people have expressed their disinterest (elsewhere) in slack though.

All in all, I think mumble is a good starting point that will last a while with the least headaches. But I'm very open to seeing alternatives as well.

**Comment by Stebalien** [comment]
I'd like to start with mumble. I wish matrix had a decent conference call system but it's not there yet.

I haven't used TOX in years but, in my experience, it never really worked well (and they had a bunch of community issues that killed the project, at least for a while).

I refuse to use discord on principle.
