### ISSUE TITLE
Use Go modules

### ISSUE THREAD

**Issue by anacrolix** [ipfs/go-ipfs#5848]
With Go 1.11, Go modules may be an option for versioning dependencies.

**Comment by mhchia** [comment]
@anacrolix  May I ask how did you generate the `go.mod` in the PR https://github.com/ipfs/go-ipfs/pull/5849? (Sorry for asking here. I just don't want to interrupt the code review in the PR)

I'm also trying to change from gx to gomod in my project. In my understanding, this needs to resolve the `gx_hash` or version of each gx dependency to git repo and (commit or tag). After resolving, we can make use of `go get` to update the dependency to `go.mod`. To resolve the hash, I had some naive approaches, but not sure if they are correct. Please correct me if anything wrong:

- To find commits, my naive approach was to download and synchronize the corresponding git repo for each dependency, and try to `git grep` the `gx_hash` from the repo, to see which commit first contains that `gx_hash`. However, some repo does not contain `.gx/lastpubver`, possibly because that the repo doesn't use gx and was just pushed to gx(ipfs), or, the repo just doesn't contain `.gx/lastpubver`.
- To find versions(tags), I just search if there is a same version tag in the git repo as the gx version specified in `package.json`. However, I found there are some inconsistence. E.g. in github.com/libp2p/go-libp2p-kad-dht the gx version is `4.4.17` by the time I write this question, while the latest tag in the git repo is `v4.4.12`.

Because of the problems above, I couldn't resolve all gx versions/hashes of my dependencies. I'm really interested in if there is a way to map the gx version/hash to the git repo version/commit. This way we can make use of `go.mod` for projects which previously used `gx`, before a formal solution has come out discussed in https://github.com/ipfs/go-ipfs/issues/5850 and https://github.com/whyrusleeping/gx/issues/200

**Comment by mhchia** [comment]
@anacrolix  Thanks a lot for the explanation. Your approach sounds pretty reasonable. In my situation, I have roughly 100 dependencies including the transitive ones, and I can only resolve the git version/commit for three-fourths of them from gx hashes. So I will rather use the latest versions in my case, following your approach.

> or unpack the gxDependencies.hash value, which may or may not correspond to something git is aware of

It's a cool thing. I thought it is just something similar to the hash of the package. Will see if there is any related information from there.

**Comment by magik6k** [comment]
All gx packages have `.gx/lastpubver` which you could use to assign versions to commits. I'm not sure if it will work everywhere because you may hit duplicate versions on merged branches in some packages.

**Comment by mhchia** [comment]
@magik6k Thanks for the direction. Yeah currently for each gx package, I go to its git repo, search for the first commit whose `.gx/lastpubver` contains the gx package's hash, and assume it is the corresponding git commit in the git repo. Some of the git repo who has been put onto the gx does not have `.gx/lastpubver`. Though, I just found the organization https://github.com/gxed which contains many gxed packages. This information seems to possibly resolve my issues. Are all of the gxed packages forked to the organization?

**Comment by lanzafame** [comment]
> Should all of the gxed packages be forked to the organization gxed?

Yes. Are they all forked to gxed? No.

**Comment by Kubuxu** [comment]
We are using go modules now.
