### ISSUE TITLE
ipfs files rm error: file does not exist

### ISSUE THREAD

**Issue by syzh** [ipfs/go-ipfs#5898]
but ipfs get QmPsndrz6Q6kRAsU5pd3VkBDRj6qXHdhduKevk4yDajGhe, ipfs cat QmPsndrz6Q6kRAsU5pd3VkBDRj6qXHdhduKevk4yDajGhe is success. and return data

**Comment by Stebalien** [comment]
The `ipfs files` command allows you to manipulate a virtual mutable filesystem. `ipfs files rm Qm...` doesn't work because, while a file with that hash may exist in IPFS, no file by that name has been added to your virtual filesystem (e.g., with `ipfs files cp /ipfs/QmPsndrz6Q6kRAsU5pd3VkBDRj6qXHdhduKevk4yDajGhe /QmPsndrz6Q6kRAsU5pd3VkBDRj6qXHdhduKevk4yDajGhe`).

(closing for tracking)

**Comment by schomatis** [comment]
Related to https://github.com/ipfs/go-ipfs/issues/5862.
