### ISSUE TITLE
Prefix log filename unhelpful

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#592]
There are lots of logs using prefixlog that print out a message, but give no indication of where that message originated from, since the log function is being called from inside prefixlog. This can be solved by increasing the value of `ExtraCallDepth` on the logger object itself: https://github.com/op/go-logging/blob/4d186fb040e7e748df3736262acc9816156cc194/logger.go#L88

**Comment by jbenet** [comment]
@whyrusleeping yeah I opened https://github.com/op/go-logging/issues/44 before the `ExtraCallDepth` merged to master. We just haven't updated our logger to deal with this.

**Comment by jbenet** [comment]
This requires:
- [ ] vendoring op/go-logging again instead of my fork
- [ ] wrapping go-logging to fit our StandardLogger interface (i.e. what my fork did)
- [ ] setting the `ExtraCallDepth` in the prefix logger.
- [ ] moving everything to use one logger (i think we want `eventlog`)

Nice:
- [ ] moving the logging stuff out of `util` and into its own package (`util/logging` ?)

Long term good idea (though this still needs work):
- [ ] move everything to use `logrus` -- https://github.com/sirupsen/logrus

I started on this here: https://github.com/jbenet/go-ipfs/tree/fix/logging/stash -- but i'm shifting to do something else, sorry.

**Comment by jbenet** [comment]
Closed in #1359
