### ISSUE TITLE
Flatfs Unstable, and Crashing Once Every 2-3 days, Issue preceeded by `too many open files`

### ISSUE THREAD

**Issue by bonedaddy** [ipfs/go-ipfs#5944]
#### Version information:
Version info
```
go-ipfs version: 0.4.18-
Repo version: 7
System version: amd64/linux
Golang version: go1.11.1
```

Repo stats
```
NumObjects: 1427247
RepoSize:   165253110418
StorageMax: 12000000000000
RepoPath:   /ipfs-node
Version:    fs-repo@7
```

`$IPFS_PATH/config.Datastore`
```json
  "Datastore": {
    "StorageMax": "12000GB",
    "StorageGCWatermark": 90,
    "GCPeriod": "1h",
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "/ipfs-data/blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
            "sync": true,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "/ipfs-data/datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "HashOnRead": true,
    "BloomFilterSize": 4096000000
  },
```

`$IPFS_PATH/datastore_spec`
```json
{"mounts":[{"mountpoint":"/blocks","path":"/ipfs-data/blocks","shardFunc":"/repo/flatfs/shard/v1/next-to-last/2","type":"flatfs"},{"mountpoint":"/","path":"/ipfs-data/datastore","type":"levelds"}],"type":"mount"}
```

CPU: `Intel(R) Xeon(R) CPU E5-2660 v4` x2
Memory: 128GB DDR4
OS Disk: 256GB SSD
`$IPFS_PATH` disk: 256GB SSD
Datastore Disk: 12TB RAID6 iSCSI

`ulimit -n`: 65535

#### Type: Bug

IPFS node will spit out flatfs errors about `too many open` files, then crash with a massive goroutine panic log.

#### Description:

I have 2 nodes of equal spec, except 1 is running badgerds, and has no problems. The one with the problems is the one running flatfs. 

After awhile it will log errors about too many files being open. Afterwards, the node will crash generating a massive log that I've uploaded to IPFS, it is 19MB in size.

Nodes are started with `ipfs daemon --enable-namesys-pubsub` and a peer range of 1200 low watermark, 1500 high watermark.

From what I can tell the peer count is pretty high compared to other nodes, but i've been running with these connection settings for ~6 months without any issue. This is my first time in about 7 months using flatfs

Log file: https://ipfs.io/ipfs/QmZ2ezNEkjzcUfdcVYJub4ZuwcbAFJCioP4VPN8Nuf6Bwb

**Comment by magik6k** [comment]
Can you try running
```
export DPID=$(pidof ipfs); watch -n0 'printf "sockets: %s\nleveldb: %s\nflatfs: %s\n" $(ls /proc/${DPID}/fd/ -l | grep "socket:" | wc -l) $(ls /proc/${DPID}/fd/ -l | grep "\\/datastore\\/" | wc -l) $(ls /proc/${DPID}/fd/ -l | grep "\\/blocks\\/" | wc -l); netstat -anpt 2>/dev/null | grep "$DPID/ipfs" | sort -k6 | column -N "a,b,c,d,e,f,g" -J | jq ".table[].f" --raw-output | uniq -c'
```

And see what actually consumes FDs?

**Comment by postables** [comment]
Sure, how often do you want me to run it?  Getting an invalid `-N` option for column

```
Every 0.1s: printf "sockets: %s\nleveldb: %s\nflatfs: %s\n" $(ls /proc/${DPID}/fd/ -l | grep "socket:" | wc -l) $(ls /proc/${DPID}/fd/ -l | grep "\\/datastore\\/" | wc ...  delta-node-1: Thu Jan 24 15:59:39 2019

sockets: 947
leveldb: 10
flatfs: 1
column: invalid option -- 'N'
usage: column [-txne] [-c columns] [-s sep] [file ...]
```

**Comment by Stebalien** [comment]
Can you run those commands after a day or so?

**Comment by postables** [comment]
After running for about 1.5 days:

```
sockets: 1334
leveldb: 12
flatfs: 1
```

**Comment by Stebalien** [comment]
Hm. I wonder if that's a garbage collection run? Do you have garbage collection enabled?

**Comment by Stebalien** [comment]
> Nope, iirc the only way to enable garbage collection is with a command-line flag when starting the daemon?

Correct. 

>  I have since opening this issue, changed my peer count to 600 as low-watermark, and 900 as high-watermark, however the node that I pulled those statistics from, I forgot to apply the config change so its still using a high-watermark of 1500

Assuming your file descriptor limit is actually 65k, that shouldn't be the issue. Actually, can you cat `/proc/$(pidof ipfs)/limits`? I want to make sure something isn't messing with the limits.

**Comment by postables** [comment]
@Stebalien I notice that ipfs daemon still says `raising limit to 2048` on startup, based off the following it looks like it is indeed overriding the 65k to 2048 (formatted into a table because the original output was awful to read)

| Limit  |  Soft Limit  | Hard Limit   | Units  | 
|---|---|---|---|
| Max cpu time | unlimited | unlimited | seconds   |
| Max file size |  unlimited   |         unlimited        |    bytes |     
| Max data size      |       unlimited          |  unlimited        |    bytes     |
| Max stack size     |       8388608         |     unlimited         |   bytes     |
| Max core file size    |     0           |         unlimited       |     bytes     |
| Max resident set   |       unlimited   |         unlimited     |       bytes     |
| Max processes      |      515094        |       515094       |        processes |
| Max open files       |      2048        |         2048      |           files     |
| Max locked memory  |  16777216     |        16777216        |     bytes     |
| Max address space      |   unlimited         |   unlimited    |        bytes     |
| Max file locks      |      unlimited   |         unlimited        |    locks     |
| Max pending signals     |  515094         |      515094    |           signals   |
| Max msgqueue size      |   819200      |         819200      |         bytes     |
| Max nice priority     |    0         |           0          |          
| Max realtime priority |    0        |            0               |     
| Max realtime timeout    |  unlimited     |       unlimited       |     us       |

**Comment by Stebalien** [comment]
Try setting the `IPFS_FD_MAX` environment variable. IPFS _shouldn't_ be reducing the file descriptor limit, no matter what.

**Comment by postables** [comment]
I'm trying to set it and I'm getting the following error when trying to start my node
```
^[[0;37m15:10:59.458 ^[[31mERROR ^[[0;34m  cmd/ipfs: ^[[0msetting file descriptor limit: cannot set rlimit, IPFS_FD_MAX is larger than the hard limit ^[[0;37mdaemon.go:205^[[0m
```

This is what I have it set to right now `export IPFS_FD_MAX=16384` it looks like for some reason the IPFS node is trying to fix it to `2048`.

setting `export IPFS_FD_MAX=2048` does not cause any errors when starting the daemon and shows:

```
Successfully raised file descriptor limit to 2048.
```

**Comment by Stebalien** [comment]
Ah, sorry, I didn't thoroughly read that table. Something is setting a lower _hard_ limit for go-ipfs. Really, given that table, 4096 shouldn't have worked either. The hard limit is 2048.

> it looks like for some reason the IPFS node is trying to fix it to 2048.

This is something else, not IPFS. IPFS won't (unless there's a bug I'm not seeing) ever reduce the file descriptor limit. Furthermore, it _can't_ reduce the hard limit.

**Comment by postables** [comment]
Hmm okay let me poke around a bit more and see what i can find.

**Comment by Stebalien** [comment]
Closing as stale. We now set the max FD limit to 8192 if we can which should be sufficient for most cases.
