### ISSUE TITLE
`ipfs dht put` fails

### ISSUE THREAD

**Issue by LastExile16** [ipfs/go-ipfs#5967]
I want to put a value into dht manually. through the documentation it says `ipfs dht put` only works with _ipns_ key-type, so I tried to put a value to `/ipns/<my peer id>`, I got `record could not be unmarshalled` error which I don't know what does it mean!
```
$ ipfs dht get QmZkYvWH99M3QoMKgMWFMFfvwi2C6BA8Cmh58jMRtBtUpk
$ echo "Hello World!" | ipfs dht put -v /ipns/QmZkYvWH99M3QoMKgMWFMFfvwi2C6BA8Cmh58jMRtBtUpk
20:58:47.255: error: record could not be unmarshalled
$ echo "Hello World!" | ipfs dht put /ipns/QmZkYvWH99M3QoMKgMWFMFfvwi2C6BA8Cmh58jMRtBtUpk
$ ipfs dht get QmZkYvWH99M3QoMKgMWFMFfvwi2C6BA8Cmh58jMRtBtUpk
$ 
```
Notice that I don't get any error messages or feedback if `verbose` flag isn't set.

- Am I doing it wrong?
- what does the error message mean?
- Can I pick anyones' `<peerID>` or any hashed key instead of my peer id?

**Comment by leerspace** [comment]
> I want to put a value into dht manually.

Why?

> so I tried to put a value to `/ipns/<my peer id>`, I got `record could not be unmarshalled` error which I don't know what does it mean!

You tried passing in something that is not a valid IPNS entry. IPNS entries are very specifically formatted.

> Am I doing it wrong?

I expect that you should be using `ipfs name publish` if you want to publish something using your IPNS public key. Though if you really need to be publishing arbitrary entries to the DHT then that probably won't suit your use-case. I'd imagine this isn't supported in order to prevent abuse, but I could be mistaken.

> Can I pick anyones' `<peerID>` or any hashed key instead of my peer id?

No. You can only publish IPNS entries for IDs/keys you own.

**Comment by LastExile16** [comment]
Although I thought it's a bug (at least the _error_ message should be returned without using `verbose` flag), I think I should have opened this on **discuss.ipfs** instead of here.

I am just curious about using `ipfs dht put` and `ipfs dht get` commands ;) 
Not being able to use other `<peer id >` makes a lot of sense.


> You tried passing in something that is not a valid IPNS entry. IPNS entries are very specifically formatted.

What is that _specific format_? the `ipfs name publish` publishes it to my `<peer id>` or the generated `key` that I own, and as you can see I used my `<peer id>` to make sure the format is the same as `ipfs name publish`

**Comment by leerspace** [comment]
> Although I thought it's a bug (at least the _error_ message should be returned without using `verbose` flag)

I'd agree that verbose output shouldn't be needed in order to see the error.

> What is that _specific format_?

It looks like a valid [IPNS entry](https://github.com/ipfs/go-ipns/blob/ec728150635864b77f4c3c649516027b40e97670/ipns.go#L19) mainly consists of a protobuf-encoded
* IPFS path
* sequence number
* RFC 3339 timestamp indicating when the entry is valid until
* cryptographic signature of the entry using the private key

**Comment by michaelavila** [comment]
I'm going to close this issue as the bug mentioned appears to be fixed, here's my output when running the commands above:


```sh
λ echo "Hello World" | ipfs dht put -v /ipns/QmZkYvWH99M3QoMKgMWFMFfvwi2C6BA8Cmh58jMRtBtUpk
14:19:10.900: error: record could not be unmarshalled
Error: record could not be unmarshalled
~
λ echo "Hello World" | ipfs dht put /ipns/QmZkYvWH99M3QoMKgMWFMFfvwi2C6BA8Cmh58jMRtBtUpk
Error: record could not be unmarshalled
```

**Comment by pontiyaraja** [comment]
@michaelavila `Ipfs dht put` is not working properly
