### ISSUE TITLE
ipfs repo is full, how to expand it to a new disk?

### ISSUE THREAD

**Issue by hoogw** [ipfs/go-ipfs#6017]
My ipfs repo is on c drive, 1TB, is full. I can't add more. However, D drive 1TB is empty, how to expand or add more storage to D drive?

I know I can (mac) export ipfs_path=/volume D/2nd_ipfs_repo, 
 (windows)set new environment variable  ipfs_path= 'D:/2nd_ipfs_repo' 

If I do so, does I lost the stuff on C drive old ipfs_repo?

**Comment by magik6k** [comment]
All storage mechanisms go-ipfs currently supports require that data is stored in a single directory.

I assume that settunig up RAID0 is not an option for you, so the best option would probably be to setup https://github.com/ipfs/ipfs-cluster with 2 go-ipfs instances on your computer.

I'm not sure what is the best way to move from one go-ipfs node to ipfs-cluster with 2 nodes, cc @hsanjuan.

For a more 'hacky' solution - it might also be possible to support distributing flatfs (`$IPFS_PATH/blocks/`) to multiple drives by symlinking some of the shard directories to the other drive, but it might not work well on Windows (and I'm not sure if it would even work on Linux/Mac)

**Comment by hsanjuan** [comment]
something similar to `ipfs pin ls --type recursive --quiet | xargs -n1 ipfs-cluster-ctl pin add -r 1`. You may do this in 2 or 3 batches and GC the original node in between so that space gets freed up, so that Cluster doesn't assign all new pins to the empty node because it has more free space in the repository (cluster will unpin from the original node when content is allocated to the other one).
