### ISSUE TITLE
ERROR: bitswap: Ended request for cid (<CID>) not in progress providerquerymanager.go:358

### ISSUE THREAD

**Issue by wmitsuda** [ipfs/go-ipfs#6046]
#### Version information:
go-ipfs version: 0.4.19-83d3f76
Repo version: 7
System version: amd64/darwin
Golang version: go1.12

#### Description:
After upgrading to 0.4.19 via homebrew, I started noting some error messages on ipfs-daemon output as websites are redirected to the local gateway thanks to ipfs chrome extension.

04:07:44.513 ERROR    bitswap: Ended request for cid (<CID>) not in progress providerquerymanager.go:358

They are all like this, with different CIDs. I didn't note a specific pattern that triggers the error.

**Comment by Stebalien** [comment]
Thanks for the report. It looks like this is an unecessary error log, feel free to ignore it.

Fix in: https://github.com/ipfs/go-bitswap/pull/91

**Comment by dokterbob** [comment]
@Stebalien I'm getting a *lot* of these (running ipfs-search.com crawler). Is there a way to just block these messages?

**Comment by Cu7l4ss** [comment]
If I might add, it seems that it makes the request from the user fail.
I've had 504 returning multiple times and this error was printed.
ipfs version: 0.4.19
system version: linux-amd64
running with prebuilt package of 0.4.19

**Comment by Stebalien** [comment]
@dokterbob you can fetch the latest go-ipfs master and run `GO111MODULE=on go get github.com/ipfs/go-bitswap@master` to use the latest master. Actually, you may want to try `GO111MODULE=on go get github.com/ipfs/go-bitswap@fix/reduce-provide-workers`. That's what we're currently running on our gateways.

@Cu7l4ss this log message is only hit on timeout. That's why you're seeing that.
