### ISSUE TITLE
ipfs only use max 5% bandwidth, why? 

### ISSUE THREAD

**Issue by hoogw** [ipfs/go-ipfs#6054]
My workplace bandwidth upload speed is 800Mbps, (speedtest.net)
however, when I look at the ipfs-webui and ipfs-desktop, 
the max outgoing speed is 40Mbps, only 5% of 800Mbps. 
Why?
Does it have configuration somewhere to limit the outgoing speed?

[https://transparentgov.net/json2tree/ipfsList.html](https://transparentgov.net/json2tree/ipfsList.html)

My home bandwidth upload speed is 10Mbps, (speedtest.net)
ipfs-webui and ipfs-desktop can reach max 12Mbps, it is 100% allowed bandwidth used.

**Comment by djdv** [comment]
Are you seeing these results with a specific test?
If not, it is possible that more bandwidth is not being requested from you at the time you are checking.
For example, if your upload can support 100Mbps, but only 1 person is downloading from you on a connection of 50Mbps, you will not utilize entire connection of yours, but will entire connection of theirs.

Could it be the case?

**Comment by hoogw** [comment]
No, it is more complicate than client download speed threshhold.

My workplace download 800Mbps, upload 100Mbps (speedtest.net)
This computer host ipfs, I also use the browser(on same computer) to visit the pdf file on the same computer.
The usage is 40Mbps Max.

The bottleneck is public gateway!
If I use local gateway, do same thing, it supper fast, without any delay. 

But if I use public gateway, the max speed is 40Mbps. 

Public Gateway is bottleneck of speed.

**Comment by lordcirth** [comment]
It's hardly surprising that the volunteer-run gateway can't do better than 40Mbps. That's 40 times better than my upload speed. Doesn't seem like an IPFS problem to me.

**Comment by djdv** [comment]
>If I use local gateway, do same thing, it supper fast, without any delay.

It seems like you've switched now, but for the issue tracker:
It should be known that anyone can host a gateway, "ipfs.io" is just one of them. So if you find that you need more capabilities than any 1 gateway offers, you can refer people to another one (like "cloudflare-ipfs.com"), or host+expose your own gateway for people to use.

If possible, the ideal is for clients to be using ipfs directly rather than relaying traffic through any gateway. This will be direct, and as fast as possible between the 2 peers, rather than bound by the relay(gateway).

**Comment by djdv** [comment]
Closing for age+answered.
