### ISSUE TITLE
problem with gateway.ipfs.io

### ISSUE THREAD

**Issue by ivan386** [ipfs/go-ipfs#6158]
#### Version information: 
{"Version":"0.4.20-dev","Commit":"29668e116","Repo":"7","System":"amd64/linux","Golang":"go1.12"}

#### Description:

On my site: https://ivan386.tk
I see: Welcome to nginx!

ivan386.tk is an alias of gateway.ipfs.io

site use cloudflare cdn service.

**Comment by Stebalien** [comment]
Make sure to carefully follow the instructions here: https://www.cloudflare.com/distributed-web-gateway/#connectingyourwebsite. I believe you need to use a CNAME, not an alias. You may also need to put the DNSLink record under `_dnslink.ivan386.tk` instead of directly under `ivan386.tk` (I'm not sure what changes CloudFlare has made to their gateway).

**Comment by ivan386** [comment]
@Stebalien i use cname and domain have _dnslink record. And if i change gateway.ipfs.io to cloudflare-ipfs.com problem disappear.

**Comment by Stebalien** [comment]
I'm not seeing any CNAME records for ivan386.tk, just an A record for `104.24.{126,127}.137` (cloudfair).

**Comment by ivan386** [comment]
@Stebalien Cloudflare proxy request to gateway.ipfs.io. If i switch to direct request i get cert error. If i allow this cert then get same msg "Welcome to nginx!".
Example: https://gw.ivan386.tk

**Comment by Stebalien** [comment]
Cloudflare doesn't proxy anything to gateway.ipfs.io. They run their _own_ IPFS gateway.

You're getting the certificate error because, unlike cloudflare's gateway, our gateway won't automatically generate an SSL certificate on your behalf. Cloudflare uses certbot to do this automatically but we don't yet have support for this on our gateways.

Note: http://gw.ivan386.tk (not `https`) works just fine for me.

**Comment by ivan386** [comment]
@Stebalien problem appear only on https version. Problem not in certificate. Cloudflare proxy can acept it. Problem after it. Server do not return site content. Instead it show "Welcome to nginx!".

Cloudflare is proxy request to gateway.ipfs.io. Because i set cname ivan386.tk to gateway.ipfs.io and turn cache proxy on.

To use cloudflare gateway i set cname cf.ivan386.tk to cloudflare-ipfs.com. [here instructions](https://www.cloudflare.com/distributed-web-gateway/#connectingyourwebsite)

https://ivan386.tk -> cf proxy -> gateway.ipfs.io
https://gw.ivan386.tk -> gateway.ipfs.io
https://cf.ivan386.tk -> cloudflare-ipfs.com

**Comment by Stebalien** [comment]
> Cloudflare is proxy request to gateway.ipfs.io. Because i set cname ivan386.tk to gateway.ipfs.io and turn cache proxy on.

I see. You're using cloudflare as a reverse proxy for gateway.ipfs.io, not as a gateway.

That nginx page is being served by cloudflare and your request is never hitting our gateways, as far as I can tell. Unfortunately, there's not much I can do to help you here.

**Comment by ivan386** [comment]
@Stebalien you wrong. If you try to open https://gw.ivan386.tk/ and allow incorrect certificate you will see same msg "Welcome to nginx!".

**Comment by Stebalien** [comment]
Huh. You appear to be correct. I guess cloudflare's reverse proxy is replacing _all_ of our headers (I saw a `server: cloudflare` header and assumed this was being served by them).

In that case, our gateways probably just aren't setup for https for third-party domains (likely because we don't have certificates for these domains).

@scout can you comment on this? How do our gateways react to `https://some.other.domain` when that domain uses dnslink?

**Comment by scout** [comment]
>In that case, our gateways probably just aren't setup for https for third-party domains (likely because we don't have certificates for these domains).

Correct. Only http requests to the gateway are available for third-party domains at the moment

**Comment by Stebalien** [comment]
Is there any technical reason for this?

**Comment by scout** [comment]
Well, we would need to have a predictable `server_name` for nginx to listen for with a local certificate that validates the name. We therefore only manage certs for domains that we own and maintain. Third party domains can, however, run a reverse proxy for http or https calls to the gateway where they are able to host gateway calls via a custom domain.

**Comment by Stebalien** [comment]
Hm. So, I think @ivan386 is using a reverse proxy but it's routing https to https (not https to http). I'm not entirely sure why it's even working as much as it is. I'm guessing cloudflair must be ignoring the certificate errors (or manually validating that the certificate matches `gateway.ipfs.io`).

For context, https://ivan386.tk/ is giving a "welcome to nginx" page which appears to be served from our server for unknown domains.

**Comment by scout** [comment]
I found where requests were getting defaulted and why the nginx welcome page was coming up - I'm testing a fix where those sorts of calls get a `444` instead. If that looks good we will roll that out to the gateways tomorrow. The end recommendation for third party domains is the same though: folks should set up a reverse proxy to proxy calls to `ipfs.io` or `gateway.ipfs.io` (via http or https)

**Comment by ivan386** [comment]
@scout ```gateway.ipfs.io``` should be default server for unknown domains. At this time it ```dwebops.net```.

**Comment by scout** [comment]
@ivan386 the `dwebops.net` is actually expected here as it's our `default_server` - Are you running a reverse proxy to `gateway.ipfs.io`? If so, can you copy/paste your config here?

**Comment by ivan386** [comment]
@scout 
![config](https://user-images.githubusercontent.com/717207/55609098-8df01100-5788-11e9-9ad3-29aeb15ff948.png)

**Comment by scout** [comment]
@ivan386 That’s not going to work as we don’t have a way to validate your domain for https calls. Instead, you would need to run a reverse proxy to our gateway via a web server configured for your domain certs.

**Comment by ivan386** [comment]
@scout as i said [before](#issuecomment-478562009)
> Problem not in certificate. Cloudflare proxy can acept it. Problem after it. Server do not return site content. Instead it show "Welcome to nginx!".

**Comment by scout** [comment]
There are two issues here:
 - we do run a service to validate your domain (only cloudflare's gateway does)
 - since we do not accept traffic via third party domains, we also do not resolve your domain to the dnslink or IPNS hash via your DNS records

The untrusted domain and well as the returned `444` from our gateway service is the expected response if you are not running a separate reverse proxy to our gateways.

**Comment by ivan386** [comment]
@scout Ok what reverse proxy must do to get site content over https connection?

**Comment by mburns** [comment]
@ivan386 what I think you want to do is follow a guide like https://rklaehn.github.io/2018/06/08/running-ipfs-gateway/ that sets nginx to (1) handle SSL certs and (2) proxies incoming requests to a local ipfs daemon that you control.

**Comment by ivan386** [comment]
@mburns Easy way for me is to use cloudflare gateways. I switched my sites to it when that problem appear. But i wont to use gateway.ipfs.io as second trusted gateway.
