### ISSUE TITLE
/pin/* endpoints API inconsistencies

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/go-ipfs#6269]
#### Description:

* `/pin/update` always returns the given arguments (as ipfs-paths) in the responses, however `/pin/add` returns the resolved CIDs (and not paths):

```
curl "localhost:5001/api/v0/pin/update?arg=/ipns/QmTuAM7RMnMqKnTq6qH1u9JiK5LqQvUxFdnrcM4aRHxeew&arg=Qmbvkmk9LFsGneteXk3G7YLqtLVME566ho6ibaQZZVHaC9&unpin=false"
{"Pins":["/ipns/QmTuAM7RMnMqKnTq6qH1u9JiK5LqQvUxFdnrcM4aRHxeew","/ipfs/Qmbvkmk9LFsGneteXk3G7YLqtLVME566ho6ibaQZZVHaC9"]}
```

```
curl "localhost:5001/api/v0/pin/add?arg=/ipns/QmTuAM7RMnMqKnTq6qH1u9JiK5LqQvUxFdnrcM4aRHxeew"
{"Pins":["QmR9pC5uCF3UExca8RSrCVL8eKv7nHMpATzbEQkAHpXmVM"]}
```

* `/pin/update` with a single argument or no arguments returns a text error :

```
curl -v "localhost:5001/api/v0/pin/update?arg=/ipns/QmTuAM7RMnMqKnTq6qH1u9JiK5LqQvUxFdnrcM4aRHxeew"
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 5001 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 5001 (#0)
> GET /api/v0/pin/update?arg=/ipns/QmTuAM7RMnMqKnTq6qH1u9JiK5LqQvUxFdnrcM4aRHxeew HTTP/1.1
> Host: localhost:5001
> User-Agent: curl/7.60.0
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< Vary: Origin
< Date: Fri, 26 Apr 2019 22:37:12 GMT
< Content-Length: 30
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host localhost left intact
argument "to-path" is required
```

but `/pin/update` with a bad argument returns a JSON error:

```
curl -v "localhost:5001/api/v0/pin/update?arg=cdf&arg=abc"
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 5001 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 5001 (#0)
> GET /api/v0/pin/update?arg=cdf&arg=abc HTTP/1.1
> Host: localhost:5001
> User-Agent: curl/7.60.0
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Access-Control-Allow-Headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
< Access-Control-Expose-Headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
< Content-Type: application/json
< My-Header: v1
< My-Header: v2
< Server: go-ipfs/0.4.20
< Trailer: X-Stream-Error
< Vary: Origin
< Date: Fri, 26 Apr 2019 22:39:02 GMT
< Transfer-Encoding: chunked
< 
{"Message":"invalid 'ipfs ref' path","Code":0,"Type":"error"}
```

(it seems this last thing also affects `pin/add` and `pin/rm`)

**Comment by Stebalien** [comment]
>  with a single argument or no arguments returns a text error

There are a couple of issues here:

1. We don't actually know what encoding the user wants when parsing the arguments list, that's why this case is different. I'm not sure if we _can_ fix that because we make this decision based on the `enc` param which we haven't necessarily parsed yet. However, we could switch the default to JSON.
2. We default to JSON errors everywhere else (unless the user specifies `enc=text`). This is a _bit_ inconsistent because we default to _text_ for non-errors.

>  /pin/update always returns the given arguments (as ipfs-paths) in the responses, however /pin/add returns the resolved CIDs (and not paths):

We should be returning the resolved cids, IMO. We can _probably_ also return bare CIDs. That's a breaking change but I kind of doubt many users are relying on it.

**Comment by ianopolous** [comment]
We rely heavily on pin update. (It's 99% of our pin calls) So please involve us in evaluating any breaking changes.

**Comment by Stebalien** [comment]
@ianopolous I've flagged you on the PR. Basically:

1. `ipfs pin update /ipfs/QmA /ipfs/QmB` will now return `{Pins: ["QmA", "QmB"]}` instead of `{Pins: ["/ipfs/QmA", "/ipfs/QmB"]}`.
2. `ipfs pin update /ipns/QmA /ipns/QmB` will now return the _resolved_ names in the response (like as is done in `ipfs pin add`).

**Comment by ianopolous** [comment]
@Stebalien That sounds fine, we convert them to that form immediately on our end anyway, so just means less code for us. :-)

**Comment by kishansagathiya** [comment]
May be two more
https://github.com/ipfs/ipfs-cluster/pull/768#discussion_r280001535
https://github.com/ipfs/ipfs-cluster/pull/768#discussion_r280010178
