### ISSUE TITLE
Script to simplifiy gathering debug stats

### ISSUE THREAD

**Issue by magik6k** [ipfs/go-ipfs#6457]
Currently gathering debug info involves running some commands manually, and putting the files somewhere. We should have a script to automate that (bonus point for a tiny pastebin like service for those)

**Comment by Tajallah** [comment]
Hello, I'm new and I'd like to get started contributing to this project. I've never collaborated on github before and would like to work on this. How do I get started?

**Comment by Stebalien** [comment]
If you haven't already, read https://guides.github.com/introduction/flow/. Once you have, this script this issue is talking about needs to:

1. Run all the commands from https://github.com/ipfs/go-ipfs/blob/master/docs/debug-guide.md#beginning.
2. Compile the output files (along with a copy of the IPFS binary) into a single archive (e.g., using `tar`).

**Comment by Kubuxu** [comment]
There is also: https://github.com/ipfs/go-ipfs/blob/master/bin/collect-profiles.sh

**Comment by Tajallah** [comment]
Oh, it looks like that's already done then.

**Comment by Kubuxu** [comment]
Yeah, we just should mention it in our docs.

**Comment by Stebalien** [comment]
Given that this was just a documentation issue, I've filed a fix in https://github.com/ipfs/go-ipfs/pull/6486.
