### ISSUE TITLE
go-ipfs and js-ipld-dag-cbor produce different hashes for arrays

### ISSUE THREAD

**Issue by andrewheadricke** [ipfs/go-ipfs#6549]
These two commands produce a different hash result

go-ipfs:

```
echo '[1]' | ipfs dag put
```

js-ipld-dag-cbor:
```
var c = dagCBOR.util.serialize('[1]')
dagCBOR.cid(c).then(function(cid) {
   console.log(c.toString())
})
```

It appears they encode arrays differently. The js-ipld-dag-cbor appears to be creating a valid cbor byte stream.

I don't mind if the two different methods produce different hashes, although it seems to me they should produce the same. How can I go about adding binary cbor data produced by js-ipld-dag-cbor into go-ipfs? The API doesn't seem to allow it.

Also see https://github.com/ipld/js-ipld-dag-cbor/issues/113

**Comment by Stebalien** [comment]
The issue here is that JSON doesn't distinguish between float/int/etc. but CBOR does. You're seeing this in _go_ because go is strongly typed so we get the following:

1. Read data in as JSON, store numbers as float64.
2. Convert `[]float64` (float64 slice) to CBOR.

If we had started with `[]uint64` in go, we would have converted to the same thing as JS.

---

The solution is to avoid converting. Personally, I recommend either:

1. Using `cbor` for the `--input-enc`.
2. Even better, just use the `ipfs block` commands to put/get blocks directly.

If you're writing a _go_ program, I recommend using https://godoc.org/github.com/ipfs/go-ipfs-http-api#HttpApi.Dag.

**Comment by andrewheadricke** [comment]
Thanks @Stebalien i am creating the data with js-ipld-dag-cbor, I just discovered it was the numbers not the arrays causing the issue :)

Is it possible to save binary data with `ipfs block add`? I have a CBOR byte stream created from javascript, how to post it over the HTTP api as a binary block rather than text.

**Comment by Stebalien** [comment]
> Is it possible to save binary data with ipfs block add? I have a CBOR byte stream created from javascript, how to post it over the HTTP api as a binary block rather than text.

You can put/get binary using `ipfs block add` and `ipfs block get`.
