### ISSUE TITLE
MDNS not working in private network

### ISSUE THREAD

**Issue by kpp** [ipfs/go-ipfs#6579]
#### Version information:

go-ipfs version: 0.4.21-
Repo version: 7
System version: amd64/linux
Golang version: go1.12.5

#### Description:

On default configs MDNS not working in private network.
However if I set `Swarm.EnableAutoNATService = true` on bootstrap nodes and `Swarm.EnableAutoRelay = true` on clients they can find each other (ipfs swarm peers shows mutable connections on 192.168.1.X). Without an access to bootstrap nodes local peers still cannot find each other through MDNS.

**Comment by Stebalien** [comment]
Two possible issues:

* 0.4.21 has a bug that sometimes causes MDNS to fail (why I asked for a bug report; I needed the version). This has been fixed in 0.4.22.
* Some networks block multicast packets (which MDNS uses).
* If you're using IPFS private networks (swarm key), MDNS doesn't work at all. If, by private network, you mean "local LAN", then it should work in most cases (poor choice of naming on our part).

**Comment by kpp** [comment]
> This has been fixed in 0.4.22.

Confirmed
