### ISSUE TITLE
Memory leak over time 0.4.22

### ISSUE THREAD

**Issue by bclermont** [ipfs/go-ipfs#6617]
Follow up on #6508

I tested with 0.4.22, left it running for a while and here is ![Last 4 days memory usage](https://user-images.githubusercontent.com/474302/64150440-cf313d80-ce5a-11e9-98a9-b4d1d80ad2d2.png)

Also, here is [output of collect-profiles.sh](https://github.com/ipfs/go-ipfs/files/3568152/ipfs-profile-bangsar-2019-09-03T06.50.03%2B0000.tar.gz)

I know that upcoming Go 1.13 will help free RSS memory. I hope that there will be a new release of IPFS as soon as it's released.

Beside that, the metrics seem to indicate there is an continuously increasing memory

#### Version information:

docker image `ipfs/go-ipfs:v0.4.22`

installed [this helm chart from official helm/charts repo](https://github.com/helm/charts/tree/master/stable/ipfs)

**Comment by Kubuxu** [comment]
Are we using datastore peerstore? If not, this might be it.

**Comment by Stebalien** [comment]
> Are we using datastore peerstore? If not, this might be it.

Not yet.

---

Internally, go-ipfs is using ~320MiB. Go then keeps double that because "GC".

I'm seeing three memory leaks but, unfortunately, they're known ones:

1. Protocol lists for known peers: 56MiB.
2. Public keys for known peers: 60MiB.
3. User-agents for known peers: 26MiB.
4. Peer IDs of known peers: 10MiB.
5. Bandwidth metrics for known peers: 30MiB. You can turn this off by running `ipfs config --json Swarm.DisableBandwidthMetrics true`.

We should be able to drop the first 4 from memory by switching to an on-disk peerstore (or garbage collecting these things.

I've filed an issue in libp2p (https://github.com/libp2p/go-libp2p-peerstore/issues/93) as we don't even need to remember these values.

**Comment by Stebalien** [comment]
Closing in favor of https://github.com/libp2p/go-libp2p/issues/715.
