### ISSUE TITLE
When double-clicked on Windows, ipfs.exe should start the daemon

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#6633]
Currently, when a user double clicks on ipfs.exe on Windows, a terminal launches, some help text is printed, then the terminal exits. This usually blinks by faster than the user can see.

Instead, we should detect this case (if possible, see https://support.microsoft.com/en-us/help/99115/info-preventing-the-console-window-from-disappearing) and just launch the daemon in the background.

**Comment by kpp** [comment]
Why? Add a daemon.bat to start the daemon

**Comment by djdv** [comment]
Mainly this is because it's confusing to new users who are used to launching programs from their typical environment. Double clicking `ipfs.exe` provides no help or feedback to these users, it simply launches and disappears before they can even read the text.

However, there are also technical considerations here (that are minor, but let's talk about them anyway)
(stop reading here unless you like esoteric Windows knowledge)

`ipfs` doesn't rely on a full terminal or command interpreter to run. Windows provides a console host for CLI programs, which provides everything needed (without the need for `cmd` or a hosting terminal  outside of `conhost.exe`). It allows CLI programs like this to simply exist alone in the graphical environment, separate from a terminal.

Creating a batch file looks similar, but in actuality launches 2 programs prior to the target (the terminal (this persists), the cmd interpreter (this exits), and then a shared conhost (this persists)).
In the case of launching `ipfs` in a GUI environment on Windows, you would want to create a shortcut file (.lnk) with arguments, to launch `ipfs` directly, without any implied dependencies.

However, since the case of running `ipfs` without any arguments is already deemed not useful in this context, we can change the behaviour to just launch ourselves when we know we're in this setting.
(this was implemented here: https://github.com/ipfs/go-ipfs/pull/6646) without the need for users to know about our arguments ahead of time, and without needing them to create a launcher themselves.

![I shouldn't know this](https://user-images.githubusercontent.com/13862850/65426903-2c2b6e00-dddf-11e9-8e06-ad2f52f2528f.png)

**Comment by kpp** [comment]
Still #6646 is hacky.

> However, since the case of running ipfs without any arguments is already deemed not useful in this context, we can change the behaviour to just launch ourselves when we know we're in this setting.

This will add a different behavior based on how you launch ipfs.exe. You may receive several issues like "why ipfs does not start daemon when running from cmd.exe"?

And #6646 is a workaround for a users that are not so good with Windows cmd. Give a man a fish and you feed him for a day; teach a man to fish and you feed him for a lifetime.

**Comment by djdv** [comment]
(Pardon the wall of text, I'm trying to provide reasoning for these decisions, not trying to come off as dismissive. These are just my own opinions on it, and I'm open to hearing opposing views.)

>"why ipfs does not start daemon when running from cmd.exe"?

I would imagine the help text itself would clarify that. We still display it when run from inside a terminal.

>This will add a different behavior based on how you launch ipfs.exe. 

This seems fine to me personally. The purpose of the argument vector is to determine user intent. In this case we check both the arguments supplied, and inspect the environment to determine intent. I can't think of a scenario where a user would want the current behavior to happen, but the alternative of starting the daemon does seem in line with user expectations for this environment.
Most Windows programs are graphical, and launch without arguments.

That being said, if there are concerns around this, we shouldn't do it. But from my perspective, this is a direct improvement.
CLI users are unaffected, GUI users who have specific arguments supplied are unaffected, and GUI users who provide no arguments, start the service rather than having invisible program failure.

As an additional anecdote, a common standard program `vi`/`vim` has different launch behaviour depending on argv[0] (the binary name (example: `ex`)), and many programs have different launch behaviour depending on environment variables (including `ipfs` with things like the repo path, debug logging, etc.)
So it's not uncommon to have 2 users running the same version of a program, but see different results, depending on their environment/system. (whether this is good or bad though, I hold no opinion.)

>And #6646 is a workaround for a users that are not so good with Windows cmd. Give a man a fish and you feed him for a day; teach a man to fish and you feed him for a lifetime.

I think educating users on how to use `cmd` falls outside the scope of the project. We shouldn't exclude people who lack specific knowledge from running the service if they want to, and instead should seek to accommodate new environments and their users if we can. In a P2P network like this one, the more the merrier. :^)

>Still #6646 is hacky.

While hacky this is still the official documented way of handling it. If there are newer WINAPI methods to detect this, I'd rather use them where we can. But I'm not aware of them.

**Comment by kpp** [comment]
> We shouldn't exclude people who lack specific knowledge from running the service if they want to

I did not mean to exclude people from running the service =)

> Creating a batch file looks similar, but in actuality launches 2 programs

All I want to say is daemon.bat will be easy to inspect (with a Notepad), easy to run (even though it launches 2 programs; who cares?). It would be easy to maintain the code (no checks for `InsideGUI`). It will teach the users that you should launch ipfs.exe with `daemon` arg.
