### ISSUE TITLE
Is it possible to retrieve md5sum of an IPFS file

### ISSUE THREAD

**Issue by avatar-lavventura** [ipfs/go-ipfs#6674]
[gdrive](https://github.com/gdrive-org/gdrive), which is is a command line utility for interacting with Google Drive, can provide an information wheren when I provide `Google Drive folder ID` such as `gdrive info <folderID>`, if the upload file is a file, it returns its`md5sum`. Please note that if it is a folder it does not provide its `md5sum`.

```
$ gdrive info 1d_sRQ2xcyKCZ7FBhgaVrnrpM8zOrduTX
Id: 1d_sRQ2xcyKCZ7FBhgaVrnrpM8zOrduTX
Name: result-0x57b60037b82154ec7149142c606ba024fbb0f991-1Jbsgt68dg2jAlllmaYIDG__R0pz3CeWE-1.tar.gz
Path: 60bc9c6da9d7e819b94ebc3dc24ed037/result-0x57b60037b82154ec7149142c606ba024fbb0f991-1Jbsgt68dg2jAlllmaYIDG__R0pz3CeWE-1.tar.gz
Mime: application/gzip
Size: 4.8 KB
Created: 2019-09-19 21:40:19
Modified: 2019-09-19 21:40:19
Md5sum: 1d664d73a334212f2b53b90cb83775f3
Shared: True
Parents: 1Jbsgt68dg2jAlllmaYIDG__R0pz3CeWE
ViewUrl: https://drive.google.com/file/d/1d_sRQ2xcyKCZ7FBhgaVrnrpM8zOrduTX/view?usp=drivesdk
DownloadUrl: https://drive.google.com/uc?id=1d_sRQ2xcyKCZ7FBhgaVBnrpM8zOrduTX&export=download
```

=> Could `IPFS` provide similiar feature, where when I provide IPFS-hash of a file, could I obtain its `md5sum` without downloading the complete file (`ipfs object md5sum <ipfsHash>`)?

**Comment by Stebalien** [comment]
You'll _still_ have to download the complete file to your local node to compute the checksum. There's no way to convert some a CID of the file as stored in IPFS to a hash of the raw file without having a copy of the raw file.

We could, in theory, provide a command to do compute a hash server-side (inside go-ipfs) instead of sending the entire file to the client (e.g., in a command like `ipfs cat /ipfs/QmFoobar | md5sum`). However, there's very little to no benefit.

---

P.S., Please _never_ use MD5. It's completely broken and insecure.

**Comment by avatar-lavventura** [comment]
While long considered obsolete for secure cryptographic hashes, `MD5` and `MD4` remain adequate for checking file corruption. @Stebalien
