### ISSUE TITLE
Cannot verify ipfs on Mac.

### ISSUE THREAD

**Issue by Anu1601CS** [ipfs/go-ipfs#6756]
I am not able to verify ipfs on my mac.

<img width="586" alt="Screenshot 2019-11-09 at 11 47 35 AM" src="https://user-images.githubusercontent.com/30978328/68524008-f424af80-02e6-11ea-96b9-2f517b9b5bdd.png">

**Comment by Stebalien** [comment]
I believe the simple solution is to right-click on the binary and select "open". That _should_ allow you to verify the app and then run it from the command-line.

I believe extracting the archive containing go-ipfs via the command-line (instead of finder) should also bypass this.

The real solution is for us to start notarizing our macos distributions but that's a can of worms: https://github.com/ipfs/distributions/issues/273
