### ISSUE TITLE
Custom/local DNS name resolver support without ipfs server dns configuration

### ISSUE THREAD

**Issue by matyapiro31** [ipfs/go-ipfs#6915]
I'm using OpenNIC domain and want to go with ipfs web hosting, but any public ipfs gateway server don't support OpenNIC domain, pointing my domain to ipfs fails.

This will be a problem when using intranet.

Even if local ipfs server's dns configuration is correct, client has no way to check it.

So I want a feature of custom dns server.

**Comment by hsanjuan** [comment]
I've been looking into how we do `/ipns/domain` resolution.

For `.eth` we detect that suffix use `.eth.link`. This is a single domain (although I see things like `.kred`).

OpenNIC does not have (to my knowledge) a similar DNS-domain proxy that we can use similarly. We would need to use a Resolver with a custom dialer to their anycast servers (https://wiki.opennic.org/start).

I suppose there is a stable list of actual TLD domains under the OpenNIC federation (still to find the full one). People can apply for whatever new ones they want so it's subject to change.

Anyways, we could potentially support this so that people can get dnslink-ing etc on OpenNIC TLDs, which is probably a good thing and not overly different from supporting .eth.

**Comment by matyapiro31** [comment]
#6776 will solve this issue.

**Comment by matyapiro31** [comment]
@hsanjuan At first, how about adding function to return `500 internal server error` when DNS resolve failed?

**Comment by hsanjuan** [comment]
> @hsanjuan At first, how about adding function to return `500 internal server error` when DNS resolve failed?

Can you show where/how that does NOT happen already?

**Comment by lidel** [comment]
@matyapiro31  I believe setting custom DNS server won't be enough to support OpenNIC TLDs.

Context: go-ipfs performs additional [go-is-domain](https://github.com/jbenet/go-is-domain/) checks in both [namesys and http gateway code](https://github.com/ipfs/go-ipfs/search?q=go-is-domain&unscoped_q=go-is-domain). Recently added `.eth` support required PR against that repo: https://github.com/jbenet/go-is-domain/pull/13

First step to unblock use of OpenNIC would be to do the same: submit a PR extending `ExtendedTLDs` list with OpenNIC TLDs, then switch go-ipfs to updated version.

**Comment by matyapiro31** [comment]
@lidel I sent PR, but .eth is also not supported still now?

**Comment by lidel** [comment]
.eth is supported since #6448 (via https://eth.link).

Do you mind linking your PR?

**Comment by matyapiro31** [comment]
@lidel https://github.com/jbenet/go-is-domain/pull/15
Here.

**Comment by matyapiro31** [comment]
I think that I add special support for OpenNIC this time is faster answer now,
How about using http://proxy.opennicproject.org/ proxy for OpenNIC domain?

**Comment by lidel** [comment]
@matyapiro31 that "proxy" is a PHP script running on remote server, it won't work for go-ipfs. We need to merge your PR and switch go-ipfs to use updated domain validator.

**Comment by matyapiro31** [comment]
Those just solve opennic domain, but there's no idea to resolve custom dns server address.
I suggest that you use dns address as subdomain.

**Comment by lidel** [comment]
FYSA this will be closed when https://github.com/ipfs/go-ipfs/pull/8068 and https://github.com/ipfs/go-ipfs/pull/8071 land.
