### ISSUE TITLE
Hard to tell which is a file and which a directory in gateway index

### ISSUE THREAD

**Issue by renich** [ipfs/go-ipfs#6939]
LIke the title states, there is no difference when viewing files or directories. For example, my songs (CC-BY-SA): 
https://ipfs0.sjc.cloudsigma.com/ipfs/QmT4ecy4M1A2pJMMfStu9WV6TN3ydTBVE95V2UM23bDtim/renich/electronica/2010

There is a directory that is called: Rola Z (re-makes). You can't tell it's a directory. It looks the same as the files. 

Maybe, it would be good to add a slash at the end. Or some kind of icon or indicator that it's a directory.

**Comment by hsanjuan** [comment]
Unfortunately, we have no way of knowing whether that link points to a folder or a file without following it...

From the IPLD explorer:

http://localhost:5001/ipfs/Qmexhq2sBHnXQbvyP2GfUdbnY7HCagH2Mw5vUNSBn2nxip/#/explore/ipfs/QmT4ecy4M1A2pJMMfStu9WV6TN3ydTBVE95V2UM23bDtim/renich/electronica/2010

(all links are the same base58btc - cidv0 - dag-pb type. Only when parsing the internal protobuf after fetching the link we know if it is a folder or a file).

**Comment by renich** [comment]
OK. Wanted to report it because it isn't optimal as it is. Thank you for getting back so quickly @hsanjuan.

**Comment by Stebalien** [comment]
Basically, we do this _locally_ in `ipfs ls` but don't on the gateway because it's expensive (would require fetching 1 piece of data per file in the directory). This is one of those "will be fixed with unixfs 2.0" issues (https://github.com/ipfs/unixfs-v2). The plan is to start embedding basic file metadata into directories themselves.
