### ISSUE TITLE
Small added files do not return a CidV1 dag-pb multicodec

### ISSUE THREAD

**Issue by xmaysonnave** [ipfs/go-ipfs#6947]
#### Version information:
go-ipfs version: 0.4.23
Repo version: 7
System version: Debian buster Kernel 5.5.6-xanmod5 x86_64 GNU/Linux
Golang version: go1.13.7

#### Description:
Starting to generates cidv1 instead of cidv0.
Not sure what should be the defaul behaviour however :
- small files are not dag-pb  but raw instead
- large files are always dag-pb

1 - Small file - raw
[control-panel.txt](https://github.com/ipfs/go-ipfs/files/4285250/control-panel.txt)
ipfs add control-panel.txt --cid-version 1
https://cid.ipfs.io/#bafkreib277r64ixzbgtqgfumiv7d4evyztidhfqbk6wbiqizfrt5hepwsq

2 - Small file - dag-pb
ipfs add control-panel.txt
https://cid.ipfs.io/#QmdCootquw4nU55HmwdaCM1AzsvJYgpMRH2Tgrz9RRYk3s

3 - Large file
[assets.txt](https://github.com/ipfs/go-ipfs/files/4285254/assets.txt)
ipfs add assets.txt --cid-version 1
https://cid.ipfs.io/#bafybeidcqsw7gnd4y3jazkmqrsrsouxqy6fnelsqquykajzl2mumrguxhm

Current workaround. I always generate a V0 then convert it in V1...

Thanks

**Comment by ribasushi** [comment]
@xmaysonnave this is by design. Whenever you explicitly ask for `--cid-version=1` you also activate `--raw-leaves=true` here: https://github.com/ipfs/go-unixfs/blob/v0.2.4/mod/dagmodifier.go#L67-L70

You could always disable this with an explicit `--raw-leaves=false` but the real question is: why are you doing this? The PB-wrapping is rather inefficient and is a historical artifact at this point... Please expand on the underlying problem when time permits.

**Comment by xmaysonnave** [comment]
Thanks for your quick and detailed reply.
1 - Not sure to understand what's the PB wrapping your are talking about and the relationship between the cidv0 and cidv1. I was rather confused to see that the same file do not return the same cid codec whether or not I explicitly request a cidv1. The core motivation of this opened issue then.
2 - We started our cidv1 journey and are analysing consequances at every level (browser, dapp, nginx, etc...)
3 - Our users have a feature who let them export to IPFS content but we do not have any control on what they are exporting. Right now as stated in the first post I generate a v0 the convert it in v1.

**Comment by Stebalien** [comment]
> I was rather confused to see that the same file do not return the same cid codec whether or not I explicitly request a cidv1.

With CIDv0, the _only_ codec possible is dag-pb so we only produce dag-pb nodes. However, CIDv1 makes other codecs possible, so we encode blocks using the "raw" format.

You're still seeing dag-pb for _large_ files because the content doesn't fit into a single block. Therefore, the root block of the file is actually an indirect block that points to multiple raw blocks.

> Current workaround. I always generate a V0 then convert it in V1...

This is the correct approach if you want the underlying blocks to be the same in both CIDv0 and CIDv1. We actually have a global flag for this `ipfs --upgrade-cidv0-in-output ...`.

**Comment by xmaysonnave** [comment]
Thanks for your explanations. 
The situation is clear now.
