### ISSUE TITLE
ipfs add should allow adding CIDs

### ISSUE THREAD

**Issue by tmbdev** [ipfs/go-ipfs#7084]
Right now, the only way I can find to create a directory is with "ipfs -w add files..."

It would be good if "ipfs add" had the option to create a directory directly out of CIDs. This might be done in one of two ways:

- "ipfs add" directly recognizes "/ipfs/..." and "/ipns/..." paths and does the right thing
- with a command line option that says that the remaining arguments are hashes, not files.

**Comment by ribasushi** [comment]
The answer to the underlying problem is the [`ipfs object ...` sub-command tree](https://discuss.ipfs.io/t/how-can-i-wrap-existing-files-in-a-directory-from-the-command-line/7616/2)

The UX of having a "magical" path in `ipfs add` is rather icky. I personally would not mix path and CID concepts in the same command, the interface is already overloaded. But leaving the ticket open to see what others think.

**Comment by tmbdev** [comment]
Is there another command I can use for this operation? If not, then maybe it could simply be added as another command, like "ipfs wrap" or something.

**Comment by ribasushi** [comment]
> Is there another command I can use...

@tmbdev it's described and linked in my reply...

**Comment by Stebalien** [comment]
The right way to do this right now is `ipfs files`. That is, create a temporary directory, add your files, get the CID, pin it, delete the temporary directory. Or just leave your files in `ipfs files`.

**Comment by ribasushi** [comment]
> The right way to do this right now is `ipfs files`

Oh... Is `ipfs object patch` discouraged for some reason?

**Comment by Stebalien** [comment]
Yes. It doesn't work with sharded directories.

**Comment by tmbdev** [comment]
Thanks. Are those kind of merkeldag manipulations encouraged for end users for common operations like "stick all these files in a directory"? Is this going to work for all the complex edge cases?

Even if it works, it only allows adding links to existing objects. So, the way to use it would presumably be to wrap an empty file to get a directory node to get a directory node to add to in the first place, add-link all the links I want to add one at a time, then finally remove the empty file I initially added.

**Comment by RubenKelevra** [comment]
> Are those kind of merkeldag manipulations encouraged for end users for common operations like "stick all these files in a directory"? Is this going to work for all the complex edge cases?

Yes they are. MFS operations (via `ipfs files`) should work in all complex edge cases.

The only downside is currently the generation of many intermediate versions of a folder, if you going to add multiple files. It makes sense to use [badgers](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#badger-datastore) as file storage, not flatfs to speed up operations.

There's a new version of badgers coming soon(TM), which will require a convert of the complete datastore.

**Comment by RubenKelevra** [comment]
@Stebalien I agree with @tmbdev that it would be nice if you can add files and specify a CID of a folder in which they are "patched" in one operation - if you going to add a load of files you have to script it currently if you want to add them to an already existing folder.

**Comment by tmbdev** [comment]
> Yes they are. MFS operations (via `ipfs files`) should work in all complex edge cases.

@ribasushi suggested `ipfs object patch`, which is different from @RubenKelevra `ipfs files`.

It's not clear to me from the documentation what the relationship between MFS, IPFS, and UnixFS is. Do the MFS-related commands result in files/merkeldags that are fully compatible with the non-MFS tools? Anyway, I'll experiment a bit more. Thanks for the info.

**Comment by RubenKelevra** [comment]
The MFS are locally 'mapped' UnixFS elements. 

If you would modify a folder without MFS you need to unpin the old one and pin the new one, since you've changed the CID.

MFS handles this for you automatically: When you modify an folder in the MFS it will get a new CID but the path will stay the same.

You can lookup the CID of a folder in the MFS via `ipfs files stat --hash /foldername`.

You can look at this folder on a different node, without adding it to this node's MFS:

`ipfs ls /ipfs/<CID>`

And you can add the folder under a arbitrary name to the second node's MFS:

`ipfs files cp /ipfs/<CID> /foldername123`

The content will be guaranteed the same.

If you modify the content on one node, the content on the other note *won't* change.

It's also to note that a folder - and all it's files don't get immediately transferred when you add it with `files cp`.

The files and folders get transferred on access, but then stay permanently on your node.

This allows for fast access on large folders.

If you want to fetch the whole folder, you can simply run a pin followed by an unpin command:

`ipfs pin add <CID>; ipfs pin rm <CID>`

Not unpinning it again will lead to a permanent storage of this 'version' of the folder, regardless how you modify it in the MFS of this node.

This might not be what you want.

**Comment by hsanjuan** [comment]
@tmbdev I have opened a doc issue to track the suboptimal docs. We would be super grateful if you go here and provide more details of what you'd like to see and where https://github.com/ipfs/docs/issues/481 (particularly your journey on browsing the docs looking for what you wanted to find and where it should have been).

**Comment by RubenKelevra** [comment]
> However, I don't think it will help me. The reason for wanting to put a bunch of preexisting CIDs into a directory is because I'm using the urlstore extension with large files that I want to add in parallel. That is, the file sizes I'm looking at are between 1GB and 100GB, and they aren't stored on disk.

I really can't understand where your issue is. As far as I understand you can easily achieve the task this way:

1) create a local folder: `ipfs files mkdir /folder`
2) add a cid with a name: `ipfs files cp /ipfs/<CID> /folder/name`
3) repeat step 2 until all data is added to your folder
