### ISSUE TITLE
Add support Blake3, Argon2 and hide hashes

### ISSUE THREAD

**Issue by KonoromiHimaries** [ipfs/go-ipfs#7353]
* Your motivation. Why do you need the 
better privacy, to protect free speech

 * How the feature should work
https://github.com/BLAKE3-team/BLAKE3#readme
https://github.com/P-H-C/phc-winner-argon2#readme

**Comment by Stebalien** [comment]
Please describe the exact feature you want and provide a motivation for why the feature addresses your need.

**Comment by cryptoquick** [comment]
@Stebalien 
[ipfs-embed (rs)](https://github.com/ipfs-rust/ipfs-embed) supports Blake3 multihash by default. go-ipfs should allow for this to work to support interoperability without saying it's disabled because it's insecure. That's the whole point of multiformats, right?

https://github.com/multiformats/go-multihash/issues/121

An example ipfs-embed Blake3 multihash:
`bafyr4idgsqf6v6bxfntjercbk6j5jmm4cclci54io3tq33gi7mibeah3te`
