### ISSUE TITLE
[META] Commands Library Improvements

### ISSUE THREAD

**Issue by aschmahmann** [ipfs/go-ipfs#7493]
Using this issue to track the various proposals to improve the commands lib and CLI

- https://github.com/ipfs/go-ipfs/issues/3120
- https://github.com/ipfs/go-ipfs/issues/3056
- https://github.com/ipfs/go-ipfs/issues/3081
- https://github.com/ipfs/go-ipfs/issues/6326

**Comment by schomatis** [comment]
I think this can be closed since everything in the list is done.

**Comment by Arlodotexe** [comment]
> I think this can be closed since everything in the list is done.

I'm not so sure.

Kubo 0.26.0 deprecated `ipfs file ls`, and I was hoping to do some API consolidation while migrating the .NET libraries [in the shipyard](https://github.com/ipfs-shipyard/net-ipfs-core), but I found that `ipfs ls` hasn't been fully migrated to contain all the functionality of `ipfs file ls`.

As of 0.27.0, the main functional difference is that `ipfs ls` doesn't output the Size when provided with a file like `ipfs file ls` did. Consumers can still get this information using our API for `ipfs files stat`, but this is still an additional dependency that should be consolidated at the root api level along with `ipfs get`, `ipfs add`, `ipfs ls`.

I think this ticket was closed by mistake and may need to be reopened. The linked tickets were closed because they were consolidated into this meta-ticket, not as an indicator that they were completed. If they were completed, the backlinks from PRs seem to be missing on all 4 of them.
