### ISSUE TITLE
Huge amount of connected peers

### ISSUE THREAD

**Issue by ridenaio** [ipfs/go-ipfs#7503]
Hi, we are using `go-ipfs` as a library in our project. We have ~2500 active nodes in our private ipfs network. We faced the issue, that each node has an enormous number of connections. [This](https://github.com/ipfs/go-ipfs/files/4820136/golist.txt) is the output of `go list -m all` command.

We have this simple code which writes current peers count every 10 seconds.

```
info, err := api.Swarm().Peers(context.Background())
if err != nil {
	logger.Info("peers info", "err", err)
}
logger.Trace("", "peers count", len(info))
```

and we have [peers count](https://github.com/ipfs/go-ipfs/files/4820114/output.log) these statistics, where you can see, that sometimes almost all network is connected to this node.
```
TRACE[06-23|08:22:00.980] peers count=2152
TRACE[06-23|08:22:10.981] peers count=2518
TRACE[06-23|08:22:20.983] peers count=2512
TRACE[06-23|08:22:30.985] peers count=2520
TRACE[06-23|08:22:40.985] peers count=2472
TRACE[06-23|08:22:50.987] peers count=2199
```

Our settings:
```
    "ConnMgr": {
      "Type": "basic",
      "LowWater": 30,
      "HighWater": 50,
      "GracePeriod": "40s"
    }
```

In our project, we don't need tons of peers, because mostly each node has all the necessary content and we use ipfs for syncing purposes. We think that having such a big number of peers could cause performance issues. So, several questions.

1) Is it normal to have 2500 peers connected simultaneously with these settings?
2) Are there any other settings, which can limit the number of peers? (e.g. MaxPeers)
3) If there is no such setting, which components we need to overwrite or replace with our own implementation, to reduce total peer count (e.g ConnManager, or smth else)?

Thanks in advance.

**Comment by aschmahmann** [comment]
@ridenaio thanks for the report.

What does your setup look like? A couple thoughts on potential culprits.

1. All your peers are on the same network and MDNS is causing all the peers to constantly reconnect to each other. If this is the  case there are a few potential solutions available depending on how your application plans on working.
2. There's some application layer logic causing peers to constantly connect to each other

Also, if you're able to, I'd recommend updating to go-ipfs v0.6.0 since investigating issues at version numbers with changelogs associated is a bit easier than with a commit from the middle of a release cycle.

**Comment by ridenaio** [comment]
[This](https://github.com/ipfs/go-ipfs/files/4821601/output.log) is our log file on new ipfs `v0.6.0`. In 40 seconds after the start, it already had >1k peers. Our peers are worldwide, they are from different countries. As I have said, we use `swarm.key` for the private network. [Here](https://github.com/ipfs/go-ipfs/files/4821621/config.txt) you can find our full config file.

About application logic, we use already opened ipfs connections to open a permanent stream, which is used for our custom protocol. We use `SetStreamHandler` to  [accept](https://github.com/idena-network/idena-go/blob/master/protocol/gossip.go#L113) the stream for our protocol. We do not somehow close connections, we only [reset](https://github.com/idena-network/idena-go/blob/master/protocol/peer.go#L354) streams if needed. Max number of our simultaneously opened streams is 18.

**Comment by Stebalien** [comment]
Does every node have this high peer count, or only some? If many of your nodes are behind NATs, they won't participate in the DHT. That means the nodes that _do_ participate in the DHT will have to handle more inbound connections.

If you run `ipfs swarm peers --direction` and count the number of inbound versus outbound connections, you should be able to tell. If you're node has many inbound connections but few outbound connections, you probably have lots of nodes behind NATs.

**Comment by aschmahmann** [comment]
@ridenaio thanks for posting more info. From your config file it looks like you have:

```
    "EnableRelayHop": true,
    "EnableAutoRelay": true,
```

This is configuration is almost always a mistake as indicated in the docs https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#swarmenablerelayhop. By enabling both of these settings you are making your node advertise itself as a public relay to the entirety of your private network. This means it's very likely that the node will be connected to a huge number of peers (as well as relay their traffic). Did you mean to setup this node as a public relay, and do all of the nodes in your network have this same configuration?

**Comment by ridenaio** [comment]
@Stebalien yes, all nodes have this high peer count, it seems that our config file is not so good :)

@aschmahmann all peers in our network have same configuration. Most of our nodes are run on local computers and laptops, behind NAT. We have several bootstrap nodes and ~10-20% nodes running on VPS. So, the question is, what is the best way to setup our network?

**Comment by RubenKelevra** [comment]
@ridenaio have you considered applying the [server profile](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#profiles)?

As soon as those nodes "see" each other via mDNS they will do connections between each other.

The server profile will also avoid that all your nodes will try to dial private IP-addresses published in the DHT.

**Comment by aschmahmann** [comment]
> So, the question is, what is the best way to setup our network?

This seems like a question for discuss.ipfs.io, it'll make the results more searchable in the future and isn't really about bugs/features which is more what these github issues are for. I'm going to close this issue, since it seems like the problem was identified (i.e. badly configured node, where the documentation is fairly clear about the configuration options).

Nonetheless, since we're already here, here a few thoughts on network setup.

- The only NAT traversal mechanism currently supported in IPFS is port mapping (i.e. UPnP)
    - Now that QUIC is supported we'd like to use UDP based hole punching, but we don't have it yet.
- This means that if UPnP does not work on some local computer's router that that machine will have a difficult time providing that data to the rest of the network since no one else on the network will be able to contact them
    - If UPnP fails for nobody on your network then we're done, you can use go-ipfs default settings
    - If UPnP fails for a high percentage of your network then you may want to start thinking about using something like a shared VPN to get all the nodes to be able to talk to each other. There are alternatives here, but things get a bit complicated.
    - If UPnP fails for a low percentage of your network then you're probably best off setting up a few dedicated relay nodes. Since your network is isolated from the public IPFS network you can use your the advertise relays (i.e. your current configuration) for those nodes, but I wouldn't make every node a relay

Thanks for opening the issue and if you have more questions feel free to ask on discuss.ipfs.io
