### ISSUE TITLE
High CPU usage with go-libp2p-noise

### ISSUE THREAD

**Issue by ridenaio** [ipfs/go-ipfs#7540]
Hi, we are using `go-ipfs@0.6.0` as a library in our project. [This](https://github.com/ipfs/go-ipfs/files/4820136/golist.txt) is the output of `go list -m all` command.

Sometimes we see huge CPU spikes and ipfs starts to disconnect\reconnect a lot of peers at this moment. This problem appeared recently. We ran our application with `pprof` profiler and collected statistics during these spikes. It looks like `go-libp2p-noise` does a lot of work.

[profiling.zip](https://github.com/ipfs/go-ipfs/files/4925186/profiling.zip)

**Comment by thienpow** [comment]
2700 threads running in ipfs process for me on macbook pro

**Comment by Stebalien** [comment]
@thienpow I assume your issue is unrelated, right? If so, please file a new bug report with more information.

@ridenaio 

> Sometimes we see huge CPU spikes and ipfs starts to disconnect\reconnect a lot of peers at this moment. 

It sounds like something is forcing a disconnect, then your node is automatically re-connecting to all peers at once.

* Did you explicitly prefer the noise transport over the TLS transport? If not, I wonder if there's someone on the network running ephemeral/flaky nodes with the noise transport.
* Could you try disabling the noise transport: `ipfs config --json Swarm.Transports.Security.Noise false`. I'm wondering if we have a bug forcing a mass disconnect (unlikely but we may have something causing a mass internal timeout killing all connections).

**Comment by ridenaio** [comment]
We have tried to turn off `Noise`, `SECIO`, but the problem still exists. So, we can say that the problem not in `go-libp2p-noise`. This task can be closed then.
