### ISSUE TITLE
Limit number of connections per IP address

### ISSUE THREAD

**Issue by hsn10** [ipfs/go-ipfs#7543]
There is quite noticeable group of people running 16 IPFS nodes per ip. Its quite popular sport. I inspected mini IPFS node with 1024 open connections. and found 8 IP addresses with 16 distinct IPFS nodes on that particular IP which is 12.5% of total connections, there is another, larger group of people running 4 nodes per IP.

This is waste of my system resources. I need only one node from each group because these nodes will peer over LAN and find content on their peers easily.

I would like connection manager to be enhanced to allow just one node per each group. Also it would be helpful for IPFS node to publish admin email contact (if configured) like tor nodes do.

**Comment by bertrandfalguiere** [comment]
I think multiple peers per IP can be multiple things:
- Totally different applications that happen to be hosted on the same cloud provider and same machine
- Protocol Labs' "hydra boosters nodes", which try to be spread evenly accross Kad space for faster routing
- Badly configured services

In the first case, you want to keep the connections to all these nodes.
In the second case, I don't know if they share the same knowledge of the network/records. Asking one for a record will make you connect to the other so you need to allow connections to be made to several nodes on the same address.

I think what is important is to have connections to nodes in different parts of the Kad space not necessiraly on different IP.

Anyway, the less useful connections will be dropped eventually automatically. I suspect the groups of 16 nodes are highly stable, fast and highly useful nodes of PL or Cloudflare or Textile's infrastructure that are worth keeping. 

A confirmation from IPFS team that I'm correct would be nice.

**Comment by Stebalien** [comment]
Also, carrier grade NATs. A lot of nodes fall into this category.

> This is waste of my system resources. I need only one node from each group because these nodes will peer over LAN and find content on their peers easily.

This is not how IPFS works, unfortunately.

1. You need to be directly connected to a peer to fetch content from them.
2. We usually _keep_ connections because either:
    a. We're below the connection manager limit so we have no "pressure" to close them.
    b. The peer is actively using us.
    c. We're actively using the peer (e.g., for the DHT, bitswap, etc.).

Your case is probably a matter of 2.a. As long as you're running go-ipfs 0.6.0, I'd consider setting your connection manager limit really low (like 50 to 100). As of 0.6.0, we exclude connections we actually _need_ (active bitswap peers, some DHT peers, etc.) from the connection manager limits so this should be relatively safe.

---

In go-ipfs 0.7.0, we're adding some IP diversity requirements in the DHT which should incidentally fix (or at least reduce) this issue. Unfortunately, we can't simply restrict the number of connections to any given IP due to carrier grade NATs and the likes.
