### ISSUE TITLE
auto update DNS TXT record with thirdparty API

### ISSUE THREAD

**Issue by dassio** [ipfs/go-ipfs#7551]
for IPNS, i find the DNS text record seems to be the most straigt forward, you only need ipns://your.domain to get the content when you have IPFS companion installed, but it is true that you need to update the DNS text record everytime you update the content

i think of a work flow where you only need to name the subdomain once and later when you change the content the go-ipfs will auto update your DNS record with the new CID(using aws API or alike)

we can give option to users for using which thrid-party service

**Comment by olizilla** [comment]
> i think of a work flow where you only need to name the subdomain once and later when you change the content the go-ipfs will auto update your DNS record with the new CID(using aws API or alike)

These TXT DNS records are known as a DNSLink, you can see more info about them here https://dnslink.io/ - they should always either be set on the domain directly, or more commonly, at a `_dnslink.<my.domain.here>` subdomain.

There are a few modules to simplify updating dnslinks for various DNS providers...
- dnsimple - https://github.com/ipfs-shipyard/js-dnslink-dnsimple
- cloudflare -  https://github.com/ipfs-shipyard/dnslink-cloudflare
- digital ocean - https://github.com/ipfs/dnslink-deploy

If you want to set the dnslink once and not have to update it later then IPNS can help... IPNS lets you create a pointer to a CID that you can update, and you can set the value of the dnslink to be an IPNS address, that way you can manage the updates from your ipfs node rather than the dns providers api... as a command line adventure that might look something like this

```sh
# Get a CID for your hot new website
echo "hello" | ipfs add -q
QmZULkCELmmk5XNfCgTnCyFgAVxBRBXyDHGGMVoLFLiXEN

# publish that CID under the default IPNS key for your ipfs daemon
ipfs name publish QmZULkCELmmk5XNfCgTnCyFgAVxBRBXyDHGGMVoLFLiXEN
Published to QmS2H72gdrekXJggGdE9SunXPntBqdkJdkXQJjuxcH8Cbt: /ipfs/QmZULkCELmmk5XNfCgTnCyFgAVxBRBXyDHGGMVoLFLiXEN

# Set the *IPNS* address as a dnslink on your domain, e.g on dnsimple you could
DNSIMPLE_TOKEN=!!! npx dnslink-dnsimple --link /ipns/QmS2H72gdrekXJggGdE9SunXPntBqdkJdkXQJjuxcH8Cbt --domain <your domain here>

# check it
ipfs cat /ipns/<your domain here>
hello

# update your site to be even more rad
echo "✨🎷🐩" | ipfs add -q
QmWgA3p7XWE5gimmFRKPq8ypKXd4zNrp7steDqDvmRey76

# update the IPNS address to point to a new CID
ipfs name publish QmWgA3p7XWE5gimmFRKPq8ypKXd4zNrp7steDqDvmRey76
Published to QmS2H72gdrekXJggGdE9SunXPntBqdkJdkXQJjuxcH8Cbt: /ipfs/QmWgA3p7XWE5gimmFRKPq8ypKXd4zNrp7steDqDvmRey76

# see dnslink resolve to the latest, no dns update needed 🎉
ipfs cat /ipns/<your domain here>
✨🎷🐩
 ```

**Comment by olizilla** [comment]
More info here https://docs.ipfs.io/concepts/ipns/

**Comment by olizilla** [comment]
I'm gonna go ahead and close this issue out as IPNS provides a solution, and modules exist to simplify updating DNSlinks. Including code within go-ipfs to talk directly to various DNS providers APIs is unlikely to get support at this time. If I've misunderstood the proposal, please feel free to re-open with more detail.
