### ISSUE TITLE
IPNS, any way to make it faster?

### ISSUE THREAD

**Issue by jumpersdevice** [ipfs/go-ipfs#7632]
Hello all,
any way to speed up the publish of IPNS? I'm currently trying to use IPNS and update a small text file every 10 seconds or so. Any suggestions in how to make this better? Is there any alternative way to publish to ipns directly to let’s say the http gateways? Thanks

**Comment by aschmahmann** [comment]
@jumpersdevice if you use IPNS over PubSub (--enable-namesys-pubsub) then the publishes will happen quite quickly. However, the CLI/HTTP API will wait until the DHT publish is completed before returning.

Note that even with IPNS over PubSub the first publish needs to take a little while because it needs to advertise the pubsub topic into the DHT. However, after that things should be fast.
