### ISSUE TITLE
Files.mv works different according to target parent directory

### ISSUE THREAD

**Issue by rafaelramalho19** [ipfs/go-ipfs#7646]
#### Version information:

go-ipfs version: 0.5.1-8431e2e
Repo version: 9
System version: amd64/darwin
Golang version: go1.14.2

#### Description:

Using `ipfs.files.mv` in a file to 2+ top-level directory copies the file instead of moving it. When moving files from a path to a direct parent path, the `mv` command works fine.  

Considering we have the following file: `/animals/pets/dogs/doge.png`

If I do `ipfs files mv /animals/pets/dogs/doge.png /animals/pets/dogs`, it works as intended (file gets moved and original removed)

if I do `ipfs files mv /animals/pets/dogs/doge.png /animals/pets/` or `ipfs files mv /animals/pets/dogs/doge.png /animals/` the file gets copied instead.

**Comment by lidel** [comment]
@rafaelramalho19 I think you made a typo in your repro steps,   the thing that "works as intended" moves the files to the same directory it was in the first place(?)

I checked if moving to higher levels is broken, but was unable to reproduce it with a random file, below work as expected:

```console
$ ipfs files mkdir -p /animals/pets/dogs/
$ ipfs files cp /ipfs/bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi /animals/pets/dogs/doge.png
$ ipfs files mv /animals/pets/dogs/doge.png /animals/
$ ipfs files ls /animals/pets/dogs/
$ ipfs files ls /animals/pets/
doge.png
dogs
```

Can you check again? If the issue is there, it may be specific to a file or directory (in past I found odd behaviour which was caused by HAMT-sharding), so  you may want to share CID of initial `animals` directory for testing.

**Comment by rafaelramalho19** [comment]
You're right, could be a problem with the folder I was testing at the time, closing the issue.
