### ISSUE TITLE
aborted pinning loses already downloaded nodes

### ISSUE THREAD

**Issue by skliarie** [ipfs/go-ipfs#7748]
#### Version information:
go-ipfs version: 0.7.0-ea77213
Repo version: 10
System version: amd64/linux
Golang version: go1.14.4

#### Description:
When ipfs pin add --progress is aborted in the middle, it loses much of already downloaded nodes.
E.g. if before abort I see "Fetched/Processed 4241 nodes", then after starting again the pin, it starts from the beginning and takes many hours to get to the same point when it was aborted (as if all intermediate nodes were lost and need to be re-downloaded).

Frankly, it gets to the point faster than the first time I started pinning, but still takes unreasonably lots of time.

**Comment by aidanharris** [comment]
This is very noticeable trying to pin `/ipns/en.wikipedia-on-ipfs.org/wiki`, `ipfs pin add --progress QmehSxmTPRCr85Xjgzjut6uWQihoTfqg9VVihJ892bmZCp` takes an absurd amount of time to pin if it gets interrupted and you need to start again.

Due to the number of HTML files in this directory `ipfs ls -s QmehSxmTPRCr85Xjgzjut6uWQihoTfqg9VVihJ892bmZCp` takes a long time too.

**Comment by aschmahmann** [comment]
@aidanharris can you post your config file `ipfs config show`? How did you abort it, was it a network issue or did you kill the process (e.g. Ctrl + C)?

**Comment by skliarie** [comment]
I did CTRL+C, no network issues.
[ipfs_config_show.txt](https://github.com/ipfs/go-ipfs/files/5505237/ipfs_config_show.txt)

**Comment by Stebalien** [comment]
Pinning traverses the graph randomly. Progress will appear to be lost if you restart and randomly start traversing a part of the graph you haven't yet downloaded before you finish traversing everything you have downloaded.

**Comment by skliarie** [comment]
Got it, thank you.
