### ISSUE TITLE
ipfs not working with windows 10 powershell

### ISSUE THREAD

**Issue by TomCJones** [ipfs/go-ipfs#7756]
#### Version information:
go-ipfs version: 0.7.0
Repo version: 10
System version: amd64/windows
Golang version: go1.14.4

tried to post on doc page, but it give a nonsensical error about links - so there is an error of some sort there

#### Description:
fresh install of ipfs on current windows 10 home
accessing api from powershell
config
  "API": {
    "HTTPHeaders": {
      "Access-Control-Allow-Methods": [
        "PUT",
        "GET",
        "POST"
      ],
      "Access-Control-Allow-Origin": [
        "http://localhost"
      ]
    }
  },
results with get and post fail

PS C:\WINDOWS\system32> Invoke-RestMethod http://127.0.0.1:5001/api/v0/version
Invoke-RestMethod : 405 - Method Not Allowed
At line:1 char:1
+ Invoke-RestMethod http://127.0.0.1:5001/api/v0/version
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
PS C:\WINDOWS\system32> Invoke-RestMethod http://127.0.0.1:5001/api/v0/version -method POST
Invoke-RestMethod : 403 - Forbidden
At line:1 char:1
+ Invoke-RestMethod http://127.0.0.1:5001/api/v0/version -method POST
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by aschmahmann** [comment]
@TomCJones questions like this (i.e. how do I use my application with go-ipfs) are likely best answered on discuss.ipfs.io so more people can benefit from the answers. People tend not to look for or find information in closed GitHub issues.

That being said, what I think is happening is that `Invoker-RestMethod` by default uses a user agent which pretends it's a web browser, which it's not. go-ipfs adds extra security measures regarding HTTP requests that come from web browsers since the thing web browsers most frequently do is run untrusted code (i.e. websites).

This will work just fine though:

```
❯ Invoke-RestMethod http://127.0.0.1:5001/api/v0/version -Method Post -UserAgent "MyApp"

Version : 0.8.0-dev
Commit  : 9c5304a21
Repo    : 10
System  : amd64/windows
Golang  : go1.14.4
```

---------

BTW since you're using PowerShell, just a heads up that PowerShell doesn't like to play nicely with binary data (there are a number of issues on this including https://github.com/PowerShell/PowerShell/issues/1908) and so for go-ipfs commands that input/output binary data you may want to do one of:
1) Utilize commands that work with inputting/outputting to/from file names so that PS doesn't have to deal with them (and if there isn't one file a feature request)
2) Use cmd
3) Use one of the various hacks online (do some Googling for "powershell pipe binary data") to get PowerShell to work with piping binary data
