### ISSUE TITLE
IPFS_PATH notworking

### ISSUE THREAD

**Issue by CGsama** [ipfs/go-ipfs#7805]
#### Version information:

go-ipfs version: 0.7.0-ea77213e3
Repo version: 10
System version: amd64/linux
Golang version: go1.14.9

#### Description:

Tried both way, but ipfs only start repo on snap path, and /ipfsrepo/ubuntu still empty

```
$ IPFS_PATH=/ipfsrepo/ubuntu ipfs init
generating ED25519 keypair...done
peer identity: 12D3KooWEAn7ZszToMCz1Ux5G145Cp4Qm1YvwggfprzPEAP9N8TD
initializing IPFS node at /home/ubuntu/snap/ipfs/common
Error: ipfs configuration file already exists!
Reinitializing would overwrite your keys.

$ export IPFS_PATH=/ipfsrepo/ubuntu
$ ipfs init
generating ED25519 keypair...done
peer identity: 12D3KooWPHyr2Rjo8qduMwXPPUMNvFXyJhre73w8w6keQBcViBf3
initializing IPFS node at /home/ubuntu/snap/ipfs/common
Error: ipfs configuration file already exists!
Reinitializing would overwrite your keys.


```

**Comment by CGsama** [comment]
its snap problem

**Comment by NCGThompson** [comment]
> initializing IPFS node at /home/ubuntu/snap/ipfs/common

Snap, by default only allows IPFS to access that directory. However, you can easily give it access to peripheral storage by following [this guide](https://ubuntu.com/blog/a-guide-to-snap-permissions-and-interfaces).

I am not saying doing that will fix it, but it definitely won't work if you don't do that. In my case, Snap is overriding my preferences because ["cgroup v2 is not fully supported yet"](https://github.com/ubports/ubports-installer/issues/1448) so I don't know if it will work for me.

If you haven't already, change your permission settings and report back please.
