### ISSUE TITLE
Error in `config show`:  case mismatch in config

### ISSUE THREAD

**Issue by eminence** [ipfs/go-ipfs#7818]
#### Version information:

go-ipfs version: 0.8.0-rc1-02d15ac41
Repo version: 11
System version: amd64/linux
Golang version: go1.15.2

#### Description:
After upgrading/migrating from  `0.7.0-ea77213e3` to `0.8.0-rc1-02d15ac41` I get this error when running "config show":

```
$ ipfs config show
Error: case mismatch in config, expected "Pinning" but got ""
```

My config file doesn't have any `"Pinning"` fields (since I'm using the same config from when I was running 0.7.0.  I didn't manually add any fields, and it appears that IPFS didn't automatically migrate the config)

**Comment by lidel** [comment]
## Workaround for v0.8.0-rc1

@eminence thanks for reporting this!

Until we fix this in RC2, you can fix on your own by adding and removing a dummy service:

```console
$ ipfs pin remote service add noop http:///example.com foo
$ ipfs pin remote service rm noop
$ ipfs config show
```

Apologies for inconvenience! :bow: 

## Details 

Seems that we did not caught this because `ipfs init` produces:

```json
"Pinning": {                                                                                                                                                                                                    
  "RemoteServices": null                                                                                                                                                                                        
}   
```

If I manually remove that from `config`, I get the same error

```console
Error: case mismatch in config, expected "Pinning" but got ""
```

@petar I believe you are going to refactor how we sanitize `ipfs config show` in https://github.com/ipfs/go-ipfs/pull/7798, and that should fix this bug as well?

**Comment by eminence** [comment]
No apologies needed, this is why RC releases exist 😄
