### ISSUE TITLE
IPNS nocache when querying via IPFS gateway

### ISSUE THREAD

**Issue by krishraghuram** [ipfs/go-ipfs#7851]
I see that `ipfs name resolve` has a `--nocache` option, which allows me to ignore the local cache and get the latest ipfs cid associated with ipns name.

When I make a call via the ipfs gateway, like `http://127.0.0.1:8080/ipns/<name>`, is it possible to make it not use the ipns cache ?

I could not find any way to do it as of today, but I think this will be good to have.

#### Suggestions:
I'm thinking something like this would be good, `http://127.0.0.1:8080/ipns/<name>?nocache=true`.

Alternatively, having a command line option to ipfs daemon , that completely disables the caching of ipns records also works for my use-case. I'm thinking something similar to the `--enable-gc` and `--enable-pubsub-experiment` that we have now, say `--disable-ipns-cache`.

**Comment by lidel** [comment]
@krishraghuram adding this at the consumer end (gateway) is unlikely: main worry is that it would open public gateways to abuse AND we avoid exposing low level IPFS internals on the gateway paths (`/ipfs/`, `/ipns/`).  Gateway is HTTP-interop for `get/cat`, and API port exposes `/api/v0` more advanced commands.

So I'm closing this, however instead of changing how gateway works, you may try:

1. When you publish to IPNS, set `lifetime` to a lower value, for example:
    ```console
    $ ipfs name publish -t 5m /ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsM
    ````
    The above will publish a record with TTL of 5 minutes, but you can pick even lower value:
    >  `-t`, `--lifetime`   string - Time duration that the record will be valid for. Default: 24h.
    >  This parameter accepts durations such as "300s", "1.5h" or "2h45m".  Valid time units are  "ns", "us" (or "µs"), "ms", "s", "m", "h".
2. If you really, really need to resolve a third-party name without use `nocache`, then you can use the `/api/`:  [`/api/v0/name/resolve?nocache`](https://docs.ipfs.io/reference/http/api/#api-v0-name-resolve)

**Comment by krishraghuram** [comment]
Hey, thanks for the answer.
I knew that the HTTP API and the Gateway are two different things, but I'm understanding the difference only now.
HTTP API allows full control over ipfs, just like the CLI.
Gateway is a workaround for clients that don't have access to native IPFS.
