### ISSUE TITLE
Add memory ballast to reduce latency on new allocations

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#7935]
I've just found [this document](https://blog.twitch.tv/en/2019/04/10/go-memory-ballast-how-i-learnt-to-stop-worrying-and-love-the-heap-26c2462549a2/) and couldn't find any code in go-ipfs which implements this, while the Go runtime code still appears to be the same.

So in theory this could help to reduce the response time when new memory gets allocated, especially when there's a high amount of load on a server.

The downside is slightly higher memory consumption since the cleanup isn't as promptly anymore. But I think a 45% reduction in API response time in their workload could translate to some improvements in IPFS as well. Especially for DHT requests since this data is probably cached in memory anyway.

On data requests, the results might look different since the IO is probably adding a lot of latency.

@Stebalien what do you think? :)

**Comment by Stebalien** [comment]
This would have to be a very advanced feature tuned (by users) to specific workloads because one ballast may be correct for one workload while another might need a 10x ballast.

A better approach might be:

1. Set the GC Percent to -1 to disable automatic GC.
2. Run GC when we reach some threshold (or somehow learn the correct threshold?).

It's also unclear how useful this would be a we often have the exact opposite problem. Unlike twitch, we a lot of long-lived allocations (minutes) for every peer we're connected to and use object pools extensively to avoid taxing GC. This means we have a lot of built-in "ballast" and often end up failing to return memory to the system.

We implemented https://github.com/raulk/go-watchdog to solve this particular problem in lotus.

---

However, I'd love to see an investigation. Want to try adding some ballast and reporting back how it affects memory/CPU usage (when idle, when adding data, etc)?

**Comment by RubenKelevra** [comment]
> However, I'd love to see an investigation. Want to try adding some ballast and reporting back how it affects memory/CPU usage (when idle, when adding data, etc)?

I think it could be especially interesting to add ballast on some operations, like large pinning and/or running the GC - where we need to analyze a lot of data which is usually just stored in the DB.

I'm definitively interested in doing this :)


> This would have to be a very advanced feature tuned (by users) to specific workloads because one ballast may be correct for one workload while another might need a 10x ballast.
> 
> A better approach might be:
> 
> 1. Set the GC Percent to -1 to disable automatic GC.
> 2. Run GC when we reach some threshold (or somehow learn the correct threshold?).

How about monitoring the system load and try to anticipate when the system might want some memory back instead? 

On Linux there's this nice Pressure Stall Information available, which is quite neat. So if memsome goes above 0% we should definitively continuously cleanup to give the system more room to work with. But if there's more than say >1 Gigabyte of "Free" memory, we might just want to suspend the GC for a while until this changes.


> It's also unclear how useful this would be a we often have the exact opposite problem. Unlike twitch, we a lot of long-lived allocations (minutes) for every peer we're connected to and use object pools extensively to avoid taxing GC. This means we have a lot of built-in "ballast" and often end up failing to return memory to the system.

Yeah, I know that there are some issues with that. I was wondering if running the GC in larger intervals might also help with this, since it might be able to discard larger blocks, leading to larger used fragments?
 
> We implemented https://github.com/raulk/go-watchdog to solve this particular problem in lotus.

I'll have a look at it :)

**Comment by RubenKelevra** [comment]
Okay, I'll dig deeper into this topic and close this ticket for now, since it's hardly actionable.

When I find something which does better in ABX comparison I'll open a ticket for this.
