### ISSUE TITLE
ipfs update repo tool fs-repo-migration can exe in the same directory

### ISSUE THREAD

**Issue by godcong** [ipfs/go-ipfs#7948]
System variables must be set every time fs-repo is executed, which is relatively inconvenient.
I added some changes, when fs-repo and ipfs are in the same directory, then it can be executed without setting.

**Comment by aschmahmann** [comment]
The fs-repo-migrations in general is under a rework as is its integration into go-ipfs. Currently you can solve this just fine by putting the fs-repo-migrations binary in your PATH. However, even supporting that behavior seems like it could be a bit of a trap for users in the event they update go-ipfs, but forget to update the migrations binary.

Under what situation would you be manually putting the fs-repo-migration binary in the same place as go-ipfs and expecting go-ipfs to run the binary for you instead of just manually calling the migration binary itself?

**Comment by godcong** [comment]
Because I keep failing when I need to use `fs-repo-migrations`

**Comment by Stebalien** [comment]
Unfortunately, blindly running the repo migrations from the current directory is not an option as it makes it much easier for an attacker to trick a user into running untrusted code.

The options for now are:

1. Set PATH to include the directory where you installed fs-repo-migrations.
2. Let go-ipfs fetch/run fs-repo-migrations for you.
3. Manually run the fs-repo-migrations command.
