### ISSUE TITLE
enable Swarm connect to use any relay when in private network mode

### ISSUE THREAD

**Issue by ehsan6sha** [ipfs/go-ipfs#7963]
Currently when ipfs is using swarm.key and in private network mode, it cannot use relay nodes that do not share the same swarm.key to connect to other nodes that are behind NAT and unreachable. This makes private network almost un-usable.
Can we enhance the behaviour so that it does not require the swarm key for the relay when it is dialing another node with the same swarm key through a relay?

**Comment by Stebalien** [comment]
Unfortunately, while technically possible, I'm going to have to say that this feature will almost certainly never exist in go-ipfs itself. It would require having go-ipfs spin up _two_ libp2p nodes and join _two_ networks. It would also require some pretty invasive changes to the relay transport.

The "private network" feature is designed to allow for completely separate networks and generally requires _some_ amount of private infrastructure for bootstrappers, relays, etc. (even if that "private infrastructure" is just a few stable nodes).

Basically, it would introduce a fair amount of complexity to support a feature that goes against the point of private networks to some extent.

---

However, I do have some good news. There has been work under way to:

1. Implement hole punching.
2. Implement a "limited" relay mode that _all_ nodes can enable. "Limited" relays will relay a very limited amount of data for a limited number of peers to enable coordination for hole-punching.

When this lands, this should eliminate the need for dedicated relays for most nodes (those where hole punching works). See: https://github.com/libp2p/go-libp2p/issues/1039.

We can revisit this issue in the future if this turns out to be insufficient, but the solution will likely involve turning nodes inside the private network into full relays rather than allowing private networks to use the public relays.
