### ISSUE TITLE
Support --output-enc cbor in dag get command 

### ISSUE THREAD

**Issue by tysonzero** [ipfs/go-ipfs#8085]
This would mirror `--input-enc cbor` in `dag put` command.

Currently inputting cbor files into ipfs is easy, but getting them back out seems difficult.

**Comment by aschmahmann** [comment]
This seems doable and somewhat useful since it does a path traversal before returning the data, but generally dealing with binary data on the CLI/HTTP API is a bit of a pain unless the data is treated like a file/request body.

My guess is that doing `ipfs block get` will handle the job most of the time (and `ipfs resolve` can be used for path traversal when needed).

**Comment by tysonzero** [comment]
Ah yes `ipfs block get` seems equivalent to `ipfs dag get --output-enc cbor`.

Similarly `ipfs block put --format cbor` seems equivalent to `ipfs dag put --input-enc cbor`.

Leaving the issue open as it seems like it'd be more consistent to have it anyway to mirror `dag put`, but that solves my short term needs.

**Comment by aschmahmann** [comment]
@tysonzero transcoding via `ipfs dag get` is now supported by #8440
