### ISSUE TITLE
Flaky test: TestPeersTotal

### ISSUE THREAD

**Issue by aschmahmann** [ipfs/go-ipfs#8135]
https://app.circleci.com/pipelines/github/ipfs/go-ipfs/4610/workflows/d1451a93-9637-482c-b9e1-f1914dfaa687/jobs/51152/tests#failed-test-0

```
=== RUN   TestPeersTotal
2021/05/12 20:33:38 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
    TestPeersTotal: metrics_test.go:45: expected 1 peers transport, got 2
--- FAIL: TestPeersTotal (0.16s)
```

After re-running it is green, so filing this issue so we don't forget to fix this).

**Comment by masih** [comment]
Looking at [CircleCi config](https://github.com/ipfs/go-ipfs/blob/master/.circleci/config.yml#L92), it looks like `gotest` job runs on [Docker](https://github.com/ipfs/go-ipfs/blob/master/.circleci/config.yml#L34-L42). To set `sysctl` we need to run that on a `machine` executor; See [docs](https://circleci.com/docs/2.0/executor-types/#using-machine).

Running that job on `machine` will have longer start-up time, and will potentially involve installing go manually.  
@aschmahmann Do we want to make this change?

**Comment by aschmahmann** [comment]
@masih the UDP buffer size should be an independent problem from the flaky test, it's just a data transfer efficiency thing.

At the moment it doesn't seem worthwhile to change the setup to run as a machine, especially given that we'd like to move towards using GitHub Actions #8348

**Comment by schomatis** [comment]
The test on which this one is based

https://github.com/ipfs/go-ipfs/blob/ef0428af407410d7f7e98ec0b3e57afd8c828031/core/corehttp/metrics_test.go#L15

has been fixed for the same error in https://github.com/libp2p/go-libp2p-swarm/commit/0538806be79cf321e79253cecaec8c9b0d2a7167.

@aschmahmann I'm not sure how to fix this as I don't know the original design rationale behind the test nor the function we are testing. The original fix changes its test to track peers instead of open connections (because of what's explained in the commit message) but in our function being tested [we track connections](https://github.com/ipfs/go-ipfs/blob/ef0428af407410d7f7e98ec0b3e57afd8c828031/core/corehttp/metrics.go#L163) and I imagine changing that to tracking peers instead would have unintended side effects in the callers consuming this information.

**Comment by BigLep** [comment]
Next step is for @petar to look to identify next step.  We may not need this if this test is a copy from libp2p.

**Comment by petar** [comment]
I've added more logging to the test for now, so that next time it breaks we can understand why the connections are established over different transports.

**Comment by schomatis** [comment]
@petar Following up on this:

On the extra [logging](https://github.com/ipfs/go-ipfs/pull/8479), we will normally dial _both_ TCP and QUIC/UDP simultaneously and add both connections to the list, see the [swarm dial worker logic](https://github.com/libp2p/go-libp2p-swarm/blob/87ff7aca8ae058f7fd7bd9ada6bb255fe1b0b3a8/swarm_dial.go#L464-L513) for more details.

As mentioned [above](https://github.com/ipfs/go-ipfs/issues/8135#issuecomment-920081471) this is already acknowledged upstream and that is why https://github.com/libp2p/go-libp2p-swarm/commit/0538806be79cf321e79253cecaec8c9b0d2a7167 no longer checks the list of connections but explicitly the list of peers in its own test (because one peer might have more than one active connection).

I think we should port this fix here as well, consulting the peer list instead of the connection list where appropriate. My main doubt is understanding the actual purpose of [`PeersTotalValues`](https://github.com/ipfs/go-ipfs/blob/ef0428af407410d7f7e98ec0b3e57afd8c828031/core/corehttp/metrics.go#L158-L171) to decide how to best do that.

**Comment by petar** [comment]
@schomatis I agree. The ipfs test should use peer count, and not be dependent on the underlying implementation of swarm (which can vary the connection count per peer).

**Comment by schomatis** [comment]
Ok, will push something for this next week.

**Comment by BigLep** [comment]
Per 2021-11-12 verbal and slack: the test should be updated to assert on the number of peers (not the number of connections).

@galargh: if you have other comments/context from Slack, feel free to add.

**Comment by galargh** [comment]
Nothing to add, https://github.com/ipfs/go-ipfs/issues/8135#issuecomment-962291976 says it all.

**Comment by schomatis** [comment]
Picking this up again.
