### ISSUE TITLE
Restarting node with invalid pin index takes excessive time

### ISSUE THREAD

**Issue by gammazero** [ipfs/go-ipfs#8149]
#### Version information:
- 0.9.0-rc1-1c2fc6b
- 0.8.0-48f94e2
- 0.8.0-48f94e2

Appears to be all versions starting with 0.8.0

#### Description:
Restarting a node, that has an invalid pin index, is taking excessive time before the node is operational.

On a node with a large number of pins (1.4M in the case observed), it took almost 90 minutes for the node to come online following rebuilding its recursive pin indexes.

The logs contain this error message, after which everything begins working:
```
21-05-19T23:38:22.749875+00:00 localhost ipfs[1756272]: 2021-05-19T23:38:22.749Z#011INFO#011pin#011dspinner/pin.go:709#011invalid recursive indexes detected - rebuilt
```

To see this message, set the log level to `info`: `GOLOG_LOG_LEVEL=info`

#### Notes
Likely approaches to fixing this include:
- Pinner improvement to reduce the possibility of an invalid index (or shrink the part that's invalid), or to make it much more efficient to do a repair.
- Using a separate datastore for blocks than non-blocks so that we can have sync-writes turned off for non-blocks, but turned on for non-blocks (this will mimic the FlatFS + levelDB behavior).

**Comment by Stebalien** [comment]
Can't we just sync writes for the index? Alternatively, we could do some write-ahead logging, replaying on error, instead of setting a dirty bit and rebuilding on error.

**Comment by petar** [comment]
Three possible solution:

(1) Shard keys into a 100 independent copies of the pinner datastore. This is the quick hack route.

(2) Use a relation database backend. This has the benefit of accommodating increasing complex relational semantics, which are expected in upcoming projects/features (e.g. ipld backlink/parent indexing).

(3) Rewrite the pinner to use a write-ahead log together with a state snapshot. This is the correct solution in the sense that it is lightweight and can be reused to implement arbitrarily complex relational semantics.

**Comment by petar** [comment]
In IPFS, the pinner is used with badger and 'ipfs add' invokes sync after pinning an entire IPLD tree. @Stebalien's suggestion reduces the chances that the process dies between a write and a sync (by orders of magnitude for most files and directories). This PR https://github.com/ipfs/go-ipfs-pinner/pull/13 confirms that moving to sync-on-every-pin strategy is not hurting happy-path performance much.

**Comment by aschmahmann** [comment]
@petar how different is the approach in ipfs/go-ipfs-pinner#13 from what's happening in go-ipfs (i.e. IIRC we should be calling flush after individual pin operations externally such as https://github.com/ipfs/go-ipfs/blob/ef866a1400b3b2861e5e8b6cc9edc8633b890a0a/core/coreapi/dag.go#L29)? Doing this internally will help, but maybe not enough.

An alternative idea that might work (thoughts @petar @Stebalien?) is that since my understanding is the issues are coming from the non-atomic nature of updating the indicies that we could insist that the pinner takes a datastore that understands transactions which both levelDB and Badger should support.

What's been stopping us from doing this so far is that generally indirection such as the mount datastore https://github.com/ipfs/go-datastore/blob/4ee0f58273906f63b05ea8957d9133a31586e881/mount/mount.go#L66 stops us from being able to make assertions like `datastore.(TxnDatastore)`. However, given that all pins are now under `/pins` (instead of in the blockstore) we should be able to add a function to the mount datastore like `GetInnerDatastore(path)` and then assert that either the Datastore is a TxnDatastore, or it supports `GetInnerDatastore(path)` and that datastore supports transactions, before we pass it into the Pinner.

**Comment by BigLep** [comment]
2021-07-15 status:
1. https://github.com/ipfs/go-ipfs/pull/8180 has been deployed to PL infra.  
2. We need to check in on the work @gammazero has been doing to see if we should still proceed given https://github.com/ipfs/go-ipfs/pull/8180 appears to be working.

**Comment by BigLep** [comment]
Related: https://github.com/ipfs/go-ipfs-pinner/pull/15

**Comment by BigLep** [comment]
2021-07-20 status:
1. We've given instructions to George to deploy https://github.com/ipfs/go-ipfs-pinner/pull/15
2. If pinner deployment goes well, deploy to all hosts in our cluster.

Exit criteria: as long as it's not breaking anything, we'll merge.

Assuming no problems the week of 2021-07-26, we'll merge.
