### ISSUE TITLE
Add support for /ipns/{dnslink}?doh-url= (shorter + follows existing curl --doh-url )

### ISSUE THREAD

**Issue by johnnywu-namebase** [ipfs/go-ipfs#8172]
This issue arises from a chat between Namebase team and @lidel from Protocol Labs about integrating Handshake with IPFS

Given the goals of:
- IPFS doesn’t want to choose winners
- IPFS wants to decouple from ICANN and support non-ICANN namespaces
- IPFS wants to avoid introducing privacy and security risks in implicit defaults
- IPFS wants the alternative namespaces to be DNS compatible. Preferably they can use DoH endpoints 

IPFS can accomplish these goals while supporting non-ICANN namespaces by adding a “doh-resolver” query parameter that can be used with gateways to specify which resolver to use. This parameter would override any DNS.Resolvers settings. The “doh-resolver” parameter can be set to a DoH url or to a key as a shorthand. Ie ?doh-resolver=https://query.hdns.io/dns-query can be equivalent to ?doh-resolver=hns

**Comment by Stebalien** [comment]
1. What alternatives were considered?
2. How is this intended to be used?

Given what I can see here, I can't see how this could work:

1. It doesn't work with subdomain gateways and/or browser origins. If I switch resolvers, I should get a new browser origin for security reasons.
2. Users will likely remove the trailing "resolver" part and wonder why things don't work.
3. This is a very easy way to trick users into thinking they're visiting the "real" website while actually visiting a phishing website through some malicious resolver.
4. This will cause go-ipfs to make HTTP requests to random servers... we do make libp2p requests to random servers, but this potentially worse.

**Comment by johnnywu-namebase** [comment]
Thanks for the great questions! I'm non-technical so I'm hoping you can help clarify your concerns for me:

1. Do you mean alternatives to Handshake resolution with IPFS? The preferred resolution method is posted at: https://github.com/ipfs/go-ipfs/issues/8173 but this one is meant to be a quicker and hacky way to get HNS to work with IPFS
2. What do you mean? The goal is to have HNS included as an option for linking domains to IPFS websites https://docs.ipfs.io/how-to/websites-on-ipfs/link-a-domain/

1. I think it does work with subdomain gateways (see HNS.to). You can try visiting my personal websites on Handshake (johnnywu/ and home.johnnywu/) through HNS.to (johnnywu.hns.to and home.johnnywu.hns.to). What do you mean by "browser origins"?
2. Ah I wasn't aware this was existing user behavior, would this be a deal breaker? 
3. Hmm could you walk me through a specific example how someone might use this to phish users? It's not totally clear to me yet
4. I'm a little lost on this one, why would making HTTP requests to hdns.io be an issue? Anyone can also run their own Handshake resolver too

**Comment by aschmahmann** [comment]
> Hmm could you walk me through a specific example how someone might use this to phish users? It's not totally clear to me yet

Let's say there's a DNSLink record held by you at johnnywu.hns.to that point to `bafygoodcid` and I give you the link `https://dweb.link/ipns/johnnywu.hns.to?doh-resolver=https://query.hdns.io/dns-query` that will behind the scenes resolve to `bafygoodcid` since the query.hdns.io resolver is asked what `_dnslink.johnnywu.hns.to` maps to and gets back `/ipfs/bafygoodcid`.

But what if I make a bad DoH resolver `evildns.tld` and ask a user to resolve `https://dweb.link/ipns/johnnywu.hns.to?doh-resolver=https://evildns.tld/dns-query`? The user could instead see `bafybadcid`.

> I think it does work with subdomain gateways

As a a bonus this hurts origin isolation because both `https://dweb.link/ipns/johnnywu.hns.to?doh-resolver=https://query.hdns.io/dns-query` and `https://dweb.link/ipns/johnnywu.hns.to?doh-resolver=https://evildns.tld/dns-query` will end up turning into the same subdomain `johnnywu-hns-to.ipns.dweb.link` which means both `bafygoodcid` and `bafybadcid` would have access to the same cookies, bad info, etc.

**Comment by Stebalien** [comment]
> Do you mean alternatives to Handshake resolution with IPFS? The preferred resolution method is posted at: #8173 but this one is meant to be a quicker and hacky way to get HNS to work with IPFS

Yep. And thanks for the link. And yeah, that solution works quite well.

> What do you mean? The goal is to have HNS included as an option for linking domains to IPFS websites https://docs.ipfs.io/how-to/websites-on-ipfs/link-a-domain/

I was wondering if this was going to be some kind of "internal use only" thing for browsers. I.e., browsers integrating go-ipfs would tack on the intended resolver when applicable. That would alleviate some of my UX/security concerns.

> I think it does work with subdomain gateways (see HNS.to). You can try visiting my personal websites on Handshake (johnnywu/ and home.johnnywu/) through HNS.to (johnnywu.hns.to and home.johnnywu.hns.to). What do you mean by "browser origins"?

We're slowly deprecating the "path" based gateway (`https://ipfs.io/ipns/foo.com`) because every website gets the same browser origin (shares cookies, local storage, etc.). We're moving to a subdomain-based gateway `https://foo-com.dweb.link` so every website gets a new origin/domain.

However, if an attacker can just tack on `?doh-url=evil-resolver.com` to use their own resolver, they could serve whatever page they want and steal the user's data.

> Ah I wasn't aware this was existing user behavior, would this be a deal breaker?

Consider `https://ipfs.io/ipns/johnnywu.com/very/long/path?doh-resolver=example.com`. Users are _used_ to trimming paths `https://ipfs.io/ipns/johnnywu.com` to go back to the root. This isn't really the deal-breaker, but it's a strong reason not to go with this solution.

> Hmm could you walk me through a specific example how someone might use this to phish users? It's not totally clear to me yet

Same as the browser origin issue. An attacker can send the user to `https://example-com.ipns.dweb.link?doh-resolver=evil-resolver.com` and the user will focus on `https://example-com.ipns.dweb.link` (the browser will even helpfully highlight this for them).

> I'm a little lost on this one, why would making HTTP requests to hdns.io be an issue? Anyone can also run their own Handshake resolver too

This is _mostly_ a non-issue. My concern is that go-ipfs currently only makes DoH requests to _user_ specified DNS servers. With this change, an attacker could trick a user making requests to an arbitrary DoH server (potentially attacker controlled).

For example, if not implemented _very_ carefully, this could be used to poison go-ipfs's DNS cache:

1. Attacker tricks tricks user into visiting some attacker-controlled page.
2. The page embeds an image pointing at `/ipns/google.com?doh-resolver=evil-resolver.com`.
3. Go-ipfs caches a malicious DNSLink record for google.com.
4. IPFS companion now redirects requests for google.com to an attacker controlled site.

In practice, a correct DNS cache would prevent this (e.g., by segregating the cache by origin). But my concern is opening up a new attack surface like this (I can pretty much guarantee that a first-pass implementation would have had this bug because we cache in a layer _above_ the resolver).

**Comment by lidel** [comment]
I agree phishing is an issue, but after thinking about this bit more the way bigger problem is **Origin sharing on subdomain gateways**:

```
https://en-wikipedia--on--ipfs-org.ipns.dweb.link/wiki/
https://en-wikipedia--on--ipfs-org.ipns.dweb.link/wiki/?doh-resolver=evil-resolver.com
```

Both share same Origin (`window.location.origin` = `https://en-wikipedia--on--ipfs-org.ipns.dweb.link`), which means  it is enough to click a  link with `?doh-resolver` once, and cookies/secrets are leaked to malicious CID. 


I don't see a way to work around this, which makes `?doh-resolver not a viable option, unfortunately :(

**Comment by johnnywu-namebase** [comment]
Thanks @aschmahmann and @Stebalien for the great explanations, it does seem like this route has some serious security vulnerabilities, agreed with @lidel to focus on [#8173](https://github.com/ipfs/go-ipfs/issues/8173) instead.
