### ISSUE TITLE
Faster gateway directory listings

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#8178]
Update 11/4(@schomatis): We need to refactor the gateway code to use `UnixfsAPI.Ls()` instead of `Get`.

Instead of resolving file types up-front in the gateway, we can take advantage of streaming HTML rendering (most browsers support this) by:

1. Returning an HTML body with the directory listing as fast as possible.
2. Streaming back some trailing style elements to "update" the directory listing with file types.

That way the directory listing appears immediately, and icons for file-types will be filled in as new `<style>` elements get sent back to the browser.

Alternatively, we could do this with some javascript. But I'd _like_ to avoid that if possible.

**Comment by lidel** [comment]
Update around go-ipfs 0.13:  

- When we have https://github.com/ipfs/go-ipfs/pull/8758 and https://github.com/ipfs/go-ipfs/issues/8823 we can stop fetching child blocks in dir-index-html code, and return listing immediately.  
- Child information could then be fetched via `?format=raw|dag-json|dag-cbor` and updated asynchronously, with some sane limits (eg. only items visible in the browser viewport). Fetching as `dag-cbor` will be most bandwidth-efficient, but we could implement `raw` vasriant first, and then improve  performance when we have cbor option.

**Comment by lidel** [comment]
quick thought on a band-aid for this:
- we should detect when dir is over N items and only render  that + add footer saying it's too big, and suggest using the CLI  `ipfs ls -s --size=false --resolve-type=false $BIG_DIR_CID`
- this would be a band-aid, but probably easy to implement in a few lines of go

**Comment by lidel** [comment]
@schomatis would you be interested in doing the band-aid described above, so we could ship it in go-ipfs 0.13? Let's go with N=5000 for now.

**Comment by schomatis** [comment]
Assigning. If this is time sensitive I'm probably not the best person though, but will give you an update on this this week.

**Comment by schomatis** [comment]
Sorry, just now reading the band-aid alternative: yes, seems like a quick fix I can implement to help alleviate this.

**Comment by schomatis** [comment]
@lidel Need some clarifications:

A. On the objective of this issue, I'm not clear which is the performance downgrade we're trying to fix. From the OP:

> Instead of resolving file types up-front in the gateway

From what I see in the code we don't fetch the type information but [guess it](https://github.com/ipfs/go-ipfs/blob/f855bfe6ef8fe8a2633df889ce766cddc8d0effb/core/corehttp/gateway_indexPage.go#L106-L115) from file name extension (which is something we already have available in the directory node itself).

B. Guessing about any other potential performance issues, the only potential other fetch is to get the hash of the file in the [path resolver](https://github.com/ipfs/go-ipfs/blob/f855bfe6ef8fe8a2633df889ce766cddc8d0effb/core/corehttp/gateway_handler_unixfs_dir.go#L119-L124). We have that available in the directory but it's not exposed in the `Node` [interface](https://github.com/ipfs/go-ipfs-files/blob/9b481f40778c3b1e65a229248c7f0b730ef72b1e/file.go#L16-L24). (This may not even be a real network fetch. I'm not familiar with our path resolver; it might just fetch the directory DAG node locally. I'll need to take a closer look if necessary.)

C. On the band-aid, assuming there is some performance hit somewhere, **we don't know upfront how many entries a directory has** (at least for the HAMT case, which is probably the type of big directory this issue has in mind). We can't limit upfront by its size since this is being continually streamed (is maybe _this_ the performance issue we're trying to address in the first place?). In any case, what we could do is add a timer and if the directory hasn't been fully iterated stop there and add the warning proposed.

**Comment by schomatis** [comment]
Reading the original issue that spawned this one, https://github.com/ipfs/go-ipfs/issues/7495, I now see we're conflating two different listing mechanisms:

* `ipfs ls` command (original issue), using `UnixfsAPI.Ls()`: without setting `-size=false --resolve-type=false` it indeed fetches independently every entry in the directory (with its performance hit).
* Gateway listing (this issue here), using `UnixfsAPI.Get()`: we do _not_ fetch directory entries (except in the potential path resolution of point B above to get the hash, but that's a big maybe, and even if that were true we could just get it from the directory itself).

We need to clearly distinguish between the two, possibly having independent issues (since each mechanism has its independent code; the gateway is not just calling `ipfs ls`/`UnixfsAPI.Ls()` behind the scenes).

**Comment by schomatis** [comment]
(Marking as blocked until we clarify all this.)

**Comment by lidel** [comment]
This should unblock you:

- This issue is about gateway behavior in `gateway_handler_unixfs_dir.go` when no `index.html` is present (when HTML listing is generated), don't worry about `ipfs ls`, it already has flags that solve the perf problem:
  ```
  ipfs ls -s --size=false --resolve-type=false bafybeiggvykl7skb2ndlmacg2k5modvudocffxjesexlod2pfvg5yhwrqm | wc -l
  ```
- Indeed, iiuc `UnixfsAPI.Get()` does not fetch child blocks, however  inside `for dirit.Next()` loop we do fetch them via  `ResolvePath` call (`Node().Size()` is reading Size based on root block of  each child)
- My understanding is that band-aid would count how many times we called `dirit.Next()` and break out of the loop when we hit some number. That way we only fetch 5k+1 blocks.
  - If this helps, you can use `bafybeiggvykl7skb2ndlmacg2k5modvudocffxjesexlod2pfvg5yhwrqm` for testing.
    This dir was originally reported by @alanshaw  to load slow on gateway (it has 10100 items :exploding_head:)

**Comment by alanshaw** [comment]
🙏 This would be **super** useful - folks are uploading NFT drops with directories of 10k+ items to NFT.Storage and are getting confused when trying to view them on the gateway - it times out and they assume their upload did not complete successfully.

**Comment by lidel** [comment]
@alanshaw  check https://github.com/ipfs/go-ipfs/pull/8853/files#pullrequestreview-942930258 – I've tested it with `bafybeiggvykl7skb2ndlmacg2k5modvudocffxjesexlod2pfvg5yhwrqm` and loads as soon the root node arrives.
