### ISSUE TITLE
should use less threads

### ISSUE THREAD

**Issue by bmwiedemann** [ipfs/go-ipfs#8260]
I was wondering why some parts of ipfs are slower than I expected and using so much CPU power and then I noticed that

```bash
strace ipfs --help 2>&1 | grep clone
```

shows 5 threads being created when just the help text is requested. While thread creation is relatively lightweight, there are also around 770 `futex` syscalls for synchronizing those. And all of that is not needed, because help text output cannot be parallelized anyway.

Starting an [emptygo](https://github.com/bmwiedemann/onelinerbenchmark/blob/master/emptygo.go) program takes around 2ms. That is 1 ms more than an empty statically linked C program using uClibc. On the same machine, running `ipfs --help > /dev/null` takes at least 26ms and when running it as `time taskset 1 ipfs --help > /dev/null` it takes at least 98ms.

There is certainly room for improvement.

**Comment by Stebalien** [comment]
Unfortunately this issue is not actionable, and likely not the real issue.

1. I can't just "make ipfs use less threads". Go decides when/where to spawn threads.
2. All of our commands spawn goroutines (and go will likely spawn threads) for simple tasks like waiting for signals/cancellation, logging, etc.

This is also certainly not why IPFS is slow and/or uses CPU. That's usually do to other background tasks, connections, bitswap, etc.
