### ISSUE TITLE
Cannot build IPFS from source

### ISSUE THREAD

**Issue by unbeatable-101** [ipfs/go-ipfs#8269]
#### Version information:

go-ipfs version: 0.9.0-179d1d150
Repo version: 11
System version: arm64/darwin
Golang version: go1.16.5
#### Description:

I ran 
```shell
git clone https://github.com/ipfs/go-ipfs.git
cd go-ipfs
make build
```
and the build failed, here is the output 
[Terminal Saved Output.txt](https://github.com/ipfs/go-ipfs/files/6834147/Terminal.Saved.Output.txt)

**Comment by aschmahmann** [comment]
From your terminal output:
```
go build  "-asmflags=all='-trimpath='" "-gcflags=all='-trimpath='" -ldflags="-X "github.com/ipfs/go-ipfs".CurrentCommit=ae306994a" -o "cmd/ipfs/ipfs" "github.com/ipfs/go-ipfs/cmd/ipfs"
# github.com/ipfs/go-ipfs/cmd/ipfs
/opt/homebrew/Cellar/go/1.16.5/libexec/pkg/tool/darwin_arm64/link: /opt/homebrew/Cellar/go/1.16.5/libexec/pkg/tool/darwin_arm64/link: combining dwarf failed: unknown load command 0x80000034 (2147483700)
```

This looks like you have some weird issue with your Go installation (some Googling shows that this looks a bit like https://github.com/golang/go/issues/29539).

I tried doing a fresh `brew install go` followed by `git clone` and `make install` on a Macbook Pro with an M1 (it looks like you have an M1 device also) and it built just fine. You may want to try uninstalling + reinstalling Go and trying again, or else filing an issue in the Go repo since they may have some questions for you on reproducibility.

**Comment by unbeatable-101** [comment]
That didn't work for me, I opened an issue at https://github.com/golang/go/issues/47269

**Comment by unbeatable-101** [comment]
I can now build after installing go 1.17rc1
