### ISSUE TITLE
is dnslink and ipfs is supposed to be slow at the first load time?

### ISSUE THREAD

**Issue by dongnguyenattrace** [ipfs/go-ipfs#8476]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Description

Every time I uploaded my website to ipfs (with new CID generated), then I open the uploaded website, it is very slow to load and some js files return 404/524 status. After some tries, it loads normally again.

I'm using DNS link with Cloudflare IPFS gateway
pining service:  infura
gateway: cloudflare-ipfs.com

is DNS link and IPFS is supposed to be slow at the first load time?

**Comment by Stebalien** [comment]
1. It can take some time to advertise content on the network.
2. DNS propagation can take minutes. That's not something we can fix.

What's your DNS TTL?

**Comment by dongnguyen9186** [comment]
@Stebalien 
Sorry but now it is still very slow(I've deployed to ipfs and config hash in DNSLink in TXT record in the last 24hours). My site was fast in the last few weeks, it has downtime but just 1min-5min to be fast on the first try. I don't think it is a DNS TTL thing, I set it auto every time. 

some problems:
- infura link seems  to be very slow to load the first time, also some files load return 404 https://bafybeiga3cpj7qhiutcl4nrxqzv3gmi7ry2yo7xftk2nhqysdfvjg2fuhe.ipfs.infura-ipfs.io/
- It is always slow until I open it the first time, after some days, it sometimes very slow to load
Is it because cloudflare gateway or ipfs thing?

**Comment by Stebalien** [comment]
> It is always slow until I open it the first time, after some days, it sometimes very slow to load
Is it because cloudflare gateway or ipfs thing?

Once you load it once, it'll get "cached" on the gateway. I assume the gateway in question garbage collects once every few days at least, which means the next attempt to load it will have to fetch it.

Now, I have no idea why loading inside _infura_ is slow the first time, you'd have to ask them. But in general, public gateways aren't going to highly reliable. See https://github.com/ipfs/go-ipfs/issues/6383.

Unfortunately, I don't think there's anything we can do to help with this directly (other than to just keep on trying to make IPFS faster and more reliable).
