### ISSUE TITLE
filestore expects moved file when adding a new version of a folder

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#8948]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

built from source

### Version

```Text
go-ipfs version: 0.13.0-dev-74aff245d-dirty
Repo version: 12
System version: amd64/linux
Golang version: go1.18.1
```

### Config

default, just filestore enabled

### Description

Steps to reproduce:

- Add a folder via filecache:
`ipfs add --pin=1 -r --nocopy --cid-version 1 --raw-leaves --hash blake2b-256 -w /path/to/folder/`
- Unpin the folder:
`ipfs pin rm $CID`
- Move a file in the folder on disk:
`mv /path/to/folder/old_file_name.bin /path/to/folder/new_file_name.bin`
- Add the new version to ipfs via filecache:
`ipfs add --pin=1 -r --nocopy --cid-version 1 --raw-leaves --hash blake2b-256 -w /path/to/folder/`

After adding a bunch of files it aborts with:

```
Error: open /path/to/folder/old_file_name.bin: no such file or directory
```

**Comment by RubenKelevra** [comment]
Doing `ipfs repo gc` and then the second `ipfs add` fixes this. But it would be nice not to need this. I mean, if a file doesn't exist anymore but is somehow still linked to certain blocks, just ignore this and delete the reference and add the new file?

**Comment by RubenKelevra** [comment]
Or add a way to scan for blocks which are no longer available as files and delete them.

**Comment by schomatis** [comment]
> This does not catch the error:

What you want is `ipfs filestore verify`.

The undocumented contract in the experimental filestore feature would read something like "once a file is part of the filestore you can't touch it: it belongs to the ipfs repo, not to you". Renaming that file is like renaming a key in the repo `mv ~/.ipfs/blocks/JX/CIQFI ...`. I'm not saying this is a good thing, but it's not particular to this use case (feel free to open a separate issue to discuss general filestore improvements; I'm not sure how tested this feature is.)

I'm closing this as I don't consider it a bug but I'm open to the idea (meaning you'll have to write the code but I can answer/review) of some smart detection mechanism that besides telling you "we don't have that CID anymore in disk" takes care of removing that CID-path entry from the filestore also. I'd suggest submitting a new issue with a brief description of this to further discuss it before writing code: some people (I'm not even sure how many users we have of this) might object saying that if a path is missing they'd rather just hear about it to replace it instead of doing an implicit move (and perhaps have an explicit `ipfs filestore mv` command, which I'm guessing will have more chances of getting accepted as it won't change the current UX).
