### ISSUE TITLE
Gateway error when using subdomains

### ISSUE THREAD

**Issue by hsn10** [ipfs/go-ipfs#9046]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

ipfs-update or dist.ipfs.io

### Version

```Text
0.13.0
```

### Description

access to http://bafybeibvc5cdxldrcjihnoy6r2x3uuaib3rhy55c4uwaptdepzgoz7g5jq.ipfs.localhost:8080/safari-pinned-tab.svg

will trigger

ipfs resolve -r[ /ipfs/bafybeibvc5cdxldrcjihnoy6r2x3uuaib3rhy55c4uwaptdepzgoz7g5jq/safari-pinned-tab.svg](https://ipfs.io/ipfs/bafybeibvc5cdxldrcjihnoy6r2x3uuaib3rhy55c4uwaptdepzgoz7g5jq/safari-pinned-tab.svg): func called on wrong kind: "LookupBySegment" called on a data.Bytes node (kind: bytes), but only makes sense on map or list

I believe it should be reproducible.

**Comment by aschmahmann** [comment]
The error might be a little arcane (and you can file an issue about that), but this bug report is incorrect.
1. Nothing to do with subdomains - try http://localhost:8080/ipfs/bafybeibvc5cdxldrcjihnoy6r2x3uuaib3rhy55c4uwaptdepzgoz7g5jq/safari-pinned-tab.svg and see the same error
2. The path you specified does not exist `bafybeibvc5cdxldrcjihnoy6r2x3uuaib3rhy55c4uwaptdepzgoz7g5jq` is a UnixFS file and as a result does not have a `/safari-pinned-tab.svg` component.

I can tell that this is the `almonit.eth` website, so almost certainly you mean to use `bafybeig5acoljar3xf6clme5yo54issnj4bsjn7wjkcfkldggefkhkuvku` rather than `...jq` which is the CID for the UnixFS directory `..ku`'s index.html file.

Also, general support help should go to discuss.ipfs.io
