### ISSUE TITLE
move to using ~/.ipfs

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#970]
from `.go-ipfs -> .ipfs`

**Comment by shizeeg** [comment]
why not $XDG_CONFIG_HOME/ipfs ?
it's kinda standard:
http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by whyrusleeping** [comment]
This has been discussed before, and decided against. (although I do not recall the specific reasoning)

**Comment by jbenet** [comment]
Yeah, @mildred wants this too.

I don't know how widely used XDG is. I'm not opposed to having the option of being compatible with it, but i don't think it makes sense as a default to force upon people. 

```
> echo $XDG_CONFIG_HOME
>
```

**Comment by mildred** [comment]
> I don't know how widely used XDG is.

Most GNOME, XFCE, Qt and KDE apps, and many others :

* fontconfig
* epiphany
* FreeCAD
* libvirt
* libreoffice
* LyX
* gtk
 ImageMagick
* XFCE
* VLC
* gconf
* gajim
* chromium
* 0install
* GnuNet
* VirtualBox
* Inkscape
* *and many more*

I don't know how you managed to have an empty `~/.config` and `~/.local/share` directory, but mine is far from empty:

    $ ls ~/.config | wc -l
    203
    $ ls ~/.local/share | wc -l
    105

**Comment by whyrusleeping** [comment]
```
whyrusleeping@idril ~> ls ~/.config/ | wc -l 
28
whyrusleeping@idril ~> ls ~/.local/share | wc -l
11
```

There are a few things there, but...

```
whyrusleeping@idril ~> ls -a ~ | grep "^\." | wc -l
74
```

People can set `IPFS_PATH` to `$XDG_HOME/.ipfs` if they want, but it primarily looks like a gtk thing.

**Comment by mildred** [comment]
I don't want to repeat myself too much, but the XDG spec separate three kind of files:

* configuration files: small text files generally. What you want to use to configure applications: `~/.config`
* cache files: you can safely delete these because they can either be computed again or found fron the network. In `~/.cache`. This include thumbnails and web cache files
* data files: the current application state. These are not configuration files, and cannot be recovered in case they disappear. This is in `~/.local/share`

Separating these can be useful. For example, I frequently `rm -rf ~/.cache` to clean up things, especially if I run out of disk space. Generally this is full of thumbnails. `~/.config` is what I want to backup absolutely, or keep in a Git repository to sync across computers. `~/.local`: I don't care that much but I won't remove it as easily as `~/.cache`. I might backup some of its contents.

This is also the reason why historical applications such as Mozilla Firefox still keep everything in `~/.mozilla`. They didn't took the time to separate these different files.

**Comment by mildred** [comment]
> uname -a
Linux celebdil 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
> echo $XDG_CONFIG_HOME
>

This is normal: this environment variable is empty by default. If it is empty, it has a default value of `~/.config`

> echo ${XDG_CONFIG_HOME:-$HOME/.config}
> /home/mildred/.config

**Comment by whyrusleeping** [comment]
@mildred so how would you recommend splitting up the repo?

**Comment by mildred** [comment]
I don't really know what's in .ipfs currently, but

* config: in XDG_CONFIG_HOME or XDG_DATA_HOME as this is a little more than configuration (servers and private key)
* logs: in XDG_DATA_HOME
* lock file, right next to the files it is locking (or perhaps XDG_RUNTIME_DIR)
* IPFS blocks unpinned, as in a web cache, in XDG_CACHE_HOME
* IPFS blocks, pinned, in XDG_DATA_HOME
* What's in datastore, I assume this contains the list of pinned blocks among other things, in XDG_DATA_HOME

**Comment by jbenet** [comment]
Someone can make an `xdgfsrepo` that splits up fsrepo to work that way, but it will _not_ be the default, and it will _not_ be supported with our standard migrations. we already have a hard time as it is with migrations, and we control the directory entirely. sorry @mildred -- very strong reasons for this one. we must have the entire fs-repo be virtualizable in one location on the system, so it can be loaded from remote systems -- including things like S3 -- through simply mounting a single location, and so that people can run multiple IPFS nodes by just setting the `IPFS_PATH` (or maybe a cli opt later). (i do this all the time to run multiple nodes.

**Comment by fazo96** [comment]
@jbenet maybe a simpler yet efficient solution would be to use XDG_CONFIG_HOME/ipfs if XDG_CONFIG_HOME is set, else just use ~/.ipfs

Having some other way (like a command line argument) to set the path to the ipfs folder would be a nice and appreciated alternative though :+1:

**Comment by jbenet** [comment]
You can use $IPFS_PATH already.




XDG_CONFIG_HOME may be ok, as well, as we keep the repo the same. @Mildred would that be acceptable for you?



—

**Comment by mildred** [comment]
@fazo96 @jbenet What about `XDG_DATA_HOME/ipfs` because `XDG_CONFIG_HOME` is for configuration files (small text files) and we have much more in the IPFS dir.

There is another aspect to this whole "where do we put our data?" thing. If IPFS is to be run as a system daemon, I would expect configuration to be in /etc and most of everything in /var. I think having a way to separate config and data would be valuable for this use case. (but this is another issue than this one)

**Comment by jbenet** [comment]
:+1:  to `XDG_DATA_HOME/ipfs`
