### ISSUE TITLE
Commands hang when run as an SSH command

### ISSUE THREAD

**Issue by dylanPowers** [ipfs/go-ipfs#981]
When running an IPFS command over SSH as a command parameter, the process will hang. Simplest test:

```
ssh <host> 'ipfs cat <some_hash>'
```

I figured this is possibly because a terminal isn't present, so I went digging around the ssh man pages and what do you know running `ssh <host> -t 'ipfs cat <some_hash>'` works because it adds in a "pseudo-tty". That's a suitable workaround for ssh, but I'm sure this could trip up other applications that like to run commands without a terminal present.

**Comment by jbenet** [comment]
@dylanPowers agreed! this likley needs to be fixed in the cmds lib

**Comment by whyrusleeping** [comment]
this is still an issue

**Comment by lgierth** [comment]
The fixes in #1263 are possibly related

**Comment by jbenet** [comment]
Would be nice to have a test case-- if we figure out what's hanging them we
can send those signals. Worst case if we cannot repro otherwise, maybe with
docker?

**Comment by magik6k** [comment]
This is fixed now

**Comment by hbarcelos** [comment]
I have a functional IPFS node. If I run:

```
ssh <host> 'ipfs add test.txt'
```
I get:
```
Error: no IPFS repo found in /home/ubuntu/.ipfs.
please run: 'ipfs init'
```

If I SSH into the VM and run the command interactively, it works just fine.

**Comment by aschmahmann** [comment]
@hbarcelos your issue seems fairly different from this one. go-ipfs is not hanging but instead cannot find the repo. If the solution for you isn't apparent from my comments below could you open a new issue specifically for this that contains more info about your setup such as the output of `ipfs version --all`, where you installed the binary from, and if you've changed the IPFS_PATH environment variable?

go-ipfs uses the IPFS_PATH environment variable to locate where the repository is. My guess is that you installed go-ipfs using snap and the IPFS_PATH is set to be handled by snap https://github.com/ipfs/go-ipfs/blob/0d63fbb6059ac3a5fa9b658984cb1de12ec6c80f/snap/snapcraft.yaml#L24

Or alternatively you manually set IPFS_PATH to a different location.

If the correct IPFS_PATH environment variables (whether yours or snap's) are not available to the non-interactive shell the you'll run into problems. For more info on how environment variables differ in interactive vs non-interactive shells see [here](https://stackoverflow.com/questions/216202/why-does-an-ssh-remote-command-get-fewer-environment-variables-then-when-run-man).

**Comment by hbarcelos** [comment]
@aschmahmann thanks a lot for the pointers.

In deed I had a custom `IPFS_PATH` and it was not being set on SSH non-interactive sessions because it was defined on my `~/.bash_profile`.

I managed to workaround by setting it to the correct value on `~/.ssh/environment`.
